### ISSUE TITLE
6.0.8 版本Zotero无法安装本插件？

### ISSUE THREAD

**Issue by Liliumhumboldtii** [l0o0/jasminum#101]
首次安装本插件，运行环境是 M1  MacBook Air，Mac OS 12.4，Zotero版本6.0.8。安装插件时提示：

![image](https://user-images.githubusercontent.com/48939434/172955647-3c88abaf-45e1-4e77-acd4-70f38a8cbd4a.png)

按照知乎网友提供的方法：“打开.xpi，修改 install.rdf 里的最大版本maxVersion为6.0.*即可。” 

再试，仍然不行。提示： "The add-on "%S" could not be installed. It may be incompatible with this version of Zotero."

是否需要一些更新以适应新版本Zotero？

**Comment by l0o0** [comment]
目前最新版本0.1.8，已经可以兼容Zotero 6版本了。不知道同学下载的是什么版本插件

**Comment by Liliumhumboldtii** [comment]
> 目前最新版本0.1.8，已经可以兼容Zotero 6版本了。不知道同学下载的是什么版本插件

确实是版本问题，已经安装成功，谢谢！
