### ISSUE TITLE
[姓名显示] 能否在创建者下显示张三、李四全部作者名字，而非张三等这样格式？

### ISSUE THREAD

**Issue by Huaweidev** [l0o0/jasminum#107]
* 需求：能否在创建者下显示张三、李四全部作者名字，而非张三等这样格式？
* 需求原因：有时候一眼扫过文献列表，需要快速查看文献所有作者，以便定位特定作者（但是不想用搜索的方式）。
* 需求解决办法：能否在创建者下不显示“等”字样，而显示所有创建者姓名？
* 需求截图显示：
![2022-07-07_000813](https://user-images.githubusercontent.com/10258421/177595763-3d7d6a90-8d29-455f-a13f-6057bce48571.png)

**Comment by Celcnu** [comment]
显示张三等很好了，我的只显示张等...

**Comment by l0o0** [comment]
这个需要应该是需要对源代码里的名字展示进行修改，估计有些难度。

**Comment by lin229088559** [comment]
> 显示张三等很好了，我的只显示张等...

我也是，他会自动把人名之间加个“，”
比如张三 变成“张，三”，然后显示 张等
我这辈子没这么无语过

**Comment by zepinglee** [comment]
https://github.com/normanleiden/zotero-plugin-full-creator 这个插件的功能似乎可以用于参考。

**Comment by jiaojiaodubai** [comment]
不符合本插件的定位。
