### ISSUE TITLE
下载学位论文pdf，没有权限

### ISSUE THREAD

**Issue by yeyun1999** [l0o0/jasminum#108]
下载学位论文pdf，没有权限
设置里是选的pdf，但是好像没有办法下载，选为caj可以下载，
希望当pdf无法下载时，自动下载caj

**Comment by east-fang** [comment]
网络本身就可以下载知网，但是用插件下载不了，有没有详细的讲解，谢谢了。

**Comment by l0o0** [comment]
@yeyun1999 @east-fang 两位同学是使用翻译器网页下载PDF，还是茉莉花插件下载？

**Comment by mcxthuee** [comment]
我使用chrome的插件和zotero的邮件添加附件都没成功。chrome的插件只能添加知网元数据，右键下载提示Jasminum抓取失败

**Comment by mcxthuee** [comment]
> 我使用chrome的插件和zotero的邮件添加附件都没成功。chrome的插件只能添加知网元数据，右键下载提示Jasminum抓取失败 ![1657765548889](https://user-images.githubusercontent.com/51448797/178885024-9b4954f3-1c3a-43db-a042-508e19e25275.jpg) ![image](https://user-images.githubusercontent.com/51448797/178885149-fc165709-126e-4a4d-9892-9df55c16bc44.png) 文献地址：https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CDFD&dbname=CDFDLAST2019&filename=1019030126.nh&uniplatform=NZKPT&v=cCDc1DAszCdsNux6rpgmlyjZB9KL_f0SYy8f-9udZfFmuQ0hoS2KG84mLFhDRtF7 另外已确认可以在知网可以直接下载pdf

更新了一下translator，chrome端可以自动下载pdf了~但是在zotero上邮件更新附件依然失败

**Comment by east-fang** [comment]
网页翻译器和茉莉花都不行
![GIF 2022-7-17 18-15-25](https://user-images.githubusercontent.com/106970346/179393848-eb2174e0-d9b7-4a5e-906c-06486231
![GIF 2022-7-17 18-16-25](https://user-images.githubusercontent.com/106970346/179393850-2c9edc22-8c7d-418d-aed1-5473ded692e4.gif)
dd3c.gif)
。

**Comment by yeyun1999** [comment]
我又可以下载了，不知道动了哪里？

**Comment by east-fang** [comment]
迷茫，我昨天找了下教程，发现下载这个和知网的防御机制也有关系，我准备利用油猴的知网PDF下载，下载PDF，再导入zotero中，再利用茉莉花和Zotfile。但是经过zotfile处理过的PDF旧没办法再次被茉莉花识别了。

**Comment by Sifan798** [comment]
同样的问题，希望博主可以帮忙处理一下

**Comment by l0o0** [comment]
@Sifan798 @yeyun1999 @east-fang @mcxthuee 下载PDF的功能是测试功能，目前还不能做到很高的成功率。而且我在校外。我开发时用的是校外VPN的cookie，成功率挺高。不过如果在校内的话，有同学反馈，成功率是挺低的。我觉得可能是我把某些参数漏了，导致下载请求过程出现问题

**Comment by l0o0** [comment]
> 迷茫，我昨天找了下教程，发现下载这个和知网的防御机制也有关系，我准备利用油猴的知网PDF下载，下载PDF，再导入zotero中，再利用茉莉花和Zotfile。但是经过zotfile处理过的PDF旧没办法再次被茉莉花识别了。

同学你结合油猴插件，是我下一步更新翻译器的方向，因为有了油猴插件的帮助，下载地址是比较稳定好找的，可能会提升浏览器插件的下载成功率。

不过看你的描述，我有点疑问。应该是先把下载后的PDF拉到zotero里进行识别。然后再zotfile重命名。我不知道你用zotfile处理后的文件名是什么样的？

**Comment by Sifan798** [comment]
> @Sifan798 @yeyun1999 @east-fang @mcxthuee 下载PDF的功能是测试功能，目前还不能做到很高的成功率。而且我在校外。我开发时用的是校外VPN的cookie，成功率挺高。不过如果在校内的话，有同学反馈，成功率是挺低的。我觉得可能是我把某些参数漏了，导致下载请求过程出现问题

感谢博主，茉莉花出的查找pdf附件功能**堪称伟大**！因为他可以弥补zotero connector抓取失败的情况，一项新的功能（**且是具有创新性**的功能）肯定是由于背后的无数努力。好的插件肯定要经过不断升级的过程，建议博主可以再完善一下相关功能😉。

**Comment by l0o0** [comment]
> > @Sifan798 @yeyun1999 @east-fang @mcxthuee 下载PDF的功能是测试功能，目前还不能做到很高的成功率。而且我在校外。我开发时用的是校外VPN的cookie，成功率挺高。不过如果在校内的话，有同学反馈，成功率是挺低的。我觉得可能是我把某些参数漏了，导致下载请求过程出现问题
> 
> 感谢博主，茉莉花出的查找pdf附件功能**堪称伟大**！因为他可以弥补zotero connector抓取失败的情况，一项新的功能（**且是具有创新性**的功能）肯定是由于背后的无数努力。好的插件肯定要经过不断升级的过程，建议博主可以再完善一下相关功能😉。

感谢鼓励，整得有点不好意思了

**Comment by longzhmm** [comment]
我发现当开启代理后，插件的期刊的下载功能还可以正常使用，但硕博论文下载功能就变得不再可用。你可以试试取消代理再下载硕博论文。

**Comment by east-fang** [comment]
> > 迷茫，我昨天找了下教程，发现下载这个和知网的防御机制也有关系，我准备利用油猴的知网PDF下载，下载PDF，再导入zotero中，再利用茉莉花和Zotfile。 但是经过zotfile处理过的PDF旧没办法再次被茉莉花识别了。
> 
> 同学你结合油猴插件，是我下一步更新翻译器的方向，因为有了油猴插件的帮助，下载地址是比较稳定好找的，可能会提升浏览器插件的下载成功率。
> 
> 不过看你的描述，我有点疑问。 应该是先把下载后的PDF拉到zotero里进行识别。 然后再zotfile重命名。 我不知道你用zotfile处理后的文件名是什么样的？

我的处理后文件名是，左振兴 et al_2021_基于DUS测试性状的亚麻测试品种遗传多样性分析。不知道是哪个油猴的插件。
