### ISSUE TITLE
知网引用数存放字段，可以手动键入其它字段吗？

### ISSUE THREAD

**Issue by Celcnu** [l0o0/jasminum#109]
原因是我正在使用extra（其它）字段记录自定义的信息。但我手动键入其它字段，例如Archive，它似乎是无效的，引用数信息仍然会占用extra字段来存储。

**Comment by l0o0** [comment]
同学，这个Archive，应该是有问题。你试试用小写的archive

**Comment by l0o0** [comment]
![image](https://user-images.githubusercontent.com/2743744/197339111-2aa328a1-3ac5-442e-8743-c36ec5a16a72.png)
