### ISSUE TITLE
希望能实现在下载知网学位论文PDF后自动添加书签目录

### ISSUE THREAD

**Issue by zyx335588** [l0o0/jasminum#11]
使用connector抓取CNKI学位论文信息时，在可以下载PDF文件情况下，如果能够实现下载后自动添加书签目录就更好了。

**Comment by l0o0** [comment]
后期会考虑添加这个参数设置，让你们自己选择

**Comment by l0o0** [comment]
005版本忘了加了，我放006版本吧

**Comment by akeebird** [comment]
PDF添加书签的功能没法正常使用，确认安装好了pdftk_server。目前点击“提取PDF书签”后，会弹出命令行窗口，并提取目录到笔记中，但无法生成书签目录，还麻烦检查一下。是否与我更改了zotero文件夹默认位置有关呢？

**Comment by l0o0** [comment]
像你这种情况应该就是书签处理过的PDF复制过程出现问题，你可以提供下文件的路径和文件名。我参考下

**Comment by akeebird** [comment]
好的，其中一个文件路径是“D:\Zotero\storage\YTG9T9WN\郑雯心_2018_汉代孝子图研究.pdf”。好像确实是您说的问题，因为之前成功过，会在条目下出现两个PDF，然后再自动删除一个，目前则没有任何变化。 @l0o0

**Comment by l0o0** [comment]
我这边试了下，能正常处理这个书签。@akeebird 你试试打开
![图片](https://user-images.githubusercontent.com/2743744/92341698-121e9480-f0f1-11ea-90e8-c8c2e9b3da92.png)
然后运行抓取书签，然后把日志弄到文件里，贴上来看看哪里有问题

**Comment by qizidog** [comment]
请问使用 pdftk server 可以对普通的pdf文件（不一定是学位论文）提取章节目录么？一些其他的pdf文件总是要自己手动添加章节目录也是很耗时了，可否麻烦您讲解一下pdftk server提取目录的原理？

**Comment by l0o0** [comment]
@qizidog  我这边是从知网抓取对应的书签信息的，一般只有学位论文才有对应的书签信息。书签信息主要是有要对应的页面，书签名称以及书签的层级。可以参考下面这个文件，注意里面bookmark的部分（其他的是PDF的meta信息，你也可以把题录存到PDF中），bookmarktile这个是编码问题，出现乱码了。
[report.txt](https://github.com/l0o0/jasminum/files/5207392/report.txt)   

有了书签信息之后，就可以往PDF中添加书签了，这个你可以参考PDFtk的[命令说明](https://www.pdflabs.com/docs/pdftk-man-page/)中的`update_info_utf8`

**Comment by qizidog** [comment]
好的好的，明白了，我还以为是从pdf里面直接利用某种规则提取的。从知网抓取的话那就没办法了
