### ISSUE TITLE
使用pdftk拉取学位论文目录时出现问题

### ISSUE THREAD

**Issue by yisi-yu** [l0o0/jasminum#115]
我使用zotfile重新命名管理下载的附件文件夹名字，以出版社的形式来管理文件夹，不再是乱码命名文件夹，使用pdftk时按照要求安装并设置好路径，但拉取学位论文目录时只在条目栏出现目录信息，并且点击条目栏的目录可以跳转至pdf对应页面，但是打开pdf后在左侧目录栏并没有显示目录（zotero自带pdf阅读器和edge都没有），并报错如下所示，请问这是啥问题啊
<img width="2087" alt="截屏2022-08-04 下午7 37 48" src="https://user-images.githubusercontent.com/70384699/182838113-8025150a-7b3c-4866-8608-cff69f934d67.png">
![1191659613237_ pic](https://user-images.githubusercontent.com/70384699/182838542-796bf888-ffe0-444d-9a93-f0e6beb1c241.jpg)

**Comment by l0o0** [comment]
从你的截图上看，这是个链接文件，而且右边笔记中已经有相关的章节信息，应该是书签信息抓取成功，可是添加到PDF失败。我怀疑是因为链接文件的原因。我需要测试一下

**Comment by yisi-yu** [comment]
好的，十分感谢，我是使用的onedrive同步附件，所以pdf和条目之间有链接

**Comment by moicyu** [comment]
我也遇到一样的问题。
主页面论文列表中，单击相应论文，右边显示如上图，抓取成功。
打开pdf后在左侧目录栏并没有显示目录。
![WechatIMG635](https://user-images.githubusercontent.com/68453054/184479927-2dbfd304-c6e6-456c-a460-3dc299c1ab6e.png)



> 从你的截图上看，这是个链接文件，而且右边笔记中已经有相关的章节信息，应该是书签信息抓取成功，可是添加到PDF失败。我怀疑是因为链接文件的原因。我需要测试一下

**Comment by moicyu** [comment]
今天更新版本后一切正常了

**Comment by yisi-yu** [comment]
今日，最新更新，出现的上述问题是在macos下的，win下并未遇到上述问题

**Comment by abin1903** [comment]
您好我也出现了类似的问题。我的是win笔记本
![image](https://user-images.githubusercontent.com/59110783/190529000-45c1a4b1-06da-473e-a804-6683e0a00076.png)

**Comment by MODOUser** [comment]
我也一样，应该是知网下载的学位论文有文档保护，无法修改

**Comment by TIANTIANSTUDY** [comment]
> 您好我也出现了类似的问题。我的是win笔记本 ![image](https://user-images.githubusercontent.com/59110783/190529000-45c1a4b1-06da-473e-a804-6683e0a00076.png)

我也出现了相同的问题

**Comment by l0o0** [comment]
@TIANTIANSTUDY 你把这个PDF添加到github附件上，我去试试

**Comment by AurelianoJacket** [comment]
我也是遇到 @TIANTIANSTUDY 类似的问题，不过打开PDF后左侧有目录，只是每次导入都会报错有点不放心

**Comment by mrsunhuang** [comment]
我也遇到同样问题，是知网学位论文pdf加密码了，不能修改。
pdf解除密码、解除权限之后就正常了。
