### ISSUE TITLE
0.1.8版本 无法识别 中文文献 名字中有“_”

### ISSUE THREAD

**Issue by JackieLee-cn** [l0o0/jasminum#117]
![image](https://user-images.githubusercontent.com/52964775/187339426-88cbc95f-b39e-4460-9c16-9221256d530b.png)

**Comment by l0o0** [comment]
如果你的茉莉花设置中命名模板没有配置过，应该是默认的`{%t}_{%g}` 标题_作者的形式。不过我看你截图中的文件名，前面有一串数据，建议把文件名模板设置为`{%j}_{%t}` ，这里的 `%j` 用来识别其他信息（这部分信息不会用于查询元数据），后面的标题信息应该可以正常识别。
