### ISSUE TITLE
使用 更新知网引用数时出现问题，获取到的为空

### ISSUE THREAD

**Issue by youka-sar** [l0o0/jasminum#119]
以下方文献为例：
![image](https://user-images.githubusercontent.com/75243537/193785193-777be8c6-6d4b-441e-aa34-b641e7795709.png)
![image](https://user-images.githubusercontent.com/75243537/193785303-f2945042-750c-4608-b414-ffb26d79fd19.png)
文献链接：https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFDLAST2021&filename=TJDX202106001&uniplatform=NZKPT&v=QeM_BpSx6T1COnVc6dNqVOotc4SAKT76HCk6Ala_BnuYnXrMhWC9vVj3JEwfBxMQ

**Comment by l0o0** [comment]
我这里不能复现这个问题。同学你再试试重新抓取，看看有没有问题
