### ISSUE TITLE
插件不能获取知网论文的时间

### ISSUE THREAD

**Issue by noanless** [l0o0/jasminum#120]
其他都正常，但是论文发表的日期，卷次，期号，这些都抓不到；只要是中文文献就这样，无论是网页直接下载下来的，还是电脑pdf上传再抓取元数据的，如能解答不胜感谢，谢谢

**Comment by l0o0** [comment]
我看同学描述，应该是从网上抓取的网页快照类型。
![图片](https://user-images.githubusercontent.com/2743744/196126718-d6bed74c-b65e-4145-a888-aa8f08bc0da2.png)
你看你抓取的条目，前面的图标，是不是这种类型的。正常的期刊条目应该是类似下面那个白色文件的图标。

如果是上面的情况，你可以试试把下载的知网PDF/CAJ拉到zotero，然后用茉莉花插件识别
