### ISSUE TITLE
添加目录时显示“该条目下未找到PDF文件“

### ISSUE THREAD

**Issue by junhanch** [l0o0/jasminum#122]
zotero中使用jasmines插件对知网学位论文添加PDF目录时显示“该条目下未找到PDF文件“，请问该怎么办？
<img width="1440" alt="截屏2022-10-18 10 10 42" src="https://user-images.githubusercontent.com/116047948/196320095-4dfb8666-b555-4140-866c-0446e052b128.png">

**Comment by l0o0** [comment]
你确认下这个PDF能打开么？

**Comment by jiaojiaodubai** [comment]
应选中条目而非附件。
