### ISSUE TITLE
校外访问证书过期，怎么添加信任

### ISSUE THREAD

**Issue by carey036** [l0o0/jasminum#125]
![image](https://user-images.githubusercontent.com/45777074/198861297-5e3385f2-c593-48e1-ba2f-ae9e04926d42.png)
点那个添加例外点不动

**Comment by carey036** [comment]
在浏览器里自己抓取cookie放进去了

**Comment by l0o0** [comment]
> 

这个问题也困扰了我很久。可能这个小浏览器有限制，我在想用其他类似 chromedriver 这类的工具来获取。

**Comment by carey036** [comment]
> > 
> 
> 这个问题也困扰了我很久。可能这个小浏览器有限制，我在想用其他类似 chromedriver 这类的工具来获取。

或者可以增加自己填写cookie功能，或者配合浏览器插件等
