### ISSUE TITLE
不能给期刊论文添加目录吗

### ISSUE THREAD

**Issue by tughv** [l0o0/jasminum#126]
有些综述类的论文很长，需要通过目录来快速跳转到相应的位置

**Comment by l0o0** [comment]
主要是期刊类的文章，知网上没有相关章节页码信息。如果有的话，是可以添加的

**Comment by tughv** [comment]
不是PDFTK解析出来的吗，看到pdf的目录还可以跳转，自动打开zotero到对应的位置

**Comment by l0o0** [comment]
@tughv 不是pdftk 解析出来的，章节目录信息是从知网上抓取下来的。
