### ISSUE TITLE
明明没有勾选“抓取题录信息时拆分中文姓名”，但是每次从知网抓取信息时就抓取到的是拆分开的？

### ISSUE THREAD

**Issue by 17816712353** [l0o0/jasminum#127]
以前都好好的，换新电脑重装了就这样了。
<img width="485" alt="截屏2022-11-02 09 43 05" src="https://user-images.githubusercontent.com/68216639/199374906-7904eaad-334f-4ffc-b37e-86e1194007bf.png">
<img width="348" alt="截屏2022-11-02 09 43 41" src="https://user-images.githubusercontent.com/68216639/199374962-c755c8cb-be69-4363-bcf3-4718e468de75.png">

**Comment by 17816712353** [comment]
5天了还没有人回复

**Comment by FLIER001** [comment]
同样的问题，之前是正常的，难道是因为zotero或者插件更新了的原因？

**Comment by coisini-95** [comment]
你要在浏览器插件里也设置一下，就在这个插件的github页面有，你可以找一下

**Comment by 17816712353** [comment]
> 你要在浏览器插件里也设置一下，就在这个插件的github页面有，你可以找一下
我是老用户，之前是完全不用设置就可以正常通过茉莉花插件来控制是否自动拆分中文中文名的。但现在发现开关不起作用，且通过浏览器插件自己设置的到的合并中文姓名也与以往不同（原先是“小明”，现在是“小明，”）

**Comment by coisini-95** [comment]
> > 你要在浏览器插件里也设置一下，就在这个插件的github页面有，你可以找一下
> > 我是老用户，之前是完全不用设置就可以正常通过茉莉花插件来控制是否自动拆分中文中文名的。但现在发现开关不起作用，且通过浏览器插件自己设置的到的合并中文姓名也与以往不同（原先是“小明”，现在是“小明，”）

对我也发现了，插件设置的只是放到一个格子里了，并不是合并，还得手动，只能等作者解决了
