### ISSUE TITLE
自动合并姓名

### ISSUE THREAD

**Issue by kongdd** [l0o0/jasminum#129]
在添加中文文章的时候，能否设置自动合并姓名？

或者能否提供一个快捷键，来合并姓名？

感谢！

**Comment by coisini-95** [comment]
附议，希望能自动合并中文文献姓名

**Comment by RaymondKJ** [comment]
![image](https://user-images.githubusercontent.com/104543864/203247690-d807ad56-79b2-4f9a-bf5f-9d58402e6c10.png)
原来只要把摘取题录拆分中文姓名前面的勾去掉即可实现抓取时合并姓名，但不知道什么版本开始，这个选项失效了，即使不打勾，抓取的也是拆分姓名后的。有待作者解决

**Comment by l0o0** [comment]
> ![image](https://user-images.githubusercontent.com/104543864/203247690-d807ad56-79b2-4f9a-bf5f-9d58402e6c10.png) 原来只要把摘取题录拆分中文姓名前面的勾去掉即可实现抓取时合并姓名，但不知道什么版本开始，这个选项失效了，即使不打勾，抓取的也是拆分姓名后的。有待作者解决

提供一个示例，我这边测试一下

**Comment by kongdd** [comment]
这样可以吗？

https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFDLAST2016&filename=GSQX201603005&uniplatform=NZKPT&v=5Z2x56zdNIft43UDc3pF0jbohXQ5-W4WF9bu2cEMJsHU114ePcr1RrjngFwtA0kf

**Comment by RaymondKJ** [comment]
您好，
https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFDAUTO&filename=JJYJ202207003&uniplatform=NZKPT&v=qwR_wxIi_aiqu0a7D1SXI5uRIH54LY9exPXlp-Vat2eZq-cbi8qGBD9bq4QNouWB
茉莉花 版本0.2.1
translator 中国知网CNKI 2022-10-11 12:51:15

**Comment by Brave126** [comment]
这个功能感觉不是很稳定，已经取消勾选了，有时候还是会拆分，重启zotero和电脑又恢复正常不拆分了

**Comment by l0o0** [comment]
上面的同学，你们列一下安装的插件，看看有哪些插件是不是会有影响

**Comment by 17816712353** [comment]
> 上面的同学，你们列一下安装的插件，看看有哪些插件是不是会有影响
> 我没有出现你们说的那种情况

![uUHjdF](https://dandan-pic.oss-cn-hangzhou.aliyuncs.com/uPic/uUHjdF.png)

**Comment by l0o0** [comment]
@17816712353 禁用掉ZoteroIF那个插件，再试试

**Comment by coisini-95** [comment]
![图片](https://user-images.githubusercontent.com/78250635/203559602-91db6673-e331-4a18-88ad-3ca7d936fb72.png)
我的插件是这些

**Comment by 17816712353** [comment]
> @17816712353 禁用掉ZoteroIF那个插件，再试试

您好，禁用后依然不行

**Comment by coisini-95** [comment]
> @17816712353 禁用掉ZoteroIF那个插件，再试试

![图片](https://user-images.githubusercontent.com/78250635/203560192-11001685-8b0c-4dfe-8e48-513818c03d2a.png)
禁用if插件后还是这样，名字都写在第一个空格，这是我已经改了浏览器插件里的那个选项后变成这样的

**Comment by l0o0** [comment]
@coisini-95 你的茉莉花设置和浏览器选项是怎么设置的，截图我看看

**Comment by coisini-95** [comment]
> @coisini-95 你的茉莉花设置和浏览器选项是怎么设置的，截图我看看

![图片](https://user-images.githubusercontent.com/78250635/203560919-85d4b0ae-8126-4e18-ad00-0d754facef55.png)
![图片](https://user-images.githubusercontent.com/78250635/203561065-3dd24f28-9c33-402c-a0bf-afa65b19d415.png)
浏览器插件这个参数是按照您的说明加的

**Comment by l0o0** [comment]
@coisini-95 你这个截图是对的，条目里的姓名是合并在一起的。全名是放在姓那一栏里。  
只是因为名那一栏是空的，所以只是显示了(名)  这样的信息 
![图片](https://user-images.githubusercontent.com/2743744/203562829-41b79ac1-2152-4915-b8b5-da4539c1a34a.png)

**Comment by 17816712353** [comment]
> @coisini-95 你这个截图是对的，条目里的姓名是合并在一起的。全名是放在姓那一栏里。
> 只是因为名那一栏是空的，所以只是显示了(名) 这样的信息 。
> 如果你想显示不同的姓名展示，你可以试试点击旁边的小方框
> ![图片](https://user-images.githubusercontent.com/2743744/203562829-41b79ac1-2152-4915-b8b5-da4539c1a34a.png)
> ![图片](https://user-images.githubusercontent.com/2743744/203563258-503ebb56-e6db-4c51-ad3c-1eff19060355.png)

说明茉莉花插件里的对应设置确实没用啊，依旧需要自行修改翻译器😂。

**Comment by coisini-95** [comment]
> @coisini-95 你这个截图是对的，条目里的姓名是合并在一起的。全名是放在姓那一栏里。 只是因为名那一栏是空的，所以只是显示了(名) 这样的信息 。 如果你想显示不同的姓名展示，你可以试试点击旁边的小方框 ![图片](https://user-images.githubusercontent.com/2743744/203562829-41b79ac1-2152-4915-b8b5-da4539c1a34a.png) ![图片](https://user-images.githubusercontent.com/2743744/203563258-503ebb56-e6db-4c51-ad3c-1eff19060355.png)

就是小工具合并后的名字是一格显示，很整齐，改了浏览器插件参数后虽然合并了，但是确实两格显示，就看起来别扭。大家可能就是希望能在抓取文献后自动调用小工具合并，这样就比较好

**Comment by l0o0** [comment]
@coisini-95 你说的两格显示是指这里图1变成图2的形式
![图片](https://user-images.githubusercontent.com/2743744/203676284-aa1ab8d8-48a1-4472-8f0a-3f96d6976467.png)
![图片](https://user-images.githubusercontent.com/2743744/203676619-f5a88635-8de1-4c67-b5bc-97f18142938f.png)
像这种两格显示，是Zotero那边的展示形式。图2的格式，合并姓和名后，把结果只显示在一个方框里，没有出现多余的占位信息，也就是下面这个被省略了
![图片](https://user-images.githubusercontent.com/2743744/203676756-3392929c-93eb-4d22-8877-14e2649de884.png)

**Comment by coisini-95** [comment]
> @coisini-95 你说的两格显示是指这里图1变成图2的形式 ![图片](https://user-images.githubusercontent.com/2743744/203676284-aa1ab8d8-48a1-4472-8f0a-3f96d6976467.png) ![图片](https://user-images.githubusercontent.com/2743744/203676619-f5a88635-8de1-4c67-b5bc-97f18142938f.png) 像这种两格显示，是Zotero那边的展示形式。图2的格式，合并姓和名后，把结果只显示在一个方框里，没有出现多余的占位信息，也就是下面这个被省略了 ![图片](https://user-images.githubusercontent.com/2743744/203676756-3392929c-93eb-4d22-8877-14e2649de884.png)

嗯嗯是的，用茉莉花的小工具能把名字合并到一个方框内，所以茉莉花能自动合并嘛，或者给个快捷键，就不用每次右键-小工具-合并姓名

**Comment by l0o0** [comment]
@coisini-95 快捷键后面会有的，这里可以优化一下，合并姓名的时候，把显示形式，也修改一下，改成更简洁的形式，去除不必要的(名)

**Comment by coisini-95** [comment]
> @coisini-95 快捷键后面会有的，这里可以优化一下，合并姓名的时候，把显示形式，也修改一下，改成更简洁的形式，去除不必要的(名)

嗯嗯，感谢大佬

**Comment by 17816712353** [comment]
> 
作者大大，我又试了一下，确实是插件的：
![57XaUc](https://dandan-pic.oss-cn-hangzhou.aliyuncs.com/uPic/57XaUc.png)
是不起作用的，当我没有增加Zotero connector里的translators.zhnamesplit时，无论勾选与否抓取后都是拆分状态；
当我增加了Zotero connector里的translators.zhnamesplit时，无论勾选与否都是下方图片状态：
![pTpxBi](https://dandan-pic.oss-cn-hangzhou.aliyuncs.com/uPic/pTpxBi.png)

**Comment by l0o0** [comment]
@17816712353 你把这个条目的信息截图，贴上来

**Comment by thetaaaaa** [comment]
作者大大你好，我也遇到了取消勾选拆分作者姓名选项后，中文作者姓名仍然被拆分的情况。

**Comment by l0o0** [comment]
> 

![图片](https://user-images.githubusercontent.com/2743744/204424519-a3dc6fc7-51d0-4ab6-87e6-4738a2df2652.png)
同学，你看看你那个条目，红框处是什么信息

**Comment by thetaaaaa** [comment]
![image](https://user-images.githubusercontent.com/66288540/204435181-307b9f33-5b1d-460c-8139-6c6ca9cd70f1.png)
你好，我这边显示的是上图这样。

**Comment by coisini-95** [comment]
> @coisini-95 @17816712353 @kongdd @Brave126 各位同学，我找到原因了，已更新版本，看看有没有问题

![图片](https://user-images.githubusercontent.com/78250635/204957116-e5a93251-69ef-4be8-b822-0c04680f7ead.png)
ok修复了，感谢大佬
