### ISSUE TITLE
启用茉莉花后首选项界面显示问题

### ISSUE THREAD

**Issue by Brave126** [l0o0/jasminum#130]
我使用的是0.2版本的，我只启用了这一个插件试了几次还是没有解决，启用插件之后会导致首选项界面大小超出屏幕范围，有一部分显示不出来，点不到最上边所以也不能通过拖动窗口来调整，我只启用了这一个插件时也是这种情况，使用0.18版本正常。
![image](https://user-images.githubusercontent.com/49699838/202423171-8d489117-6915-4575-bb72-3f725ee66565.png)

**Comment by l0o0** [comment]
这应该是窗口太大了，后面我调整一下设置页面布局
