### ISSUE TITLE
navi.cnki.net/knavi/journals保存pdf不了的疑问

### ISSUE THREAD

**Issue by asong2022** [l0o0/jasminum#131]
https://navi.cnki.net/knavi/journals/XXSS/detail
请问下在知网期刊里面的文章不能通过Zotero保存为pdf的修复方法有吗，
如https://navi.cnki.net/knavi/journals/XXSS/detail下，点击插件只能剪藏。

**Comment by jiaojiaodubai** [comment]
浏览器抓取问题请到[Translators_CN](https://github.com/l0o0/translators_CN)反馈。

目前知网转换器已经支持在期刊导航页面抓取条目了。
