### ISSUE TITLE
硕博士学位论文抓取能否填充学校地点信息？

### ISSUE THREAD

**Issue by s23ir45** [l0o0/jasminum#132]
您好，请问硕博士学位论文抓取能否填充学校地点信息？
比如，知网抓取信息按照GB/T 7714-2015 样式导出为
查元源. 饱和—非饱和水流运动高效数值算法研究及应用[D]. 武汉大学, 2014.
在高校名之前缺少城市名“武汉: ”
原因是抓取不到地点，我的想法是能不能抓取完之后直接和学校信息匹配填充文件信息栏？
这里有高校地点文档信息[http://www.moe.gov.cn/jyb_xxgk/s5743/s5744/A03/202110/t20211025_574874.html]

**Comment by jiaojiaodubai** [comment]
已经由[ Zotero Linter 插件](https://zotero-chinese.com/plugins/#search=Translate%20for%20Zotero)实现
