### ISSUE TITLE
batch set language

### ISSUE THREAD

**Issue by sammo3182** [l0o0/jasminum#133]
请问如何正确使用Batch set language功能？我尝试将Tools-Batch set language(separated by ',') 设置为"zh-CN, en", "zh, zh-CN", 或单独“zh-CN”均无法将现在标为zh的条目转换为zh-CN。这导致citation key出现批量错误，非常麻烦。还请指教！感谢！

**Comment by Maasea** [comment]
Batch set language 的结果目前只支持 [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) 形式，也就是 zh。

需要注意的是 zh 也是正确的语言格式，测试时并不会导致引用错误。

**Comment by sammo3182** [comment]
@Maasea 谢谢您的回答。当yuyan1设置为“zh” 时原有的首字母大写citation key 全部变为小写，比如 `ZhangWei2020` 就会变成 `zhangwei2020` 这会造成索引该key的所有md、latex等相关文档读写错误，找不到对应索引。现在我发现有两种解决办法：

1. 回滚回旧版本jasminum
2. 将语言手动设置为 zh-CN

我相信新版本设置会对很多使用中文索引的朋友造成困扰，希望有更好的解决方案。

**Comment by Maasea** [comment]
抱歉对您造成了困扰，我已经复现您说的 citation key 变小写，但是 zh 到 zh-CN 的映射我目前没有什么好主意，因为zh 可能是 zh-CN 也可能是 zh-TW，en 可能映射成 en-US 也可能是 en-CA，他们是不同标准的表示。

**Comment by sammo3182** [comment]
@Maasea 谢谢您为此做出的努力！另一方面，我理解设置语言也是为了更好地让插件进行识别和parsing，如果因此反而造成了问题，是否可以考虑恢复旧版本自动设置语言的选项？ 我看到了诸位在 #128 中的讨论，但鉴于现在的情况，似乎有这个功能会更好地使citation key保持一致。当然只是个建议，供参考。我会让我的学生统一回滚到旧版本，并在其他介绍场合对这一问题向更多受众介绍。

无论如何，再次感谢贵团队的创建和维护如此重要的插件！！

**Comment by l0o0** [comment]
@Maasea 你好，看到以上的讨论，我的理解是因为设置语言功能经过更新，导致已有的条目语言字段发生变化，导致citeKey前后不一致。

在此我有几个疑问，
1. 正常来说，新版本安装后，不会对已入库条目的语言字段进行更新，老师这边是安装新版插件后，手动进行的处理么？
2. 如果出现上面的问题，是不是只要把对应的字段还原为 zh-CN ，就可以解决问题？

**Comment by l0o0** [comment]
@sammo3182 之前发生过有些同学设置语言时，字段填写有误，遇到和你一样的问题，就是在协作时前后不一样的情况。https://github.com/l0o0/jasminum/issues/112
后来 @Maasea 同学协助处理了这一问题，使用NLP识别，https://github.com/l0o0/jasminum/pull/114 并按ISO规范了，这样语言字段就按规范进行更新，没有手动设置语言信息的选项了。

老师的需求，目前可以用自定义脚本来实现，而且相关的插件我们也在准备，到时候老师可以关注一下我们的新作品

**Comment by Eunsolfs** [comment]
> 请问如何正确使用批量设置语言功能？我试试将Tools-批量设置语言(','分隔)设置为"zh-CN, en", "zh, zh-CN", 或单独“zh-CN”均无法将现在标为zh的条目转为zh-CN。此引导引引键出现错误，非常麻痹。还请指导！谢谢！

I got the same problem too! I have to modify all of my letters, that fells bad

**Comment by Eunsolfs** [comment]
发现了一个新的zotero插件  可以完美解决以上问题 [https://github.com/redleafnew/delitemwithatt](https://github.com/redleafnew/delitemwithatt)

**Comment by Eunsolfs** [comment]
> 请问如何正确使用Batch set language功能？我尝试将Tools-Batch set language(separated by ',') 设置为"zh-CN, en", "zh, zh-CN", 或单独“zh-CN”均无法将现在标为zh的条目转换为zh-CN。这导致citation key出现批量错误，非常麻烦。还请指教！感谢！

朋友，你去看看这个  [https://github.com/redleafnew/delitemwithatt](https://github.com/redleafnew/delitemwithatt)

**Comment by l0o0** [comment]
@sammo3182  @Eunsolfs 功能已做调整。
语言设置分为**自动检测**和**手动修改** 两个菜单选项，可分别设置。
同时新条目加入时，可以选择使用自动检测**Auto**还是手动修改**Manual** 这2个选项
![图片](https://user-images.githubusercontent.com/2743744/208148473-54a510bc-90e4-4613-84f5-17947eb49d4a.png)

**Comment by Eunsolfs** [comment]
非常感谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年12月17日 00:51 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [l0o0/jasminum] batch set language (Issue #133) |

@***@***.*** 功能已做调整。
语言设置分为自动检测和手动修改 两个菜单选项，可分别设置。
同时新条目加入时，可以选择使用自动检测Auto还是手动修改Manual 这2个选项
