### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by Eunsolfs** [l0o0/jasminum#137]
小工具 【批量设置语言】，设置自定义的语言字段后，如 zh-CN,en-US
插件疑似无法正确读取用户设置的语言参数并对各个文献条目中的language字段做出相应的修改

目前文献条目中的language的字段值分别是en和zh，我需要将它们批量设置为zh-CN,en-US
这是刚需！我需要使用[这个CSL样式](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl)来生成对应的引文样式。在这个仓库中明确指出需要文献的language字段的值为zh-CN或en-US，所以需要插件做出升级，以此来修复上述存在的：不能按照用户设置的语言参数进行批量设置的bug

为什么说是bug？因为用户设置的参数无效，无效的设置就是bug的体现。
还望各位大佬修复一下

修改思路就是设置字符串，对各位来说这很容易。尽管可能因此引入其他的问题，但是设置成zh-CN,en-US对部分用户来说是必须的

由于插件的批量设置语言的小功能会自动修改所选的条目的语言字段为zh/en，所以导致用户不得不再手动把设置成zh/en的字段改回zh-CN,en-US；这无疑使本来很简单的事情变得更麻烦了

综上，还请重视一下这个问题

**Comment by l0o0** [comment]
之前使用的NLP工具，会自动的转换语言信息，如果想要强制使用自定义信息进行填充，应该可以使用一个匹配关系表来进行

**Comment by Eunsolfs** [comment]
感谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年12月15日 12:17 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [l0o0/jasminum] bug report (Issue #137) |

之前使用的NLP工具，会自动的转换语言信息，如果想要强制使用自定义信息进行填充，应该可以使用一个匹配关系表来进行

**Comment by Eunsolfs** [comment]
发现了一个新的zotero插件  可以完美解决以上问题 [https://github.com/redleafnew/delitemwithatt](https://github.com/redleafnew/delitemwithatt)

**Comment by zepinglee** [comment]
其实 `en` 和 `en-US`、`zh` 和 `zh-CN` 区别不大，因为 <https://github.com/citation-style-language/locales/blob/master/locales.json> 后者是前者的 primary-dialect。

之所以写成 `en-US` 和 `zh-CN`，是因为很多人看到 `en` 和 `zh` 搞不懂是什么东西就忽略了。
