### ISSUE TITLE
使用网页版VPN时，zotero connector无法抓取数据了

### ISSUE THREAD

**Issue by will-gt** [l0o0/jasminum#138]
两个月前，使用大学网页版VPN的时候，zotero connector可以正常抓取知网的文献，但是最近不行了 ，是jasminum插件的问题吗？

提示的错误如下：An error occurred while saving this item. See Troubleshooting Translator Issues for more information.

**Comment by will-gt** [comment]
@l0o0 您好，我们学校是网页版VPN，我用账号登陆后的网址是：https://vpnx.lzu.edu.cn/

**Comment by will-gt** [comment]
您好，我们学校是网页版VPN，我用账号登陆后的网址是：https://vpnx.lzu.edu.cn/

**Comment by will-gt** [comment]
@l0o0 您好，我们学校是网页版VPN，我用账号登陆后的网址是：https://vpnx.lzu.edu.cn/

两个月之前能抓取的，还能直接下载PDF，不知道为啥最近不行了。感谢！

**Comment by l0o0** [comment]
@will-gt 可以把登录VPN之后，知网文章的链接发出来么？随便一篇知网文献

**Comment by will-gt** [comment]
@l0o0 https://vpnx.lzu.edu.cn/https/77726476706e69737468656265737421fbf952d2243e635930068cb8/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFDAUTO&filename=ZGGW202209014&uniplatform=NZKPT&v=E3lO5cGSCyaPIu1IyT9dXejpxSOEz4a4OfoukmWE9JEVFkQSCyezO5NicUvfvWi4

**Comment by will-gt** [comment]
@l0o0 您好，登陆VPN后随便一篇文献是这样的。谢谢啊。https://vpnx.lzu.edu.cn/https/77726476706e69737468656265737421fbf952d2243e635930068cb8/kcms/detail/detail.aspx?dbcode=CJFD&dbname=CJFDAUTO&filename=ZGGW202209014&uniplatform=NZKPT&v=E3lO5cGSCyaPIu1IyT9dXejpxSOEz4a4OfoukmWE9JEVFkQSCyezO5NicUvfvWi4

**Comment by l0o0** [comment]
@will-gt 这个网址目前是能正常匹配的，测试地址 https://tool.oschina.net/regex，正则表达式匹配规则是 https?://.*?/(kns8?/defaultresult/index|kns8?/AdvSearch|kcms/detail|KXReader/Detail\?|KNavi/|Kreader/CatalogViewPage\.aspx\?)。

你试试重新更新下翻译器试试，一般zotero也会自动更新翻译器，导致你的翻译器变成官方的，自动更新的设置应该是在这里，现在是统一叫转换器了，原来是叫翻译器的
![图片](https://user-images.githubusercontent.com/2743744/208807481-0e2cd254-a38e-4d6e-9cb2-1093f23b973f.png)

**Comment by will-gt** [comment]
@l0o0 您好，我试了下还是不行，我把zotero connector-advanced-translators更新了几下突然可以了，不懂为啥。

另外茉莉花插件更新的CNKI.js显示日期是2022年10月11日，github上下载的zip中的CNKI.js是2022年12月16日，所以茉莉花好像不能根据github最新日期来更新。

大佬还有个问题。。zotero connector可以抓取学位论文的信息，但是无法下载PDF了。zotero的URL是填充链接的，同时双击zotero中的学位论文条目会自动跳到网页去。这是不是翻译器的问题呢？非学位论文的抓取条目、下载PDF一切正常。

**Comment by l0o0** [comment]
@will-gt 你点的那按钮应该就是刷新翻译器信息
![图片](https://user-images.githubusercontent.com/2743744/208833850-bbe5ae05-ca43-40d0-bef9-707101bf9d0d.png)

翻译器的时间是根据翻译器文件中的这一行更新时间，这一行目前是2022年10月11日，你看到的2022年12月16日是指哪里的时间
https://github.com/l0o0/translators_CN/blob/3e721d79a40d17040ffed1fd5b6503b5a4750564/translators/CNKI.js#L12

学位论文在抓取到Zotero时，是不是下载PDF时，出现了红叉❌？Zotero中的URL是填充的，是指的什么？如果条目中没有PDF附件，但有URL时，双击时会自动打开浏览器访问URL的。

**Comment by will-gt** [comment]
@l0o0 
您好，我看到的2022年12月16日的时间是下载zip后解压，translators_CN-master\translators_CN-master\translators里面CNKI.js的文件修改时间（如图），是我门外汉了，以后知道怎么看了谢谢呀。
<img width="312" alt="图1" src="https://user-images.githubusercontent.com/72987274/208867985-9b68c432-ec50-439c-94f0-e6c06b25a9ea.png">


学位论文在抓取到Zotero时，下载PDF时出现了“❌Full Text PDF”。Zotero中的URL是填充的就是URL条目是有链接在的。

我之前是能下载下来学位论文PDF的，今天试了不行。
我好像找到原因了，我点击之前下载的学位论文的URL，进入的是海外简体版（链接如下）；现在点击zotero connector后，学位论文URL定位的是国内版的CNKI，所以下载不下来。两个链接进入后分别如下图，有**PDF整本下载**的是海外简体版。现在不能下了不知道是不是CNKI搞的。
另外简体海外版的PDF自己带目录，所以我的pdftk会出现如下错误。

海外简体版
https://vpnx.lzu.edu.cn/https/77726476706e69737468656265737421f3ff4fd228266d426d0d88e29b5b283c13d3673f/KCMS/detail/detail.aspx?dbcode=CDFD&dbname=CDFDTEMP&filename=1022757297.nh&uniplatform=OVERSEA&v=05zPkD0_BboOo-ST1S5xuIylxReO9aNdIiO-8aws6GcR5RrL7r5A41Ja_5Fv7mE8

国内版
https://vpnx.lzu.edu.cn/https/77726476706e69737468656265737421fbf952d2243e635930068cb8/kcms/detail/detail.aspx?dbcode=CDFD&dbname=CDFDTEMP&filename=1022757297.nh&uniplatform=NZKPT&v=05zPkD0_BboOo-ST1S5xuIylxReO9aNdIiO-8aws6GcR5RrL7r5A43K7iN7X5EXI


<img width="646" alt="海外" src="https://user-images.githubusercontent.com/72987274/208872580-4fee544e-4204-471c-9b30-52614cd6b6a5.png">
<img width="641" alt="国内" src="https://user-images.githubusercontent.com/72987274/208872574-eaef0b55-90a8-4dc9-8504-2ea82d91352d.png">
<img width="159" alt="书签失败" src="https://user-images.githubusercontent.com/72987274/208872566-511b90f4-5970-4f3f-9007-fa8d068a0f9b.png">

**Comment by l0o0** [comment]
@will-gt 
1. 你看到的那个是文件的修改时间，从github上下载应该是最近提交的时间，我们只关注其中的lastUpdated 的时间
2. 前面你说的填充是指条目的URL信息正常抓取了，我现在理解了
3. 你现在的情况是，之前能正常从海外知网下载PDF，现在海外知网也不可以了？

如果已经有书签了，那添加书签的功能也可以关掉了

**Comment by will-gt** [comment]
@l0o0 不好意思去年羊了之后忘回了。挂上VPN后，知网海外版可以通过zotero connector下载到PDF，同时因为海外版PDF已经有目录，所以显示“目录添加失败”；目前知网国内版挂上VPN后显示“❌Full Text PD”，请问国内版的这个问题有办法解决么？谢谢！

**Comment by l0o0** [comment]
@will-gt 现在用国内版知网PDF下载不保证成功，海外版成功率比较高。等以后看看有没有办法提升一下

**Comment by will-gt** [comment]
好的好的，海外版目前能用不影响。以后提升的时候，有个思路是如果是学位论文，则翻译器自动从国内版转为海外版？不太懂随便假设一下。
目前已经很好用了，感谢啊！
