### ISSUE TITLE
增加国人双字名英文区分

### ISSUE THREAD

**Issue by pencilheart** [l0o0/jasminum#140]
能否增加分离英文期刊条目的国人双字名功能。例如：“Wang Xiaoming”转换为“Wang Xiao Ming”。目前只能手动添加空格并改将后一个字改为大写。是否有可能通过js实现批量修改？

**Comment by zepinglee** [comment]
理论上可以，但是会有些问题：

1. 部分拼音组合有歧义，比如 an gang 和 ang ang；
2. 有些外籍华人名字符合拼音的模式，但是不一定适合拆成双字。比如 “Li Feifei”（假想的示例）。
3. 有些西方姓名会被错误地当成拼音，比如“Fubini”，“Fatou”。

**Comment by zepinglee** [comment]
虽然可能存在问题，但我还是建议添加这个功能。因为毕竟国标是这么要求的。

<img width="718" alt="Screenshot 2023-02-04 at 19 43 23" src="https://user-images.githubusercontent.com/12290822/216765465-9ea1e021-1f35-455b-aa0c-5d2f17749e80.png">

**Comment by pencilheart** [comment]
感谢感谢！辛苦大佬们了👍
