### ISSUE TITLE
功能改进建议

### ISSUE THREAD

**Issue by Eunsolfs** [l0o0/jasminum#141]
大佬你好, 经过使用, 我发现可改进升级的地方：修改中文作者名的功能(拆分合并姓名), 需要一些改进

该功能会自动的修改citation key, 这对于使用betterbibLatex导出元数据给Latex使用的用户有很大影响, 因为citation key发生了变化, 这是致命的, 这会导致编写的latex源文件在库中找不到对应的文献元信息

建议：
在插件设置中, 添加一个checkBox, 用户来决定是否同步修改citationKey, 当然了, 私以为默认不修改是理想情况

**Comment by northword** [comment]
citationKey 应是 bib 插件负责的，与茉莉花应当无关。你可以修改 bib 插件中 citationKey 的生成规则使其不受姓名影响。

**Comment by Eunsolfs** [comment]
好的谢谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年01月30日 14:52 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [l0o0/jasminum] 功能改进建议 (Issue #141) |

citationKey 应是 bib 插件负责的，与茉莉花应当无关。你可以修改 bib 插件中 citationKey 的生成规则使其不受姓名影响。

**Comment by zepinglee** [comment]
使用 better bibtex 插件控制。
