### ISSUE TITLE
连接VPN后，无法正常抓取知网pdf版的学位论文

### ISSUE THREAD

**Issue by thetaaaaa** [l0o0/jasminum#142]
问题描述：大佬你好，我使用easyconnect客户端链接vpn后，可以正常抓取期刊论文的pdf，但是无法抓取学位论文pdf。想问一下这是茉莉花插件的问题吗，以及如何在连vpn的情况下成功抓学位论文pdf。
补充描述：在校园网中，是可以正常抓取期刊论文的pdf和学位论文pdf。
相关信息：
（1）我连接VPN的网址是：https://vpn2.njau.edu.cn/ 
（2）连接vpn后的某篇知网学位论文的url是：https://kns-cnki-net-s.vpn2.njau.edu.cn:8118/kcms/detail/detail.aspx?dbcode=CMFD&dbname=CMFD201702&filename=1017205180.nh&uniplatform=NZKPT&v=V46jAdN1XpLUUpnBV5ZLPcihifAxIhmdfmEvvgumJ60MoeL8jcB1nsZBX_eIb2Og
（3）抓取失败时的提示是：
![image](https://user-images.githubusercontent.com/66288540/212547318-7c429736-44bd-499f-bf17-a4695e6b8c19.png)

**Comment by carey036** [comment]
这是因为软件里面的网址是cnki.net的网址，不是学校vpn的网址。

请问作者能否通过设置 自定义域名 和 手动填写登录cookie来解决这个问题（部分学校没有fsso，只有webvpn和easyconnect的情况下），当然最好的方案还是使用fsso.cnki.net来抓取pdf（支持手动填写cookie的话可以解决fsso.cnki.net部分学校证书过期的问题）  @l0o0 

目前发现可以通过zotero的高级编辑器（编辑-首选项-高级-编辑器）来修改jasminum的cookie，
![image](https://user-images.githubusercontent.com/45777074/216825759-5ea7a58d-209a-41c9-8c45-efb91c68318e.png)

**Comment by thetaaaaa** [comment]
在连接VPN后，我将学位论文页面的“整本下载”对应请求的cookie填入到上述设置项中，zotero仍然不能正常抓取全文pdf。我的具体设置方式如下图，不知这样设置是否正确。
![image](https://user-images.githubusercontent.com/66288540/216953391-4004c103-cb86-448b-aacb-218d7ce147ea.png)

**Comment by thetaaaaa** [comment]
在连接VPN后，我将学位论文页面的“整本下载”对应请求的cookie填入到上述设置项中，zotero仍然不能正常抓取全文pdf。我的具体设置方式如下图，不知这样设置是否正确。
![image](https://user-images.githubusercontent.com/66288540/216954446-e82e0341-e527-4b4e-8a11-5537df3c2130.png)

**Comment by carey036** [comment]
> 在连接VPN后，我将学位论文页面的“整本下载”对应请求的cookie填入到上述设置项中，zotero仍然不能正常抓取全文pdf。我的具体设置方式如下图，不知这样设置是否正确。 ![image](https://user-images.githubusercontent.com/66288540/216954446-e82e0341-e527-4b4e-8a11-5537df3c2130.png)

这样不行的，你需要的是登录fsso.cnki.net后，https://cnki.net/ 这个站点的LID 这个cookie( 另外需要注意的是，不是所有的学校都能登录fsso.cnki.net，可能需要借同学的账号)

你这样的抓的是你们学校webvpn使用知网的cookie，不能用来知网官方接口的访问

**Comment by mayii2001** [comment]
弹出登录界面时，复制url到首选项-jasminum-更新用户数据，就可以正常下载了

**Comment by thetaaaaa** [comment]
> 
按照您的步骤，得到如下结果，似乎不是理想的结果。原先通过fsso.cnki.net登录知网，zotero已经可以自动抓取caj版的学位论文。
![image](https://user-images.githubusercontent.com/66288540/218249766-e0211696-1edf-4faf-9309-3708cb6d3d46.png)

**Comment by mayii2001** [comment]
> > 
> 
> 按照您的步骤，得到如下结果，似乎不是理想的结果。原先通过fsso.cnki.net登录知网，zotero已经可以自动抓取caj版的学位论文。 ![image](https://user-images.githubusercontent.com/66288540/218249766-e0211696-1edf-4faf-9309-3708cb6d3d46.png)

对于无法用fsso.cnki.net的学校只能开vpn的可用。
![图片](https://user-images.githubusercontent.com/88707940/218353343-b4b5debe-2d01-4fe9-8b65-bee83b78c5f5.png)
需点击ip登录后再抓取用户信息

**Comment by thetaaaaa** [comment]
> 
我理解了。若想自动获取cookie，则应改在茉莉花的窗体中完成通过https://fsso.cnki.net/登录的全流程，即从访问https://fsso.cnki.net/开始，如下图：
![image](https://user-images.githubusercontent.com/66288540/219851060-55c60c6c-a346-4746-b609-4e3e5ec3235b.png)

**Comment by l0o0** [comment]
或者打开zotero 高级设置，找到jasminum cookie的设置，更新cookie

**Comment by jiaojiaodubai** [comment]
浏览器抓取问题请到[Translators_CN](https://github.com/l0o0/translators_CN)反馈。
