### ISSUE TITLE
无法抓取原文件 metadata for PDF

### ISSUE THREAD

**Issue by waternet001** [l0o0/jasminum#143]
【求助】我自己添加一个已经下载了的PDF到zotero中，在校园网下，无法抓取原文件 metadata for PDF。该现象出现一段时间了。 我刚才下载了最新版插件0.2.4. 再试，再失败。
反过来操作可以，从CNKI里查到文献，添加入zotero，他会自动下载PDF。
请分析指教。感谢。
(求助日期，2023-1-26）

**Comment by waternet001** [comment]
今天又测试，发现出现了相反的情况。 自己下载好的CNKI文献拉入Zotero后，可以 retrive metadata, 但是，从CNKI上搜索到的文献就无法从浏览器直接加入Zotero。 昨天的情况和今天恰好相反。（今天日期：2023-1-27）。请大家帮助。感谢。

**Comment by jiaojiaodubai** [comment]
请提供更多信息以便定位问题。
