### ISSUE TITLE
无法正常抓取Taylor & Francis 书籍信息

### ISSUE THREAD

**Issue by Jenny0888999** [l0o0/jasminum#144]
书籍和里面的篇章信息无法正常抓取，或信息是错误的：
示例如下：

网站：https://www.taylorfrancis.com/chapters/edit/10.4324/9781315697048-1/historical-contemporary-future-perspectives-self-regulated-learning-performance-dale-schunk-jeffrey-greene
![image](https://user-images.githubusercontent.com/123791237/215241198-f38c23f0-08bc-415b-8a45-22b38a5a0244.png)
明明是篇章，却成了书类型，且没有抓取到作者信息：
![image](https://user-images.githubusercontent.com/123791237/215241259-0c23eac8-1e4e-4c2d-bd90-a2341de96419.png)
希望能解决下，谢谢！

**Comment by jiaojiaodubai** [comment]
外文网站的抓取问题请到 zotero/translators 仓库反馈
