### ISSUE TITLE
抓取中文外籍作者国别时，能否用全角方括号取代目前自动的半角方括号？

### ISSUE THREAD

**Issue by ecssd** [l0o0/jasminum#145]

**Comment by zepinglee** [comment]
这个没有统一的标准，有的样式还要求六角括号，建议手动修改或者写脚本批量修改。

**Comment by ecssd** [comment]
好滴好滴！谢谢啦

**Comment by jiaojiaodubai** [comment]
已由 Zotero Linter 支持，详见 [0163fd](https://github.com/northword/zotero-format-metadata/commit/0163fda55854f3a25d0cb2f3af2e57912d6f24fb)。
