### ISSUE TITLE
Feature request: 批量转换标题为 sentence case

### ISSUE THREAD

**Issue by zepinglee** [l0o0/jasminum#146]
最近在为《心理学报》编写 csl 样式，其中要求标题为 sentence case。目前 zotero 能在标题处右键选择转为 sentence case，但是仅限单篇文献。如果能将选中的多篇文献通过右键菜单批量转换就比较方便了。

类似的功能在 better bibtex 插件中已经实现（BBT sentence），但是该插件会额外增加启动时间，对非 bibtex 用户不太友好，希望能在茉莉花插件中添加该功能。

**Comment by jiaojiaodubai** [comment]
此功能已经由[ Zotero Linter 插件](https://zotero-chinese.com/plugins/#search=Linter%20for%20Zotero)实现。
