### ISSUE TITLE
希望能够支持webvpn下载附件

### ISSUE THREAD

**Issue by skymagician** [l0o0/jasminum#148]
举个例子，浙大的webvpn在知网中的链接 http://kns-cnki-net-s.webvpn.zju.edu.cn:8001/kcms2/article/abstract?v=3uoqIhG8C447WN1SO36whLpCgh0R0Z-iDdIt-WSAdV5IJ_Uy2HKRAckBXlQAVy-H55zfzl0clzrrxPDcGUrvMbBczSbvnJqt&uniplatform=NZKPT

**Comment by Prehistoric-Bubbles** [comment]
好兄弟这个问题解决了，我参考了https://github.com/l0o0/jasminum/issues/142#issuecomment-1418918593的回答
学校提供的wevpn接口登陆后为*/www-cnki-net-443.webvpn*/而通过fsso.cnki.net搜索学校登录后（只要能搜到应该问题不大）为https://www.cnki.net/
![image](https://user-images.githubusercontent.com/74956923/218541243-96e36a23-0350-429b-9b37-039ec546cf68.png)
而回答的意思大概是我们需要通过fsso.cnki.net网站登录获得本校在https://www.cnki.net/官方接口cookies（我理解的公网）而不是本校的webvpn所提供的端口cookies（内网端口）
由于我不是相关专业不会找cookies，所以直接用了首选项-茉莉花-获取知网用户数据的法子，直接在茉莉花（zotero）内置浏览器中打开fsso.cnki.net认证本校身份，然后进入了【公网端口】成功扒下附件还是pdf格式的
![image](https://user-images.githubusercontent.com/74956923/218542976-79c48620-4b0e-452a-bf15-32f448ede15d.png)
![image](https://user-images.githubusercontent.com/74956923/218543095-76798cf2-48ba-43cf-b354-4bcfb567410f.png)

**Comment by skymagician** [comment]
> 好兄弟这个问题解决了，我参考了[https://github.com/l0o0/jasminum/issues/142#issuecomment-1418918593的回答](https://github.com/l0o0/jasminum/issues/142#issuecomment-1418918593%E7%9A%84%E5%9B%9E%E7%AD%94) 学校提供的wevpn接口登陆后为*/www-cnki-net-443.webvpn*/而通过fsso.cnki.net搜索学校登录后（只要能搜到应该问题不大）为https://www.cnki.net/ ![image](https://user-images.githubusercontent.com/74956923/218541243-96e36a23-0350-429b-9b37-039ec546cf68.png) 而回答的意思大概是我们需要通过fsso.cnki.net网站登录获得本校在[https://www.cnki.net/官方接口cookies（我理解的公网）而不是本校的webvpn所提供的端口cookies（内网端口）](https://www.cnki.net/%E5%AE%98%E6%96%B9%E6%8E%A5%E5%8F%A3cookies%EF%BC%88%E6%88%91%E7%90%86%E8%A7%A3%E7%9A%84%E5%85%AC%E7%BD%91%EF%BC%89%E8%80%8C%E4%B8%8D%E6%98%AF%E6%9C%AC%E6%A0%A1%E7%9A%84webvpn%E6%89%80%E6%8F%90%E4%BE%9B%E7%9A%84%E7%AB%AF%E5%8F%A3cookies%EF%BC%88%E5%86%85%E7%BD%91%E7%AB%AF%E5%8F%A3%EF%BC%89) 由于我不是相关专业不会找cookies，所以直接用了首选项-茉莉花-获取知网用户数据的法子，直接在茉莉花（zotero）内置浏览器中打开fsso.cnki.net认证本校身份，然后进入了【公网端口】成功扒下附件还是pdf格式的 ![image](https://user-images.githubusercontent.com/74956923/218542976-79c48620-4b0e-452a-bf15-32f448ede15d.png) ![image](https://user-images.githubusercontent.com/74956923/218543095-76798cf2-48ba-43cf-b354-4bcfb567410f.png)

按这种方法我还是下不到pdf，只能下载到一个名为 full text caj 的快照。

**Comment by Prehistoric-Bubbles** [comment]
> 

浏览器扩展的保存结果截图看一下

**Comment by Prehistoric-Bubbles** [comment]
> > 好兄弟这个问题解决了，我参考了[https://github.com/l0o0/jasminum/issues/142#issuecomment-1418918593的回答](https://github.com/l0o0/jasminum/issues/142#issuecomment-1418918593%E7%9A%84%E5%9B%9E%E7%AD%94) 学校提供的wevpn接口登陆后为*/www-cnki-net-443.webvpn*/而通过fsso.cnki.net搜索学校登录后（只要能搜到应该问题不大）为https://www.cnki.net/ ![image](https://user-images.githubusercontent.com/74956923/218541243-96e36a23-0350-429b-9b37-039ec546cf68.png) 而回答的意思大概是我们需要通过fsso.cnki.net网站登录获得本校在[https://www.cnki.net/官方接口cookies（我理解的公网）而不是本校的webvpn所提供的端口cookies（内网端口）](https://www.cnki.net/%E5%AE%98%E6%96%B9%E6%8E%A5%E5%8F%A3cookies%EF%BC%88%E6%88%91%E7%90%86%E8%A7%A3%E7%9A%84%E5%85%AC%E7%BD%91%EF%BC%89%E8%80%8C%E4%B8%8D%E6%98%AF%E6%9C%AC%E6%A0%A1%E7%9A%84webvpn%E6%89%80%E6%8F%90%E4%BE%9B%E7%9A%84%E7%AB%AF%E5%8F%A3cookies%EF%BC%88%E5%86%85%E7%BD%91%E7%AB%AF%E5%8F%A3%EF%BC%89) 由于我不是相关专业不会找cookies，所以直接用了首选项-茉莉花-获取知网用户数据的法子，直接在茉莉花（zotero）内置浏览器中打开fsso.cnki.net认证本校身份，然后进入了【公网端口】成功扒下附件还是pdf格式的 ![image](https://user-images.githubusercontent.com/74956923/218542976-79c48620-4b0e-452a-bf15-32f448ede15d.png) ![image](https://user-images.githubusercontent.com/74956923/218543095-76798cf2-48ba-43cf-b354-4bcfb567410f.png)
> 
> 按这种方法我还是下不到pdf，只能下载到一个名为 full text caj 的快照。

这是因为你用的仍然还是国内接口，没有pdf下载端口，默认下载了caj，简中国际版网址https://chn.oversea.cnki.net/kns/defaultresult/index

**Comment by skymagician** [comment]
> > > 好兄弟这个问题解决了，我参考了[https://github.com/l0o0/jasminum/issues/142#issuecomment-1418918593的回答](https://github.com/l0o0/jasminum/issues/142#issuecomment-1418918593%E7%9A%84%E5%9B%9E%E7%AD%94) 学校提供的wevpn接口登陆后为*/www-cnki-net-443.webvpn*/而通过fsso.cnki.net搜索学校登录后（只要能搜到应该问题不大）为https://www.cnki.net/ ![image](https://user-images.githubusercontent.com/74956923/218541243-96e36a23-0350-429b-9b37-039ec546cf68.png) 而回答的意思大概是我们需要通过fsso.cnki.net网站登录获得本校在[https://www.cnki.net/官方接口cookies（我理解的公网）而不是本校的webvpn所提供的端口cookies（内网端口）](https://www.cnki.net/%E5%AE%98%E6%96%B9%E6%8E%A5%E5%8F%A3cookies%EF%BC%88%E6%88%91%E7%90%86%E8%A7%A3%E7%9A%84%E5%85%AC%E7%BD%91%EF%BC%89%E8%80%8C%E4%B8%8D%E6%98%AF%E6%9C%AC%E6%A0%A1%E7%9A%84webvpn%E6%89%80%E6%8F%90%E4%BE%9B%E7%9A%84%E7%AB%AF%E5%8F%A3cookies%EF%BC%88%E5%86%85%E7%BD%91%E7%AB%AF%E5%8F%A3%EF%BC%89) 由于我不是相关专业不会找cookies，所以直接用了首选项-茉莉花-获取知网用户数据的法子，直接在茉莉花（zotero）内置浏览器中打开fsso.cnki.net认证本校身份，然后进入了【公网端口】成功扒下附件还是pdf格式的 ![image](https://user-images.githubusercontent.com/74956923/218542976-79c48620-4b0e-452a-bf15-32f448ede15d.png) ![image](https://user-images.githubusercontent.com/74956923/218543095-76798cf2-48ba-43cf-b354-4bcfb567410f.png)
> > 
> > 
> > 按这种方法我还是下不到pdf，只能下载到一个名为 full text caj 的快照。
> 
> 这是因为你用的仍然还是国内接口，没有pdf下载端口，默认下载了caj，简中国际版网址https://chn.oversea.cnki.net/kns/defaultresult/index

谢谢，国际版网址可以用。

**Comment by asong2022** [comment]
> > > > 好兄弟这个问题解决了，我参考了[https://github.com/l0o0/jasminum/issues/142#issuecomment-1418918593的回答](https://github.com/l0o0/jasminum/issues/142#issuecomment-1418918593%E7%9A%84%E5%9B%9E%E7%AD%94) 学校提供的wevpn接口登陆后为*/www-cnki-net-443.webvpn*/而通过fsso.cnki.net搜索学校登录后（只要能搜到应该问题不大）为https://www.cnki.net/ ![image](https://user-images.githubusercontent.com/74956923/218541243-96e36a23-0350-429b-9b37-039ec546cf68.png) 而回答的意思大概是我们需要通过fsso.cnki.net网站登录获得本校在[https://www.cnki.net/官方接口cookies（我理解的公网）而不是本校的webvpn所提供的端口cookies（内网端口）](https://www.cnki.net/%E5%AE%98%E6%96%B9%E6%8E%A5%E5%8F%A3cookies%EF%BC%88%E6%88%91%E7%90%86%E8%A7%A3%E7%9A%84%E5%85%AC%E7%BD%91%EF%BC%89%E8%80%8C%E4%B8%8D%E6%98%AF%E6%9C%AC%E6%A0%A1%E7%9A%84webvpn%E6%89%80%E6%8F%90%E4%BE%9B%E7%9A%84%E7%AB%AF%E5%8F%A3cookies%EF%BC%88%E5%86%85%E7%BD%91%E7%AB%AF%E5%8F%A3%EF%BC%89) 由于我不是相关专业不会找cookies，所以直接用了首选项-茉莉花-获取知网用户数据的法子，直接在茉莉花（zotero）内置浏览器中打开fsso.cnki.net认证本校身份，然后进入了【公网端口】成功扒下附件还是pdf格式的 ![image](https://user-images.githubusercontent.com/74956923/218542976-79c48620-4b0e-452a-bf15-32f448ede15d.png) ![image](https://user-images.githubusercontent.com/74956923/218543095-76798cf2-48ba-43cf-b354-4bcfb567410f.png)
> > > 
> > > 
> > > 按这种方法我还是下不到pdf，只能下载到一个名为 full text caj 的快照。
> > 
> > 
> > 这是因为你用的仍然还是国内接口，没有pdf下载端口，默认下载了caj，简中国际版网址https://chn.oversea.cnki.net/kns/defaultresult/index
> 
> 谢谢，国际版网址可以用。

请问下国际版网址还能用吗

**Comment by Prehistoric-Bubbles** [comment]
> > > > > 好兄弟这个问题解决了，我参考了[https://github.com/l0o0/jasminum/issues/142#issuecomment-1418918593的回答](https://github.com/l0o0/jasminum/issues/142#issuecomment-1418918593%E7%9A%84%E5%9B%9E%E7%AD%94) 学校提供的wevpn接口登陆后为*/www-cnki-net-443.webvpn*/而通过fsso.cnki.net搜索学校登录后（只要能搜到应该问题不大）为https://www.cnki.net/ ![image](https://user-images.githubusercontent.com/74956923/218541243-96e36a23-0350-429b-9b37-039ec546cf68.png) 而回答的意思大概是我们需要通过fsso.cnki.net网站登录获得本校在[https://www.cnki.net/官方接口cookies（我理解的公网）而不是本校的webvpn所提供的端口cookies（内网端口）](https://www.cnki.net/%E5%AE%98%E6%96%B9%E6%8E%A5%E5%8F%A3cookies%EF%BC%88%E6%88%91%E7%90%86%E8%A7%A3%E7%9A%84%E5%85%AC%E7%BD%91%EF%BC%89%E8%80%8C%E4%B8%8D%E6%98%AF%E6%9C%AC%E6%A0%A1%E7%9A%84webvpn%E6%89%80%E6%8F%90%E4%BE%9B%E7%9A%84%E7%AB%AF%E5%8F%A3cookies%EF%BC%88%E5%86%85%E7%BD%91%E7%AB%AF%E5%8F%A3%EF%BC%89) 由于我不是相关专业不会找cookies，所以直接用了首选项-茉莉花-获取知网用户数据的法子，直接在茉莉花（zotero）内置浏览器中打开fsso.cnki.net认证本校身份，然后进入了【公网端口】成功扒下附件还是pdf格式的 ![image](https://user-images.githubusercontent.com/74956923/218542976-79c48620-4b0e-452a-bf15-32f448ede15d.png) ![image](https://user-images.githubusercontent.com/74956923/218543095-76798cf2-48ba-43cf-b354-4bcfb567410f.png)
> > > > 
> > > > 
> > > > 按这种方法我还是下不到pdf，只能下载到一个名为 full text caj 的快照。
> > > 
> > > 
> > > 这是因为你用的仍然还是国内接口，没有pdf下载端口，默认下载了caj，简中国际版网址https://chn.oversea.cnki.net/kns/defaultresult/index
> > 
> > 
> > 谢谢，国际版网址可以用。
> 
> 请问下国际版网址还能用吗

今年上半年知网更新了接口后就用不了了，直接google cnki，置顶有海外版就是现在的海外版接口。

**Comment by jiaojiaodubai** [comment]
浏览器抓取问题请到[Translators_CN](https://github.com/l0o0/translators_CN)反馈。

知网转换器已经支持 VPN 和海外网络中使用。
