### ISSUE TITLE
添加在笔记中快速添加PDF所有书签信息或者单独窗口中预览PDF所有书签信息的功能

### ISSUE THREAD

**Issue by sjhsbhqf** [l0o0/jasminum#151]
添加在笔记中快速添加PDF所有书签信息或者单独窗口中预览PDF所有书签信息的功能。

因为我觉得手动给期刊论文添加PDF书签后（不一定要按照论文原目录的标题名字来，可以自己编辑一些个性化的理解或注释进去），下次再温习论文集时就可以通过书签快速预览各篇论文究竟在讲什么。

谢谢博主辛苦为我们维护这个茉莉花插件！！！！

**Comment by jiaojiaodubai** [comment]
Zotero 中可以在阅读界面的左侧看到书签目录，右侧能看到所有条目笔记，而预览批注则已经由 [Style 插件](https://zotero-chinese.com/plugins/#search=Ethereal%20Style)提供了
