### ISSUE TITLE
知网网页抓取失败

### ISSUE THREAD

**Issue by Eliauk777** [l0o0/jasminum#153]
![1677397440638](https://user-images.githubusercontent.com/100979184/221398464-5aae1131-9a04-4032-a403-7873a62446ef.png)
网页抓取数据的时候，嗯，总是提示使用cnki保存时发生错误，尝试使用save as website保存。

**Comment by syuuraku** [comment]
![image](https://github.com/l0o0/jasminum/assets/121651967/eb187577-f9fa-4112-8656-5cf07417c333) ![image](https://github.com/l0o0/jasminum/assets/121651967/39c02777-3972-48f1-a8c0-19808ac7dbf7)
只有出现这两种图标时，才能保存该条目。

**Comment by jiaojiaodubai** [comment]
浏览器抓取问题请到[Translators_CN](https://github.com/l0o0/translators_CN)反馈。
