### ISSUE TITLE
功能建议：根据标题搜索题录

### ISSUE THREAD

**Issue by ZHOU1218** [l0o0/jasminum#155]
建议可以仿照Zotero中根据DOI/ISSBN号等标识符获取题录信息的功能，可以同样弄一个搜索栏，输入文章标题就可以自动获取题录，不然有的时候看到一篇参考文献，只知道标题，如果想在Zotero内获取其题录信息乃至pdf（不跳转外部网页如知网），只有把随便一个pdf重命名为要搜索的标题，然后导入，感觉有点麻烦。
还建议可以根据标题自动更新全部元数据，除了年份、期刊卷号外还有url，因为有些题录的url过一段时间就失效了，更新url后能保证每一条题录都有长期有效的下载地址，对后面的搜集整理工作很有帮助。
最后，感谢开发者，赋予Zotero以全新的活力！

**Comment by jiaojiaodubai** [comment]
标题并不能唯一确定条目，而且在 Zotero 中模拟浏览器行为意味着要同步大量接口，建议自行检索。

**Comment by ZHOU1218** [comment]
您好，您的邮件我已收到，感谢您的来信，我将尽快处理。
                                                   周子涵
