### ISSUE TITLE
只要执行知网助手，zotero首选项界面就会立即出现bug，随后抓取知网附件失败

### ISSUE THREAD

**Issue by yuzixieshouhuajiaqi** [l0o0/jasminum#158]
只要执行右键知网助手的两个操作之一，zotero首选项界面就会立即出现bug，界面显示的插件变少，随后使用右键抓取知网附件就会抓取失败，提示“Jasminum:附件下载失败！可能是用户信息失效，没有下载权限或出现验证码，下载的附件是双页”，重启zoterozotero首选项界面恢复，知网附件抓取功能也跟着恢复
![image](https://user-images.githubusercontent.com/76084234/225825662-268cc3c5-26df-4fff-a8b6-6c20cf502210.png)
![image](https://user-images.githubusercontent.com/76084234/225825718-aba4114f-ef6e-411a-9031-cb97f9894224.png)

**Comment by l0o0** [comment]
同学你好，请问页面上出现的bug是什么？页面大小发生了改变么？

yuzixieshouhuajiaqi ***@***.***> 于2023年3月17日周五 14:11写道：

**Comment by l0o0** [comment]
https://github.com/retorquere/zotero-better-bibtex/issues/1584
https://github.com/PubPeerFoundation/pubpeer_zotero_plugin/issues/44

**Comment by trumansdo** [comment]
我也出现这个问题“附件下载失败，可能是用户信息时效，没有下载权限或者出现验证”，版本0.2.4里面，我看了下日志，打印出来的url 是这样的
![image](https://user-images.githubusercontent.com/36156087/228285806-5d32ae88-1581-4363-8c44-070d01ef63b8.png)

```txt
(3)(+0000028): Translate: resolving URL https://bar.cnki.net/bar/download/order?id=jBGETXBNdPImvx70aLAuJPYxPoFw%2Bp%2Bi0fIiSrcN6lUNEN8ir5JKoGhOO79jLkPrIPqgR38m15LFMAZn%2Bx0j%2F675x12sQbcmqHRDz3N8wPcX5FOcoxv3%2Bj06EVstImPRsJR7S7O3%2BV31gj0tjkn7C2X4FVCnyAFXBdumxVh7%2Fso6IutSjCCVA6ee4SOyBvNlJva7W4ruOurS0cH6tFFuTA%3D%3D

(3)(+0000000): Translate: resolved to https://bar.cnki.net/bar/download/order?id=jBGETXBNdPImvx70aLAuJPYxPoFw%2Bp%2Bi0fIiSrcN6lUNEN8ir5JKoGhOO79jLkPrIPqgR38m15LFMAZn%2Bx0j%2F675x12sQbcmqHRDz3N8wPcX5FOcoxv3%2Bj06EVstImPRsJR7S7O3%2BV31gj0tjkn7C2X4FVCnyAFXBdumxVh7%2Fso6IutSjCCVA6ee4SOyBvNlJva7W4ruOurS0cH6tFFuTA%3D%3D
```
直接访问这个url得到是知网提示“来源应用不正确(01)”
![image](https://user-images.githubusercontent.com/36156087/228286273-a562ee2c-1e8a-46e1-83b6-2179bc731ad3.png)




[联系我们](https://cs.cnki.net/client-pc/)

[中国知网](https://www.cnki.net/)

**Comment by yzy1228682367** [comment]
mac版本也出现了“Jasminum:附件下载失败！可能是用户信息失效，没有下载权限或出现验证码，下载的附件是网页”的提示，但是知网账号是可以下载的，而且首选项似乎没有出现问题。
![CleanShot 2023-04-11 at 10 50 11@2x](https://user-images.githubusercontent.com/50101175/231043153-1e6d2108-3475-41c7-b986-132580a0a60b.png)

**Comment by yzy1228682367** [comment]
全部的日志是这样子的。

**Comment by l0o0** [comment]
等我测试好了，我会发布个新版。现在网络好像有点不稳定

**Comment by yzy1228682367** [comment]
感谢大佬❤️

> 等我测试好了，我会发布个新版。现在网络好像有点不稳定

**Comment by Whutyzt** [comment]
> bug是首选项界面上显示的插件会变少，只要是中文文献，使用右键知网助手的两个操作之一或者使用绿青蛙插件的更新条目元数据，都会百分百触发首选项界面的bug
发现了，该BUG已经修复，请问作者大大，我这边又有新bug，多篇选中抓取就会下载CAJ，进入论文界面单篇抓取就是PDF，其他的设置都是正常的。

**Comment by l0o0** [comment]
@Whutyzt 搜索页面知网只提供CAJ，文献详情页面有CAJ和PDF。
