### ISSUE TITLE
有时会出现pdf抓取知网元素失败的情况

### ISSUE THREAD

**Issue by qizidog** [l0o0/jasminum#16]
# 有时会出现pdf抓取知网元素失败的情况

我从知网下载了一篇学术论文，全名为：基于迁移学习的多源遥感影像建筑垃圾识别_李思琦.pdf。

通过拖拽的形式我将其导入到zotero中，但是出现报错弹窗，弹窗标题名为 [Javascript Application]，对此我做了两种尝试：

1. 设定jasminum插件的提取规则为 `{%g}` 时
    - 弹窗提示信息为 --> 作者：基于迁移学习的多源遥感影像建筑垃圾识别；篇名：李思琦；
2. 设定jasminum插件的提取规则为 `{%t}` 时
    - 弹窗提示信息为 --> 作者： ；篇名：基于迁移学习的多源遥感影像建筑垃圾识别_李思琦；

此前我使用的jasminum插件为v0.04版本，当时抓取知网元素失败好像不会有弹窗显示，今天更新至v0.0.6版本才发现问题所在。

对于这个不便利的操作，我之前的解决方式是将提取规则设定为 `{%t}` ，并且在抓取元素之前都将pdf重命名为 `基于迁移学习的多源遥感影像建筑垃圾识别.pdf` 这种只含题目的名字。

能否提供一下更多的提取规则设定方式（当前只能找到`{%g}`，`{%t}`，`{%y}`这三种）？是否作者您已经提供了其他提取规则，只是没有展示出相应的文档？

望解决。辛苦！

**Comment by qizidog** [comment]
啊，我js只是入门级别，看了下你的代码，我就不pull request了，大佬你看着弄吧 =. =！

**Comment by l0o0** [comment]
因为这个是从知网上下载的固定格式，一般就是title 和 author 这种，你那个论文应该是{%t}_{%g} 这种。后面我觉得如果抓取失败带是需要告知一下，不然以为我这什么反应也没有。。

**Comment by qizidog** [comment]
收到您的回复，万分感谢。

规则调整为{%t}_{%g}后的确可以正常抓取元素了。

不过这个提取规则命名的设置似乎有些难以理解，这种提取规则命名为{%t}_{%a}，{%a}=author是不是会更好一点？即如下：

- '基于迁移学习的多源遥感影像建筑垃圾识别_李思琦.pdf' 对应 `{%t}_{%a}`
- '基于迁移学习的多源遥感影像建筑垃圾识别.pdf' 对应 `{%t}`
- '基于迁移学习的多源遥感影像建筑垃圾识别_2020.pdf' 对应 `{%t}_{%y}`
- '基于迁移学习的多源遥感影像建筑垃圾识别_李思琦_2020.pdf' 对应 `{%g}`，等同于 `{%t}_{%a}_{%y}`

若更进一步，借助split("_")获取list后，使用正则直接匹配{%t}，{%a}，{%y}三种属性是否会更优一点？

当然，比比叨一大堆，能用我已经很满足了，以上内容仅供参考，再次感谢！

**Comment by l0o0** [comment]
因为我这个是参考zotfile这个插件里的命名格式的，你可以参考一下[zotfile的格式](http://zotfile.com/#renaming-rules)。
一般来说知网上下载的文件，应该是没有Year这个命名方法的，我处理时就会把这个年份删掉。正则表达式也是可以的，不过我目前觉得这个应该也能处理目前的情况，所以就不想改了。

**Comment by qizidog** [comment]
好的，正在看你的代码，不懂的太多了，慢慢折腾，有机会向你请教，这个issue我就先close了。

**Comment by l0o0** [comment]
@qizidog 我也是刚学js，刚尝试制作插件，有问题一起交流
