### ISSUE TITLE
Automatically batch set language failed

### ISSUE THREAD

**Issue by WissenY** [l0o0/jasminum#160]
System: MacOS 13.0.1
Zotero Version: 6.0.23
Jasminum Version: 0.2.4

Issue: 在Jasminum中设置“Batch Set language"为“zh_CN, en_US”后，选中多个文献后再使用右键菜单里的“automatically batch set language"依然只会将文献info/language字段修改为“en"或“zh"

**Comment by l0o0** [comment]
自动设置语言这里，结果是要符合iso标准的https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

标准要求地区的语言是两个小写字母。你可以使用手动设置那个。后面如果可以，应该给iso和自定义间设置一个匹配关系。这样就可以了

**Comment by zepinglee** [comment]
> System: MacOS 13.0.1 Zotero Version: 6.0.23 Jasminum Version: 0.2.4
> 
> Issue: 在Jasminum中设置“Batch Set language"为“zh_CN, en_US”后，选中多个文献后再使用右键菜单里的“automatically batch set language"依然只会将文献info/language字段修改为“en"或“zh"

是 `zh-CN` 和 `en-US`，不是下划线。

> 自动设置语言这里，结果是要符合iso标准的https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
> 
> 标准要求地区的语言是两个小写字母。你可以使用手动设置那个。后面如果可以，应该给iso和自定义间设置一个匹配关系。这样就可以了

准确地讲应该是 [IETF BCP 47 language tag](https://en.wikipedia.org/wiki/IETF_language_tag) 的子集。ISO 规定了语言代码和地区代码，但是没规定中间的连接符。
