### ISSUE TITLE
m系列Mac无法使用pdftk

### ISSUE THREAD

**Issue by spacding** [l0o0/jasminum#161]
brew安装的目录为/usr/local/bin/pdftk，请问这个目录怎么输入？

**Comment by l0o0** [comment]
/usr/local/bin

**Comment by mlin1w** [comment]
你怎么解决的呀？ @spacding

**Comment by spacding** [comment]
> 你怎么解决的呀？ @spacding

目前知网下载的PDF论文默认带书签目录，暂时没用pdftk

**Comment by pencilheart** [comment]
> /usr/local/bin
下载安装@PerfBleu 的包后,设置为"/usr/local/bin"成功解决！
