### ISSUE TITLE
在论文搜索页选择多篇抓取会出现只下载CAJ的情况，单篇抓取就会下载PDF

### ISSUE THREAD

**Issue by Whutyzt** [l0o0/jasminum#164]
翻译器和其他设置都是ok，并且是最新版本。

**Comment by l0o0** [comment]
这个还是知网在搜索页面只提供CAJ的原因，我收到同学的反馈，海外版的搜索页面应该也只有CAJ

**Comment by zhulewen1998** [comment]
您好，我也是遇到了同样的问题，我要单独点进去一个论文的页面，抓取的才是pdf。其余都是CAJ

**Comment by mlin1w** [comment]
作者大大，请问这个算BUG吗？还是就是正常现象？ @l0o0

**Comment by jiaojiaodubai** [comment]
浏览器抓取问题请到[Translators_CN](https://github.com/l0o0/translators_CN)反馈。
