### ISSUE TITLE
翻译器更新报错

### ISSUE THREAD

**Issue by HFly1** [l0o0/jasminum#165]
![1](https://user-images.githubusercontent.com/49269021/233069050-34634ced-e1ad-406c-a2e1-1a3a4015aff6.jpg)

**Comment by l0o0** [comment]
@HFly1 GitCode源那里不行了，现在要登录才能使用

**Comment by l0o0** [comment]
@HFly1 发版了，用新版本 https://github.com/l0o0/jasminum/releases/tag/v0.2.6

**Comment by HFly1** [comment]
> @HFly1 发版了，用新版本 https://github.com/l0o0/jasminum/releases/tag/v0.2.6

嗯嗯，已经更新，谢谢！
