### ISSUE TITLE
更新到最新版本后出现翻译器界面空空如也，更新翻译器信息出现延时错误

### ISSUE THREAD

**Issue by liyunxiao2020** [l0o0/jasminum#166]
![image](https://user-images.githubusercontent.com/112650414/233553953-040192f5-a24b-4691-96bb-1c319f68e43a.png)
![image](https://user-images.githubusercontent.com/112650414/233577612-92665947-2530-42bd-a658-e85895e55cea.png)

**Comment by xiaoxiangst** [comment]
我也是这种问题，群里好多也出现了

**Comment by jieniu** [comment]
请问解决了吗

**Comment by jiaojiaodubai** [comment]
同 #187
