### ISSUE TITLE
抓取硕博论文时，能否自动添加一个标签用来区分硕士或博士学位论文？

### ISSUE THREAD

**Issue by weihecrazy** [l0o0/jasminum#168]
如题，zotero里硕博论文无法很好地区分，希望能够自动根据题录类型 添加一个标签，最好是支持自定义标签，或与zotero style联动一下，支持#标签。感谢开发者！这个插件非常好用！！

**Comment by l0o0** [comment]
好的，我去style那里提一个需求

WEIHE ***@***.***> 于 2023年4月23日周日 下午5:10写道：

**Comment by l0o0** [comment]
我准备去提issue的时候，想了一个，不知道同学有没有试过zotero tag插件，这个可以自定义添加标签的动作

**Comment by weihecrazy** [comment]
你好zotero tag 的规则好像不能设置成根据文献信息添加标签，只有几个固定的动作。不知道是不是我不太懂怎么使用zotero tag。祝好！
        
            
        
    
    
    

    

    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年4月24日 15:17
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [l0o0/jasminum] 抓取硕博论文时，能否自动添加一个标签用来区分硕士或博士学位论文？ (Issue #168)
        
      
    
  

我准备去提issue的时候，想了一个，不知道同学有没有试过zotero tag插件，这个可以自定义添加标签的动作

**Comment by l0o0** [comment]
@weihecrazy zotero tag 插件更新了，后期会开发一套更复杂的action，满足你的需求

**Comment by jiaojiaodubai** [comment]
硕博论文可以通过“学位论文类型”字段进行区分，目前转换器会自动处理这一字段。

**Comment by weihecrazy** [comment]
Nice，非常感谢




573717985
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "l0o0/jasminum"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月25日(星期五) 晚上10:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [l0o0/jasminum] 抓取硕博论文时，能否自动添加一个标签用来区分硕士或博士学位论文？ (Issue #168)





 
硕博论文可以通过“学位论文类型”字段进行区分，目前转换器会自动处理这一字段。
