### ISSUE TITLE
能否设置多个自动？比如自动合并中文姓名，自动处理语言，自动处理日期。

### ISSUE THREAD

**Issue by earthmoon** [l0o0/jasminum#172]
您好，

能否在这个插件中设置多个自动。比如中文文献导入后，自动合并作者姓、名；自动添加语言；自动将日期格式处理正确？

谢谢！

**Comment by earthmoon** [comment]
> 日期格式，一般会有什么问题？

比如从各个学术网站导出的日期，再用Better BibTeX导出参考文献，很多时候日期格式并不对，似乎是因为从学术网站导出的日期格式不是Zotero默认的格式。所以如果当文献刚导入至Zotero，这个插件能自动处理日期格式会很好。如果还能自动添加语言、自动合并中文作者的姓也会更好吧。谢谢。

**Comment by zepinglee** [comment]
触发自动修改的事件能否区分为 a. 导入文献 b. 同步群组中新添的文献？目前第二种情况也会触发自动修改，但是会导致群组中的文献被多人反复修改。所以我不得不经常运行脚本处理一遍（见 <https://gitee.com/zotero-chinese/zotero-chinese/issues/I6W1QY>）。

**Comment by earthmoon** [comment]
> > 触发自动修改的事件能否区分为 a. 导入文献 b. 同步群组中新添的文献？目前第二种情况也会触发自动修改，但是会导致群组中的文献被多人反复修改。所以我不得不经常运行脚本处理一遍（见 [https://gitee.com/zotero-chinese/zotero-chinese/issues/I6W1QY）。](https://gitee.com/zotero-chinese/zotero-chinese/issues/I6W1QY%EF%BC%89%E3%80%82)
> 
> 插件应该可以通过这样适配仅对导入进用户文库的条目触发自动更改，而 group 和 feed 都不变。 [northword/zotero-format-metadata@e2c56a2#diff-a2d969770fbca6d31b2bcb062b5d406aa54f9ddebef57996faacc6f82e746e42](https://github.com/northword/zotero-format-metadata/commit/e2c56a23c4b9c6d505a79ff625e2efc053df8a2a#diff-a2d969770fbca6d31b2bcb062b5d406aa54f9ddebef57996faacc6f82e746e42)
> 
> > 比如中文文献导入后，自动合并作者姓、名；自动添加语言；自动将日期格式处理正确？
> 
> 插件 zotero-format-metadata 可以在添加时处理语言和日期格式
> 
> 我个人不建议合并作者姓名，至少也应提供首选项且默认关闭。
> 
> 另外，我测试的似乎茉莉花好像是可以在添加条目时修改这几个字段的。

感觉有点高端，不敢改。谢谢了。

**Comment by zepinglee** [comment]
> 插件应该可以通过这样适配仅对导入进用户文库的条目触发自动更改，而 group 和 feed 都不变。 [northword/zotero-format-metadata@e2c56a2#diff-a2d969770fbca6d31b2bcb062b5d406aa54f9ddebef57996faacc6f82e746e42](https://github.com/northword/zotero-format-metadata/commit/e2c56a23c4b9c6d505a79ff625e2efc053df8a2a#diff-a2d969770fbca6d31b2bcb062b5d406aa54f9ddebef57996faacc6f82e746e42)

这段太赞了！

**Comment by jiaojiaodubai** [comment]
已经由 Zotero Linter 完成。
