### ISSUE TITLE
【bug】非官方维护中文翻译器 - 常常被无故清空列表

### ISSUE THREAD

**Issue by shisunsun** [l0o0/jasminum#174]
非官方维护中文翻译器 - 常常被无故清空列表

复现：
1. 按照教程，替换原文件夹中翻译器 js 文件
2. 正常刷新出各翻译器，列表排满状态
3. 过段时间（几天不等），打开 zotero，显示如图 js 错误提示，翻译器列表被清空。

（与 vpn 有关，但属于 bug）

<img width="658" alt="image" src="https://github.com/l0o0/jasminum/assets/21273224/7aa2d5a7-80c3-461e-a6ea-f39b3693663f">

**Comment by jiaojiaodubai** [comment]
待 @l0o0 将 转换器 JOSN 列表存储位置改到数据文件夹将修复此问题。

**Comment by jiaojiaodubai** [comment]
同 #187
