### ISSUE TITLE
不知道 tool - batch set language 是如何工作的，无论怎么设置，作用后结果都是 "zh"

### ISSUE THREAD

**Issue by InnocenseYu** [l0o0/jasminum#176]
知网“自动抓取”或者“手动操作批量操作”后，info - language 都是 zh，在设置中 变更为zh-CN，作用结果仍然不变

**Comment by zepinglee** [comment]
Zotero 的官方文档  <https://www.zotero.org/support/kb/item_types_and_fields#general_fields> 关于 `language` 的描述：

> The language of publication for an item. We recommend storing these as two letter [ISO language codes](http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) followed by two letter [ISO country codes](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) (e.g., en-US for American English, or de-DE for German).

不再是以前的“*optionally* followed by two letter country codes”。所以我建议统一设成 `zh-CN`。

**Comment by InnocenseYu** [comment]
> Zotero 的官方文档 https://www.zotero.org/support/kb/item_types_and_fields#general_fields 关于 `language` 的描述：
> 
> > The language of publication for an item. We recommend storing these as two letter [ISO language codes](http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) followed by two letter [ISO country codes](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) (e.g., en-US for American English, or de-DE for German).
> 
> 不再是以前的“_optionally_ followed by two letter country codes”。所以我建议统一设成 `zh-CN` 或 `en-US`。

反复尝试后，还是不知道怎么使用 `batch set language` 根据语言自动化设置为`zh-CN` 或者 `en-US` [捂脸] ，目前使用的是js 脚本

**Comment by northword** [comment]
此页按这样设置

![image](https://github.com/l0o0/jasminum/assets/44738481/f2fef9e2-c181-4f5f-9e71-5cf8baa111b7)




![image](https://github.com/l0o0/jasminum/assets/44738481/f115ef04-e22e-4a8e-9c05-fe02c38b8854)

**Comment by InnocenseYu** [comment]
> 此页按这样设置
> 
> 
> 
> ![image](https://github.com/l0o0/jasminum/assets/44738481/f2fef9e2-c181-4f5f-9e71-5cf8baa111b7)
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ![image](https://github.com/l0o0/jasminum/assets/44738481/f115ef04-e22e-4a8e-9c05-fe02c38b8854)
> 
> 

谢谢你的耐心解答。因为我使用的style需要中文为 zh-CN，英文为 en-US，所以想添加文件到zotero时自动化设置语言为以上两个，目前测试下来，你推荐的方法也没有成功。当前我使用的方法有两个，一个是使用语言栏排序，手动批量修改语言栏；另一个是使用脚本文件

**Comment by northword** [comment]
> 谢谢你的耐心解答。因为我使用的style需要中文为 zh-CN，英文为 en-US，所以想添加文件到zotero时自动化设置语言为以上两个，目前测试下来，你推荐的方法也没有成功。当前我使用的方法有两个，一个是使用语言栏排序，手动批量修改语言栏；另一个是使用脚本文件

没有成功是指什么呢？可以看看当前结果不？是没有在添加时识别语言？还是识别的结果错误？
茉莉花好像两个代码间一直用的下划线而不是短横线，如果是这个问题，就需要等插件更改了。

另也可以试一下插件：zotero-format-metadata，也提供了自动识别语言。
还有韩老师的delitemwithatt，可以手动指定。
