### ISSUE TITLE
点右键出不来“知网助手”怎么破？

### ISSUE THREAD

**Issue by alopehba** [l0o0/jasminum#178]
点右键出不来“知网助手”
<img width="419" alt="image" src="https://github.com/l0o0/jasminum/assets/22520210/6f5b3221-3c34-4297-892b-014596562937">
其他设置如下：
<img width="533" alt="image" src="https://github.com/l0o0/jasminum/assets/22520210/1ee76b39-5c46-4d5a-8f20-221caf802479">
还有：
<img width="527" alt="image" src="https://github.com/l0o0/jasminum/assets/22520210/23a74adb-fde6-469e-806f-43d03dd0f2ba">

**Comment by alopehba** [comment]
> 1. 在条目而不是附件上右键
> 2. 说明当前插件版本并更新至最新版本

就是在条目的呢，只拉pdf进去没有参考文献格式信息，右键点不出知网助手。
0.2.6版本，23年5月18日
<img width="362" alt="image" src="https://github.com/l0o0/jasminum/assets/22520210/bf1163ee-b534-419e-860a-b5d8298b2372">
<img width="446" alt="image" src="https://github.com/l0o0/jasminum/assets/22520210/f09c5dd1-976f-47f6-99fa-0c87282ee77d">

**Comment by northword** [comment]
excepted，知网助手内的功能依赖于正常的条目题录信息。

**Comment by northword** [comment]
补充：单一的PDF文件不应成为顶级条目，他应总有一个父条目，就如第一张图所示。

**Comment by alopehba** [comment]
> 我看有些人不加父条目也能抓的到。
我现在加了个父条目，还是抓不到

<img width="653" alt="image" src="https://github.com/l0o0/jasminum/assets/22520210/a45ac0fd-128b-465b-8fa0-7fe54b8b8922">

**Comment by alopehba** [comment]
> 补充：单一的PDF文件不应成为顶级条目，他应总有一个父条目，就如第一张图所示。

还是抓不到，有没有父题录都抓不到。

**Comment by l0o0** [comment]
主要是只想让从知网下载的PDF或CAJ才可以进行搜索，避免其他来源的PDF搜索不到，减少使用问题。**小工具**这个菜单就没有做任何限制。

知网助手里有4个子菜单：抓取知网元数据，抓取知网引用数，添加PDF书签，查找知网附件


我查了下代码，这些子菜单的条件分别是

**抓取知网元数据**
1. 是来源于知网的webpage 网页快照条目
2. 包含中文的附件，后缀名是'pdf', 'caj', 'kdh', 'nh'中一种，同时该附件不能在某个条目下（如果在条目下，那认为该pdf已经抓取过元数据了）

**添加PDF书签**

1. 右键选取的为某条目下的附件 
2. PDF文件
3. 该PDF所属条目类型为学位论文。期刊的PDF，知网没有提供详细的章节页面信息，所以过滤掉了

**抓取知网引用数** 和 **查找知网附件**，这两个菜单的条件一样，我感觉这个逻辑可以优化😂

1. 正常有元数据的条目
2. 该条目不能只是一个文件，比如不能是一个PDF拖到Zotero中得到的一个条目

## 说明下你上面截图的问题

![图片](https://github.com/l0o0/jasminum/assets/2743744/1c964f00-45ea-471d-87c0-2fe37149c46d)
这个应该是因为你这个PDF没有中文，你试试重命名加个中文试试。如果PDF没中文，大概率不是从知网下载

![](https://user-images.githubusercontent.com/22520210/246360143-bf1163ee-b534-419e-860a-b5d8298b2372.png)
![](https://user-images.githubusercontent.com/22520210/246594533-a45ac0fd-128b-465b-8fa0-7fe54b8b8922.png)
这个知网助手菜单应该是只显示**抓取知网引用数** 和 **查找知网附件**，应该是符合上面提到的条件


当时加这些条目主要是减少同学问我为什么这个文件为什么不能抓取不到元数据，现在都我自己搞晕了。重新看了代码，复习了一遍。


参考代码：
https://github.com/l0o0/jasminum/blob/5f7a39ed139f5499bfd264dc2983d09cadaf7711/chrome/content/scripts/ui.js#LL36C72-L36C85

**Comment by jiaojiaodubai** [comment]
不是 bug，你需要选中中文的附件或者条目才能触发此菜单。
