### ISSUE TITLE
2023-07-03 CNKI知网翻译器出错：保存此条目时发生错误

### ISSUE THREAD

**Issue by Huaweidev** [l0o0/jasminum#181]
2023-07-03 CNKI知网翻译器出错：保存此条目时发生错误，有无好的解决办法？
![image](https://github.com/l0o0/jasminum/assets/10258421/7985c03b-fc3e-4b8c-b86d-7aa2c9c689af)

**Comment by l0o0** [comment]
https://github.com/l0o0/translators_CN/commit/f2d03676b515c1d38444a66a69b864ab5f81c1db
