### ISSUE TITLE
2023-7-9 本地中文PDF更新知网元数据失败

### ISSUE THREAD

**Issue by Bigconfidence666** [l0o0/jasminum#182]
直接把已下载的知网pdf拖进zotero后，右键点击pdf文件，选择知网助手选项下的【抓取知网元数据】，软件没有反应。但从知网页用扩展插件下载的pdf就可以完整生成条目。我看挺多人出现了这种情况，之前也出现过多次相似的提问，作者给了调整后的安装包就解决了？希望能得到解答，感谢！
![24747cda3e494a2da962af6ed50c59a](https://github.com/l0o0/jasminum/assets/139030620/a9888aa5-146a-4ca8-b454-4d0e54bcf29e)

**Comment by Bigconfidence666** [comment]
发现之前也出现过多次相似的提问，作者给了调整后的安装包就解决了？

**Comment by Bigconfidence666** [comment]
文献：网络基础设施建设、信息可得性与企业创新边界_沈坤荣.pdf
在我的电脑上（校园网登录）上右键抓取知网元数据失败，但别的同学在家里试的，抓取成功

**Comment by Bigconfidence666** [comment]
文献：银行业监管处罚效应研究_明雷.pdf
这篇文献在改用{%t}的方法调整文件名和茉莉花模板后成功了一次，但删除重试又不行了。

**Comment by l0o0** [comment]
> 文献：网络基础设施建设、信息可得性与企业创新边界_沈坤荣.pdf 在我的电脑上（校园网登录）上右键抓取知网元数据失败，但别的同学在家里试的，抓取成功
> 
> 文献：银行业监管处罚效应研究_明雷.pdf 这篇文献在改用{%t}的方法调整文件名和茉莉花模板后成功了一次，但删除重试又不行了。

`网络基础设施建设、信息可得性与企业创新边界_沈坤荣.pdf` 和 `银行业监管处罚效应研究_明雷.pdf` 这个用 `{%t}_{%g}` 是标题_作者的形式，我测试了 都正常抓取。

建议
1. 重新设置文件名识别模板为 `{%t}_{%g}`，再识别
2. 如果1步骤后还失败，试试关掉校园网VPN（需要打开 APP这种），抓取元数据不需要登录校园网，普通网络就行（能正常上网就行）

**Comment by Bigconfidence666** [comment]
> > 文献：网络基础设施建设、信息可得性与企业创新边界_沈坤荣.pdf 在我的电脑上（校园网登录）上右键抓取知网元数据失败，但别的同学在家里试的，抓取成功
> > 文献：银行业监管处罚效应研究_明雷.pdf 这篇文献在改用{%t}的方法调整文件名和茉莉花模板后成功了一次，但删除重试又不行了。
> 
> `网络基础设施建设、信息可得性与企业创新边界_沈坤荣.pdf` 和 `银行业监管处罚效应研究_明雷.pdf` 这个用 `{%t}_{%g}` 是标题_作者的形式，我测试了 都正常抓取。
> 
> 建议
> 
> 1. 重新设置文件名识别模板为 `{%t}_{%g}`，再识别
> 2. 如果1步骤后还失败，试试关掉校园网VPN（需要打开 APP这种），抓取元数据不需要登录校园网，普通网络就行（能正常上网就行）

您好，我试了下，步骤1失败，步骤2还是失败（使用个人热点），还是解决不了问题，右键更新知网数据后，茉莉花插件没给任何反应，也不知道咋回事了😫

**Comment by liujin-r** [comment]
你好 解决了吗

**Comment by Bigconfidence666** [comment]
> 你好 解决了吗

解决了，问题在于我同时还开了某个显示影响因子的插件，冲突了

**Comment by HISUNDAY** [comment]
请问是哪个插件冲突了呢？我现在各种方法都试过了，都没用

**Comment by jiaojiaodubai** [comment]
@HISUNDAY 不要在多个 issue 下刷评论，先看置顶 issue 的说明
