### ISSUE TITLE
如何在知网页面根据搜索结果一次性批量抓取自己需要的文献？

### ISSUE THREAD

**Issue by Xilinjin** [l0o0/jasminum#185]
在知网页面根据关键词可以在zotero-item-selectors选取需要的几篇文献，也可以全选，但是一旦进入保存到zotero的文库中就开始【保存此条目时发生错误。查看 [翻译器故障排除]获取更多信息。】
我已经尝试关闭vpn软件，重新下载translators并更新cnki.js，以及update translators，重新关闭浏览器多次刷新等等一系列操作。依然失败抓取。感觉一篇一篇进入文献介绍界面再一篇一篇下载有点麻烦，想问问各位大佬们有没有解决办法呀？怎么样可以实现多篇文献一次性抓取到我的文库中呀？救救！感谢帮助！

**Comment by l0o0** [comment]
如果不使用vpn，直接使用cnki.net
会有异常么

Xilinjin ***@***.***> 于 2023年7月26日周三 下午5:27写道：

**Comment by Xilinjin** [comment]
> 

是的，我关掉了vpn软件也退出了校园网的登录。再进入知网界面还是得一篇一篇点进去再点小图标。依然没办法在搜索界面多篇文献一次性下载= =我用的是edge浏览器，反正各种刷新都试过了哎

**Comment by Xilinjin** [comment]
求助来了！我这边还是不行，没法一次性在搜索界面多选需要的几篇文献，这还有可能是什么样的问题呀？有没有可能我努力解决一下...
就edge浏览器，退出校园vpn也不行，刷新翻译器也不行了qaq
















在 2023-07-26 23:07:33，"Linxzh" ***@***.***> 写道：

如果不使用vpn，直接使用cnki.net
会有异常么

Xilinjin ***@***.***> 于 2023年7月26日周三 下午5:27写道：

**Comment by l0o0** [comment]
我这刷新好之后，可以正常下载。
![图片](https://github.com/l0o0/jasminum/assets/2743744/a2afcb07-9948-41d2-bc81-1247749e64bb)
edge 也正常。
![图片](https://github.com/l0o0/jasminum/assets/2743744/f5b22937-2b55-4261-9cce-97065534f4d1)

你在这打开Zotero Connector的设置页面，然后先点Enable logging，再点view output。再去点那个抓取按键，然后再到Connector页面点View output，把Output 的信息贴上来
![图片](https://github.com/l0o0/jasminum/assets/2743744/580cf5af-0e01-48d4-bd43-f58c442c73bd)

**Comment by Xilinjin** [comment]
救命，咋试都还是这样

我这里还是不行，怎么样刷新都一样，重新安装了也是这样，就只能保存网页截图。




在 2023-07-27 22:43:00，"Linxzh" ***@***.***> 写道：

我这刷新好之后，可以正常下载。

edge 也正常。


你在这打开Zotero Connector的设置页面，然后先点Enable logging，再点view output。再去点那个抓取按键，然后再到Connector页面点View output，把Output 的信息贴上来

**Comment by l0o0** [comment]
哎，那加QQ 458386996

**Comment by Xilinjin** [comment]
嗨！我加了qq但是一直没有通过来着，麻烦有空的时候指导我一下，非常感谢！！用不好它就很难受，害！
我qq  1354378988













在 2023-07-27 23:15:30，"Linxzh" ***@***.***> 写道：

哎，那加QQ 458386996

**Comment by jiaojiaodubai** [comment]
使用VPN可能会改变知网cookies对用户IP的标注，目前知网转换器已经适配海外版，如果是由于频繁请求造成的下载错误，现在的知网翻译器会给出遇到验证码的提示，此问题应该不存在了。

**Comment by jiaojiaodubai** [comment]
浏览器抓取问题请到[Translators_CN](https://github.com/l0o0/translators_CN)反馈。
