### ISSUE TITLE
Zotero 7 插件菜单显示不正常

### ISSUE THREAD

**Issue by skymagician** [l0o0/jasminum#187]
MacBook Air m1
MacOS Ventura 13.4
Zotero 7.0.0-beta.32+5e27a7501

<img width="799" alt="Screenshot 2023-08-11 at 23 47 04" src="https://github.com/l0o0/jasminum/assets/25891462/80b820ca-b9b3-48a0-a4ed-474c981952db">

**Comment by l0o0** [comment]
不好意思，忘了加上英文的信息了，只管中文的。下个版本加上

**Comment by skymagician** [comment]
> 不好意思，忘了加上英文的信息了，只管中文的。下个版本加上

lol 原来如此
