### ISSUE TITLE
zotero 7 设置界面 非官方转换器 一直转圈

### ISSUE THREAD

**Issue by jlu511** [l0o0/jasminum#188]
![image](https://github.com/l0o0/jasminum/assets/64378673/fa5339b2-2a94-4518-9841-06df378cc808)
zotero 7 设置界面 非官方转换器 一直转圈，请大佬修复

**Comment by l0o0** [comment]
extensions.zotero.jasminum.translatorurl 设置为 https://oss.wwang.de/translators_CN
![图片](https://github.com/l0o0/jasminum/assets/2743744/6099d4c2-8b59-4fdd-9b20-7774b12dadd9)
你看看你的高级设置里是显示什么

**Comment by jlu511** [comment]
![image](https://github.com/l0o0/jasminum/assets/64378673/5a62078c-7be9-4e05-a8b6-89095f3260d5)
没有这个选项，这是怎么回事啊，beta 33，插件最新版100-3

**Comment by hujie12306** [comment]
> extensions.zotero.jasminum.translatorurl 设置为 https://oss.wwang.de/translators_CN ![图片](https://user-images.githubusercontent.com/2743744/260246603-6099d4c2-8b59-4fdd-9b20-7774b12dadd9.png) 你看看你的高级设置里是显示什么

我的也是，都是最新版
![image](https://github.com/l0o0/jasminum/assets/61086637/ae2d17ac-026e-4613-ab57-78a38f6caa63)
![image](https://github.com/l0o0/jasminum/assets/61086637/e3911274-0da8-4ee8-82fe-332f94bb8a09)

**Comment by QianXuZOZ** [comment]
> extensions.zotero.jasminum.translatorurl 设置为 https://oss.wwang.de/translators_CN ![图片](https://user-images.githubusercontent.com/2743744/260246603-6099d4c2-8b59-4fdd-9b20-7774b12dadd9.png) 你看看你的高级设置里是显示什么

https://oss.wwang.de/translators_CN 这个网页目前挂不挂梯子都打不开

**Comment by l0o0** [comment]
> 

https://oss.wwang.de/translators_CN/BiliBili.js  这个链接，以上各位能打开么

**Comment by FLIER001** [comment]
> > 
> 
> https://oss.wwang.de/translators_CN/BiliBili.js 这个链接，以上各位能打开么

可以打开

**Comment by QianXuZOZ** [comment]
> > 
> 
> https://oss.wwang.de/translators_CN/BiliBili.js 这个链接，以上各位能打开么

可以打开

**Comment by FLIER001** [comment]
> https://oss.wwang.de/translators_CN

按照这个方式配置能够成功生效，谢谢大佬

**Comment by FLIER001** [comment]
> extensions.zotero.jasminum.translatorurl 设置为 https://oss.wwang.de/translators_CN ![图片](https://user-images.githubusercontent.com/2743744/260246603-6099d4c2-8b59-4fdd-9b20-7774b12dadd9.png) 你看看你的高级设置里是显示什么

按照这个方式配置能够成功生效，谢谢大佬

**Comment by l0o0** [comment]
> > extensions.zotero.jasminum.translatorurl 设置为 https://oss.wwang.de/translators_CN ![图片](https://user-images.githubusercontent.com/2743744/260246603-6099d4c2-8b59-4fdd-9b20-7774b12dadd9.png) 你看看你的高级设置里是显示什么
> 
> https://oss.wwang.de/translators_CN 这个网页目前挂不挂梯子都打不开

更新这个配置后，能显示么

**Comment by l0o0** [comment]
或者安装最新的1.0.0.3 版本是什么效果？

**Comment by Lyn6969** [comment]
> 或者安装最新的1.0.0.3 版本是什么效果？

还是转圈，我换上面那个链接试试

**Comment by Lyn6969** [comment]
> 或者安装最新的1.0.0.3 版本是什么效果？

好吧1.0.0.3版本没没有设置这个的选项了。、、还是转圈

**Comment by Lyn6969** [comment]
大佬，修复了吗？为啥我这还是转圈

**Comment by l0o0** [comment]
> 大佬，修复了吗？为啥我这还是转圈

你是已经安装了1.0.0.4 这个版本么

**Comment by Lyn6969** [comment]
> > 大佬，修复了吗？为啥我这还是转圈
> 
> 你是已经安装了1.0.0.4 这个版本么

是的

**Comment by l0o0** [comment]
如果还是存在这个bug，可以试试卸载插件后，再重新安装。

**Comment by paoniu-liu** [comment]
> 我的好了
> 
> > > extensions.zotero.jasminum.translatorurl 设置为 https://oss.wwang.de/translators_CN ![图片](https://user-images.githubusercontent.com/2743744/260246603-6099d4c2-8b59-4fdd-9b20-7774b12dadd9.png) 你看看你的高级设置里是显示什么
> > 
> > 
> > 我的也是，都是最新版 ![image](https://user-images.githubusercontent.com/61086637/260291240-ae2d17ac-026e-4613-ab57-78a38f6caa63.png) ![image](https://user-images.githubusercontent.com/61086637/260291245-e3911274-0da8-4ee8-82fe-332f94bb8a09.png)
> 
> 我的好了，啥也没改

请问你哪个版本，我的重装也不好

**Comment by lychichem** [comment]
目前状况：

1. 卸载插件重装后无法恢复
2. 浏览器无法打开https://oss.wwang.de/translators_CN（报403），但能打开具体的js脚本链接
3. jasminum的“非官方维护中文转换器”一直转圈（推测是因为2）
总结：大佬你服务器nginx配置有问题，怀疑是只做了子目录的nginx反代，没做主目录的反代

**Comment by zhanghao1989** [comment]
<img width="748" alt="image" src="https://github.com/l0o0/jasminum/assets/85247974/2704e7e7-19ea-4c3c-87df-9f9b3fcfb05c">
<img width="744" alt="image" src="https://github.com/l0o0/jasminum/assets/85247974/d8babae3-a66b-41e4-8fc4-dccba2588137">

我的编辑器里没有可以输入网址的地方啊，而且插件里也没有显示网址，这是怎么回事啊？
