### ISSUE TITLE
茉莉花抓取失败，换了火狐，还是不行，插件卸载重装了又可以了，用一次又不行了，手动更换了知网的翻译器，再重新更新，又可以了，用一次又不行了。

### ISSUE THREAD

**Issue by sparksfly2000** [l0o0/jasminum#190]
(3)(+0046105): Setting debug.store to true

(3)(+0001054): Setting debug.store to false

(1)(+0022494): TypeError: _tabInfo[tab.id] is undefined

    Zotero.Connector_Browser</this.saveAsWebpage@moz-extension://a54722dc-85ea-4198-acd1-91ff833375c1/background.js:1018:7
    _browserAction@moz-extension://a54722dc-85ea-4198-acd1-91ff833375c1/background.js:987:30
    Zotero.Connector_Browser</logListenerErrors/<@moz-extension://a54722dc-85ea-4198-acd1-91ff833375c1/background.js:1050:32
    Zotero.Connector_Browser</waitForInit/<@moz-extension://a54722dc-85ea-4198-acd1-91ff833375c1/background.js:1071:14

**Comment by l0o0** [comment]
现在确认下问题
1. 茉莉花插件 PDF 文件 元数据识别失败？
2. 知网的Zotero Connector 抓取数据失败 ？

**Comment by sparksfly2000** [comment]
作者大大你好。
第二天就可以用了。
但是有时候有些抓不了pdf，只有条目，这个是一些文献本身的问题吗？
无法批量抓取，有时候是翻译器故障，有时候是只能抓caj，不过能单篇抓pdf对我来说就足够了，不过如果能解决就更好了。
谢谢。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月20日 20:38 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [l0o0/jasminum] 茉莉花抓取失败，换了火狐，还是不行，插件卸载重装了又可以了，用一次又不行了，手动更换了知网的翻译器，再重新更新，又可以了，用一次又不行了。 (Issue #190) |

现在确认下问题

茉莉花插件 PDF 文件 元数据识别失败？
知网的Zotero Connector 抓取数据失败 ？

**Comment by MrGongqi** [comment]
> 2. 知网的Zotero Connector 抓取数据失败
同上，并且在zotero中更新翻译器（同时也在浏览器插件Zotero Connector中更新了翻译器）后，没过多久zotero中的茉莉花插件中的非官方翻译器库又全部变成了感叹号。

**Comment by jiaojiaodubai** [comment]
浏览器抓取问题请到[Translators_CN](https://github.com/l0o0/translators_CN)反馈。
