### ISSUE TITLE
无法与zotero 7 Beta 35兼容

### ISSUE THREAD

**Issue by ZorkJ** [l0o0/jasminum#191]
你好，我现在使用zotero 7 Beta 35, 他说无法兼容，请问是什么原因啊

![image](https://github.com/l0o0/jasminum/assets/31822431/100350ef-e816-4a7e-babc-46767c96a715)

**Comment by FLIER001** [comment]
下载1.0.0-3 beta版本

**Comment by l0o0** [comment]
https://github.com/l0o0/jasminum/releases  到这里下载最新的
