### ISSUE TITLE
插件管理器中Jasminum 1.0.0-4 Pre-release的三点按钮下有方块

### ISSUE THREAD

**Issue by trarer** [l0o0/jasminum#195]
<img width="557" alt="截屏2023-08-21 22 36 57" src="https://github.com/l0o0/jasminum/assets/35182935/3ebf5b48-5695-41dc-9eda-63dc3f196818">

**Comment by l0o0** [comment]
> <img alt="截屏2023-08-21 22 36 57" width="557" src="https://user-images.githubusercontent.com/35182935/262056268-3ebf5b48-5695-41dc-9eda-63dc3f196818.png">

谢谢同学的回复，不过这个应该是zotero 的问题。不是jasminum的问题

**Comment by trarer** [comment]
但是我只看到jasminum这个的插件在zotero存在这个问题

**Comment by l0o0** [comment]
> 

我这边没有复现你提到的那个问题，你是安装的哪个版本？

**Comment by trarer** [comment]
zotero 7.0.0-beta.36+3ef1f0992，插件的每个版本都有，看起来是macOS的开启HiDPI才有的问题，当采用LoDPI这些问题就消失了。
![截屏2023-08-24 09 05 04](https://github.com/l0o0/jasminum/assets/35182935/6772e9a8-c869-450a-82c3-fb35f0c533e7)
<img width="782" alt="截屏2023-08-24 09 04 48" src="https://github.com/l0o0/jasminum/assets/35182935/cabf0b77-f6b1-4c7f-b12c-54c82a2eef1e">
