### ISSUE TITLE
zotero 7 抓取知乎回答网页失败 #Bug

### ISSUE THREAD

**Issue by lenken012** [l0o0/jasminum#196]
<img width="1420" alt="1" src="https://github.com/l0o0/jasminum/assets/141751384/b0e29eb0-ab25-4f07-a1de-5d11e77cab6a">
<img width="1523" alt="2" src="https://github.com/l0o0/jasminum/assets/141751384/6ae267e1-83e9-4ea7-9f7e-87ff2e0e4b3b">

## 问题描述: 
Zotero 7抓取知乎答案页面，ZZotero connecter抓取框抓取的内容一直为灰色，并且在Zotero里不显示抓取的内容。

## 设备信息:
1. Zotero 7 version: 7.0.0-beta.36+3ef1f0992
2. Jasminum version: 1.0.0-3
3. Zhihu Chinese converter version: 2023-04-03 06:43:09
4. Computer type: Macbook Pro M1; macos 13.3.1 (22E261)

**Comment by jiaojiaodubai** [comment]
浏览器抓取问题请到[Translators_CN](https://github.com/l0o0/translators_CN)反馈。
