### ISSUE TITLE
中文转换器无法更新

### ISSUE THREAD

**Issue by lychichem** [l0o0/jasminum#197]
![image](https://github.com/l0o0/jasminum/assets/9316590/37824ace-0059-48fd-9b93-2b2385fb66fe)
如图，始终显示加载中，测试了一下，代码中定义的translator更新链接（https://oss.wwang.de/translators_CN/ ）在浏览器中报403。建议修改链接。怀疑应该是作者你嫖的azure到期了（

**Comment by yzy1228682367** [comment]
https://github.com/l0o0/jasminum/issues/188
已解决。

**Comment by lychichem** [comment]
> [https://github.com/l0o0/jasminum/issues/188已解决。](https://github.com/l0o0/jasminum/issues/188%E5%B7%B2%E8%A7%A3%E5%86%B3%E3%80%82) 或者下载最新报的zotero7插件。

没有解决问题，那个issue也应该重开。问题的关键是作者自己的站403了，这个只能作者改服务器配置。 @l0o0

**Comment by yzy1228682367** [comment]
我按照#188改后正常了耶，
![CleanShot 2023-08-25 at 20 00 20@2x](https://github.com/l0o0/jasminum/assets/50101175/67e6d606-8c92-447a-9ec5-e4bde207af59)

**Comment by zhanghao1989** [comment]
作者，我现在装的是1.0.0-3版本，1.0.0-4没有xpi，不会装，也不知道怎么更新。现在我也面临这样的问题，中文转换器一直在转圈，更新不了
