### ISSUE TITLE
1.0.0-4如何更新啊？

### ISSUE THREAD

**Issue by zhanghao1989** [l0o0/jasminum#198]

**Comment by yzy1228682367** [comment]
pre-lease 针对的是zotero7

**Comment by zhanghao1989** [comment]
我知道是zotero7的，我就是要装在7上面的，我现在装的是1.0.0-3，但是1.0.0-4没有xpi，我不知道如何才能更新，有人做出来xpi了么？

**Comment by yzy1228682367** [comment]
zotero里面点击更新试试。

**Comment by zhanghao1989** [comment]
点击过了，什么反应都没有
<img width="542" alt="image" src="https://github.com/l0o0/jasminum/assets/85247974/47312b1c-4790-4481-9834-5adc21f8775f">
这个插件最下面也没有网址

**Comment by l0o0** [comment]
可以直接到 www.zotero-chinese.com 上面的插件市场进行下载
