### ISSUE TITLE
抓取到的「卷」和「期」的值混在一起

### ISSUE THREAD

**Issue by xiaocrab** [l0o0/jasminum#2]
OS 版本:：macOS 10.15.6
Zotero 版本：5.0.89
插件版本：0.0.2

**抓取到的「卷」和「期」的值会混在一起。**
比如：
文章是**第19卷第5期**，那么识别出来的结果是。
```
卷：
期：05 vo 19
```
正确的结果应该是。
```
卷：19
期：05
```

**Comment by l0o0** [comment]
同学，麻烦把文献链接给我，我去测试下 @xiaocrab

**Comment by xiaocrab** [comment]
我这里，只要是同时有「卷」和「期」值的，都会有这个问题。
比如这个：https://kns.cnki.net/KCMS/detail/detail.aspx?dbcode=CJFQ&dbname=CJFDLAST2020&filename=COKE202008007&v=MDc1NDZxZmIrWnBGeS9rVXJ6QUppTEFhN0c0SE5ITXA0OUZZNFI4ZVgxTHV4WVM3RGgxVDNxVHJXTTFGckNVUjc=

**Comment by l0o0** [comment]
@xiaocrab 好的，我找到原因了。我等下就更新

**Comment by l0o0** [comment]
@xiaocrab 麻烦更新下插件，再试试看

**Comment by xiaocrab** [comment]
现在已经正常了。

但是发现新版插件的一个问题：首选项-->茉莉花 的图标有点大。
<img width="867" src="https://user-images.githubusercontent.com/10709715/89517756-c4bab900-d80c-11ea-93a3-b4594491111f.png">
