### ISSUE TITLE
功能改进：对扩展自动更新的支持

### ISSUE THREAD

**Issue by lychichem** [l0o0/jasminum#20]
首先感谢您能制作此扩展，在此先谢谢您的付出
提一个小建议：在项目中加入update.rdf，并在install.rdf中使用updateURL引用此文件可以实现扩展在用户端的自动更新，便于用户始终使用最新版本。关于此文件的写法可以参考firefox扩展的开发指南，或者我[这里](https://github.com/lychichem/zotfile/blob/master/zotfile-update.rdf)有个写好的样本。当然，每次扩展更新时需要同步更新update.rdf中引用的下载链接

**Comment by l0o0** [comment]
非常感谢你的建议，之前我也想添加，一直还没研究如何添加。有幸有你的帮助！

**Comment by lychichem** [comment]
另外，今早更新了zotero 5.0.92之后pdf添加书签的功能似乎炸了……黑框都弹不出来……

**Comment by lychichem** [comment]
#21 应该能用（链接用的前辈的库，理论上直接merge就能用）

**Comment by l0o0** [comment]
@lychichem 谢谢同学，我下个版本会加的^-^

**Comment by lychichem** [comment]
emm下了最新版xpi发现打包的时候前辈多打了一个文件，update.rdf不需要打包进xpi里的~

**Comment by l0o0** [comment]
哈哈，失误失误。忘了排除了
