### ISSUE TITLE
浏览器中无法抓取知网PDF，且点击下载PDF出现“系统错误（0105）”页面

### ISSUE THREAD

**Issue by menglei125** [l0o0/jasminum#201]
请问，校园网内（学校已购买知网数据库），从Zotero的目录，能直接链接到知网，但不能抓取PDF。从zotero条目进入知网，出现下面这个图标，点完成，但并不能将PDF及题目抓取到Zotero里。
![b84c4fc617de9e7b392ddf8b01065ab](https://github.com/l0o0/jasminum/assets/85054498/fa2aac48-e7a3-40e3-ac6a-6366ac12a314)

如果在上面这个页面中，点击下面的下载PDF下载，则会出现下面这个网页。显示：系统错误。
![image](https://github.com/l0o0/jasminum/assets/85054498/9f18dad4-33ef-4da0-81b8-abe6609a9cb3)

但如果直接从CNKI进入，输入同一篇文献的标题，则可以直接下载PDF。

请问，这个问题要怎么解决呢？试了Zotero，以及Connector中的更新翻译器，但都不管用。实在不知道要怎么解决，还请帮帮忙，谢谢！

**Comment by jiaojiaodubai** [comment]
学校的 VPN 重定向本身有问题，联系管理员解决。
