### ISSUE TITLE
> 2. 知网的Zotero Connector 抓取数据失败

### ISSUE THREAD

**Issue by zhanglin199912** [l0o0/jasminum#202]
> 2. 知网的Zotero Connector 抓取数据失败
同上，并且在zotero中更新翻译器（同时也在浏览器插件Zotero Connector中更新了翻译器）后，没过多久zotero中的茉莉花插件中的非官方翻译器库又全部变成了感叹号。

_Originally posted by @MrGongqi in https://github.com/l0o0/jasminum/issues/190#issuecomment-1708539868_

**Comment by jiaojiaodubai** [comment]
检查是否错误地将 translator 设置为同步文件夹。
