### ISSUE TITLE
与新版本不兼容

### ISSUE THREAD

**Issue by glittercreeks** [l0o0/jasminum#203]
无法加入插件，显示无法与该版本兼容
![image](https://github.com/l0o0/jasminum/assets/144643054/408f7262-eb3c-4e69-8d4d-3cb13e02505f)

**Comment by yzy1228682367** [comment]
选择release的，prerelease都只针对zotero 7 发布。

**Comment by tangdoupapa** [comment]
![image](https://github.com/l0o0/jasminum/assets/22194156/f70caf53-7aa7-44ee-9fca-27173bcb859b)
 使用最新版1.0.0-6提示不兼容，zotero版本如下
![image](https://github.com/l0o0/jasminum/assets/22194156/79d59af2-909a-4c3c-8bc2-07a327293ace)

**Comment by yzy1228682367** [comment]
zotero 6 选择 release

**Comment by l0o0** [comment]
> 请问7的prerelease版本怎么找到

@FromNature 如果找不到，可以直接到 https://plugins.zotero-chinese.com/ 下载。

GitHub上可以点击右侧的Releases ，就可以看到所有的版本了，你还可以在左上角的Release 那里进行过滤
![图片](https://github.com/l0o0/jasminum/assets/2743744/bb5cf81a-4487-42b0-ba78-cd5d90a88482)
