### ISSUE TITLE
PDFtk不能安装在D盘么？

### ISSUE THREAD

**Issue by zhanghao1989** [l0o0/jasminum#205]
<img width="718" alt="222" src="https://github.com/l0o0/jasminum/assets/85247974/e5bc00b0-77ad-41d9-a2b0-db2f51c85a9f">

<img width="718" alt="222" src="https://github.com/l0o0/jasminum/assets/85247974/60dfe77d-519c-4692-927d-560d9a4dc332">

这个PDFtk只能装在C盘么？
我装在D盘里，路径没有问题，刚开始也是打绿色勾的，但是重启zotero后就变成红色的感叹号了，是因为不能装在D盘里么？

**Comment by zhanghao1989** [comment]
<img width="614" alt="111" src="https://github.com/l0o0/jasminum/assets/85247974/df408201-0067-4f0b-888e-616e03bb7efe">

**Comment by l0o0** [comment]
麻烦截图一下，D盘里的安装文件

**Comment by l0o0** [comment]
@zhanghao1989 是下载的软件不对，参考这个 https://github.com/l0o0/jasminum/issues/223
