### ISSUE TITLE
在terminal 输入pdftk 但是没办法说是安装了

### ISSUE THREAD

**Issue by Yangxiaoxi99** [l0o0/jasminum#208]

**Comment by Yangxiaoxi99** [comment]
/opt/homebrew/bin/pdftk: line 3: /Users/yangxi/@@HOMEBREW_JAVA@@/bin/java: No such file or directory
/opt/homebrew/bin/pdftk: line 3: exec: /Users/yangxi/@@HOMEBREW_JAVA@@/bin/java: cannot execute: No such file or directory 出现这样子是为什么

**Comment by l0o0** [comment]
这个可能是pdftk安装问题？

**Comment by jiaojiaodubai** [comment]
未找到 JAVA 运行时的目录，请检查设置。
