### ISSUE TITLE
茉莉花插件 非官方维护中文翻译器 界面空白

### ISSUE THREAD

**Issue by pychus** [l0o0/jasminum#209]
Mac Air M2;
macOS sonoma 14.0
![image](https://github.com/l0o0/jasminum/assets/45301965/e8d93cc1-cd74-48d8-8001-7772f0131c2c)

**Comment by pychus** [comment]
jasminum-0.1.6
PDFtk 路径设置出现和issue#208一样的错误提示

**Comment by l0o0** [comment]
插件版本有些低，建议更新到最新版本，现在zotero 6 的版本号最新是0.2.7


pychus ***@***.***> 于2023年10月27日周五 18:10写道：

**Comment by jiaojiaodubai** [comment]
@l0o0 
一个用户说他用茉莉花更新翻译器后右边弹窗显示下载成功，但“本地更新时间”那一列始终是“--”(不显示时间)，而且翻译器也不能用，我在他的翻译器目录拿到了两个样本，看内容似乎意外地保存了下载源的错误页？希望对你有帮助。

然后我还遇到一个案例是用户在配置坚果云同步的时候，误把`translator`文件夹加入到同步目录里了，茉莉花更新翻译器后，新翻译器被坚果云一直占用文件进行同步，就没法在Connector里面更新（debug log显示更新的翻译器只有710个左右，正常情况下官方仓库+国内仓库的翻译器应该是750以上）。

[sample.zip](https://github.com/l0o0/jasminum/files/13656926/sample.zip)

**Comment by jiaojiaodubai** [comment]
> @l0o0 一个用户说他用茉莉花更新翻译器后右边弹窗显示下载成功，但“本地更新时间”那一列始终是“--”(不显示时间)，而且翻译器也不能用，我在他的翻译器目录拿到了两个样本，看内容似乎意外地保存了下载源的错误页？希望对你有帮助。
> 
> [sample.zip](https://github.com/l0o0/jasminum/files/13656926/sample.zip)

已解决，旧版茉莉花的问题。

**Comment by jiaojiaodubai** [comment]
同 #267
