### ISSUE TITLE
软件和网页更新完翻译器，知网还是不能批量抓取

### ISSUE THREAD

**Issue by Mradusa** [l0o0/jasminum#210]
zotero connet变不了文件夹，只能在论文页面单篇抓取。

**Comment by Mradusa** [comment]
JavaScript Error: "Failed to retrieve translators from Zotero Repo Error: HTTP request to https://repo.zotero.org/repo/metadata?version=5.0.114&last=0 rejected with status 0" {file: "chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/zotero.js" line: 306}]

**Comment by yzy1228682367** [comment]
有相同问题。

**Comment by Chikit-L** [comment]
请放弃批量抓取

**Comment by jiaojiaodubai** [comment]
浏览器抓取问题请到[Translators_CN](https://github.com/l0o0/translators_CN)反馈。

知网转换器已经支持多条目页面，多条目页面有时不能响应，和脚本加载时机有关。
