### ISSUE TITLE
你们还能抓取知网的数据吗？

### ISSUE THREAD

**Issue by AllenJHawk** [l0o0/jasminum#215]
最近需要引文，发现抓取不了知网的文献信息了，┭┮﹏┭┮

**Comment by derrickzhuyz** [comment]
我最近也发现不行了

**Comment by derrickzhuyz** [comment]
我最近也发现不行了，网上很多解决方法都试过了还是不行 :(

**Comment by yzy1228682367** [comment]
确实抓不了知网的数据了

**Comment by wangbofan** [comment]
对，我这里无法抓取了

**Comment by l0o0** [comment]
已经更新了同学们

**Comment by AvenirEnigme** [comment]
开发者打扰了，反馈一下。最近三四天似乎都无法抓取知网数据（0.2.8）知网翻译器更新了，浏览器扩展里也update translator了。显示“使用CNKI时发生错误”只能保存网页快照

**Comment by AvenirEnigme** [comment]
反馈哈，貌似问题被解决了，今天可以抓取metadata和下载附件了。总之很感谢开发者
