### ISSUE TITLE
2023.11抓取知网元数据貌似无法使用

### ISSUE THREAD

**Issue by derrickzhuyz** [l0o0/jasminum#217]
“右键-知网助手-抓取知网元数据”的方式抓取中文文献的元数据后没有反应，没有成功抓取也没有失败弹窗。
网上的方法基本试过一遍例如更新translator，重装插件等均无法解决。是否是知网增加了反抓取的机制呢？

**Comment by Charagol** [comment]
2023.11.18同样问题，搜了很多办法，也改了文件名模板格式，都失败了。具体表现就是“右键-知网助手-抓取元数据”完全无反应

**Comment by Kosmos0516** [comment]
我也是刚发现这样了，没什么办法

**Comment by feixiangqian** [comment]
我也遇到同样问题了

**Comment by wangbofan** [comment]
使用 CNKI 保存时发生错误。改为尝试用 Save as Webpage 保存。
[JavaScript Error: "HTTP request to http://127.0.0.1:23119/connector/getTranslatorCode has timed out after 15000ms" {file: "chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/zotero.js" line: 306}]

[JavaScript Error: "HTTP request to http://127.0.0.1:23119/connector/getTranslatorCode has timed out after 15000ms" {file: "chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/zotero.js" line: 306}]

[JavaScript Error: "HTTP request to http://127.0.0.1:23119/connector/getTranslatorCode has timed out after 15000ms" {file: "chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/zotero.js" line: 306}]

[JavaScript Error: "HTTP request to https://kns.cnki.net/KNS8/manage/ShowExport?filename=GDGX20231116001&displaymode=Refworks&orderparam=0&ordertype=desc&selectfield=&dbname=CAPJLAST&random=0.2111567532240084 rejected with status 0" {file: "chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/zotero.js" line: 306}]
我用的是最新版的zotero7,插件完全无法爬取，CNKI.JS我也重新下载了，完全没用！！

**Comment by yuhanwsy** [comment]
知网应该是更新了反抓取机制。我的也不行了，试了各种方法都不行。还有比知网更无耻的公司吗，答案是没有

**Comment by cp-Aurora** [comment]
抓不了了，怎么办呀...

**Comment by ChansLy** [comment]
好崩溃emm

**Comment by MrGongqi** [comment]
我也是抓取不了了，抓取文件信息应该不至于会被反制啊，又不是盗取文件。倍感无力。
[JavaScript Error: "HTTP POST https://kns.cnki.net/KNS8/manage/ShowExport failed with status code 0" {file: "chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/zotero.js" line: 306}]

[JavaScript Error: "HTTP POST https://kns.cnki.net/KNS8/manage/ShowExport failed with status code 0" {file: "chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/zotero.js" line: 306}]

**Comment by MrGongqi** [comment]
> 我也是抓取不了了，抓取文件信息应该不至于会被反制啊，又不是盗取文件。倍感无力。 [JavaScript Error: "HTTP POST https://kns.cnki.net/KNS8/manage/ShowExport failed with status code 0" {file: "chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/zotero.js" line: 306}]
> 
> [JavaScript Error: "HTTP POST https://kns.cnki.net/KNS8/manage/ShowExport failed with status code 0" {file: "chrome-extension://nmhdhpibnnopknkmonacoephklnflpho/zotero.js" line: 306}]
知网真的是让人气不过，不想着融会贯通，老是搞一些闭源自封的下三滥

**Comment by Sylvie-Laufeydottir** [comment]
watching 非常关注, 有任何release, 请comment下, 谢谢 @l0o0

**Comment by tancheng1999** [comment]
11/19我快疯了，弄了半个上午加中午，加下午，zotero就是爬取不了知网文献，什么方法都试了一遍，哎，就是知网不行，万方都可以。

**Comment by Charagol** [comment]
> 11/19我快疯了，弄了半个上午加中午，加下午，zotero就是爬取不了知网文献，什么方法都试了一遍，哎，就是知网不行，万方都可以。

我Zotero connecter还坏了，平时就靠Jasminum来导入，昨天也是捣鼓了一晚上没用，算了只能等了

**Comment by hdeuhda** [comment]
我也是，好烦那

**Comment by H-wong017** [comment]
> > 11/19我快疯了，弄了半个上午加中午，加下午，zotero就是爬取不了知网文献，什么方法都试了一遍，哎，就是知网不行，万方都可以。
> 
> 我Zotero connecter还坏了，平时就靠Jasminum来导入，昨天也是捣鼓了一晚上没用，算了只能等了

暂时用某度学术，某歌学术顶一下，可以抓到条目信息

**Comment by Fantasitao** [comment]
我也是 我还以为是没更新的问题

**Comment by John-Cohen0714** [comment]
23.11.19, 确实不能抓取元数据，更新了翻译器、重新装载jasminum、重装connector，都试过了，大概率是知网改版，translator还没跟上。

**Comment by kiencity** [comment]
同样的问题，无法抓取

**Comment by MikeCheng111** [comment]
一般多久才能修复好啊？

**Comment by at-ease** [comment]
zotero7同样问题，不知道zotero6用起来正常吗

**Comment by amommm** [comment]
辛苦开发者，希望能早点修复

**Comment by tree2547** [comment]
到期末了，希望开发者早点修复

**Comment by Siiiiiigma** [comment]
我也是，从18号开始就一直不能抓取了

**Comment by deapAIRilliteracy** [comment]
网上有的方法都试了还是不行，有劳开发者了

**Comment by yuhuangniu** [comment]
刚刚更新了最新（11月19日新发布的）的CNKI translator，还是无法抓取知网文献，麻烦开发者大大尽快修复

**Comment by yfdyh000** [comment]
https://github.com/l0o0/translators_CN/pull/233 的代码试一下。如有问题，说一下哪个页面上异常。

**Comment by a515006420** [comment]
同问，下载的pdf，点击知网助手-抓取知网元数据，毫无反应

**Comment by a515006420** [comment]
> [l0o0/translators_CN#233](https://github.com/l0o0/translators_CN/pull/233) 的代码试一下。如有问题，说一下哪个页面上异常。
用了更新的CNKI.js,也更新了translator，重新安装更新了所有插件，下载的pdf，点击知网助手-抓取知网元数据，还是毫无反应

**Comment by a515006420** [comment]
> > [l0o0/translators_CN#233](https://github.com/l0o0/translators_CN/pull/233) 的代码试一下。如有问题，说一下哪个页面上异常。
> > 用了更新的CNKI.js,也更新了translator，重新安装更新了所有插件，下载的pdf，点击知网助手-抓取知网元数据，还是毫无反应

是Mac版本的，开发者大大辛苦了

**Comment by myriad2** [comment]
折腾了好久，才发现是知网的锅，改用万方了

**Comment by fredericky123** [comment]
waching

**Comment by beifangrenliluo** [comment]
> “右键-知网助手-抓取知网元数据”的方式抓取中文文献的元数据后没有反应，没有成功抓取也没有失败弹窗。 网上的方法基本试过一遍例如更新translator，重装插件等均无法解决。是否是知网增加了反抓取的机制呢？

俺也一样

**Comment by lishuiwkp** [comment]
网页版本无法使用，而且下载PDF后拖拽至zotero也无法抓取元数据，辛苦开发者了~

**Comment by laura-Deng** [comment]
请问我现在用的zotero7，遇到问题是：
1. cnki挂着学校vpn的情况下无法抓取（爱斯威尔可以）
2. 知网助手无反应
3. 元数据抓取失败
4. 用doi手动创建父条目无法识别
（但是既然爱斯维尔能用，说明应该还是知网的问题）

目前做过的尝试都没得卵用：
1. translator 更新+浏览器更新+重启
2. 替换translator 里的cnki文件

会不会跟zotfile不能用有关

**Comment by ralphcyf1997** [comment]
试试科学上网的方式，前几天也不抓不到元数据，今天忘关了突然就能抓了

**Comment by laura-Deng** [comment]
> 试试科学上网的方式，前几天也不抓不到元数据，今天忘关了突然就能抓了

一直挂着科学上网
在某书上发现昨天晚上开发大佬连夜更新
我今天更新完了能用知网助手功能，但cnki抓取的时候还是不显示PDF选项🥹

**Comment by Sylvie-Laufeydottir** [comment]
hi @l0o0, @yfdyh000,
11.23, 用浏览器插件保存知网的PDF依然失效, 其次, 在zotero中获取知网元数据无任何跟信息
用开发者工具看了下, 没有发现有失败的http请求
有任何进度, 或者更新进展分享下吗, 谢谢

**Comment by l0o0** [comment]
@Sylvie-Laufeydottir 知网转换器和茉莉花都已经更新了呢。

如果是使用知网转换器，请及时手动更新知网转换器，官方那边也已经提交并合并了https://github.com/zotero/translators/pull/3191#event-11043975058

如果是插件，请升级到最新版本即可，注意区分6和7版本

**Comment by Sylvie-Laufeydottir** [comment]
> @Sylvie-Laufeydottir 知网转换器和茉莉花都已经更新了呢。
> 
> 如果是使用知网转换器，请及时手动更新知网转换器，官方那边也已经提交并合并了[zotero/translators#3191 (comment)](https://github.com/zotero/translators/pull/3191#event-11043975058)
> 
> 如果是插件，请升级到最新版本即可，注意区分6和7版本

非常感谢, 我在试一下, 更新辛苦啦, 比心 ❤️

**Comment by derrickzhuyz** [comment]
茉莉花插件更新后已经可以使用。感谢开发者的努力！
The jasminum plugin is now working properly after the update. Thanks to the developers for their efforts!

**Comment by derrickzhuyz** [comment]
茉莉花插件更新后已经可以使用。感谢开发者的努力！
The jasminum plugin is now working properly after the update. Thanks to the developers for their efforts!

**Comment by hezhenwang** [comment]
我也是同样的情况

**Comment by pilifengmo** [comment]
目前仍旧无法使用
