### ISSUE TITLE
最新版本（Release 1.0.0-8）插件仍然不能抓取知网元数据

### ISSUE THREAD

**Issue by akoq1205** [l0o0/jasminum#219]
zotero7安装了最新版本（Release 1.0.0-8）插件后仍然不能抓取知网元数据，显示 使用 CNKI 保存时发生错误。改为尝试用 Save as Webpage 保存。

**Comment by zzyskty** [comment]
zotero6更新了翻译器，但右上角提示保存此条目时发生错误。查看 [翻译器故障排除](https://www.zotero.org/support/troubleshooting_translator_issues) 获取更多信息。

**Comment by akoq1205** [comment]
搜了一下还需要在设置中更新翻译器，zotero7更新翻译器后知网已经可以正常抓取了

**Comment by l0o0** [comment]
你们有没有更新转换器，浏览器里也要及时更新

**Comment by zzyskty** [comment]
非常感谢作者你的来信，我再次尝试一下，真的很感谢你无私的分享，大佬受我一拜




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "l0o0/jasminum"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月23日(星期四) 下午3:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [l0o0/jasminum] zotero7安装最新版本（Release 1.0.0-8）插件仍然不能抓取知网元数据 (Issue #219)





 
你们有没有更新转换器，浏览器里也要及时更新
