### ISSUE TITLE
海外版下载硕博论文的pdf文件名变了，无法顺利识别meta信息（3个功能建议）

### ISSUE THREAD

**Issue by ghweili** [l0o0/jasminum#22]
由于zotero只能打开pdf无法打开caj等，我倾向于在海外版知网一篇篇点击下载按钮，然后批量导入。前两周还没有问题，但刚才测试发现题目被改为英文了，类似于 Structural Confi_省略__type Tensegrity_陆游.pdf （测试中硕博论文的标题都变了，但论文期刊好像标题没有变过）。 

1. 如果我们从海外版下载pdf并进行匹配，我觉得目前仅根据题目的匹配方式还可以进一步改进，不清楚有没有可能在必要时从pdf内部读取到title等， （无论是pdf的meta信息还是全文的内容）？如果没有办法的话，有没有可能根据上述格式的标题格式进行匹配？至少对于硕博论文这种，在给定对应规则后应该还是挺容易匹配成功的。

2. 从海外版下载，还有另外一个办法。我注意到至少当前（201017）在海外版的zotero connector是可以使用的 （奇怪的是国内版反而不行），因此，可以把那些条目都批量导入，但无法顺利查找到全文。此时必须一篇篇点击下载。那在都下载好以后，Jasminum有没有可能在指定特定存储pdf的文件夹以后，根据当前zotero collection里的条目以及该文件夹内的文件题目，进行匹配，这样就不必一篇篇手动进行匹配。考虑到知网经常变来变去，这个方案也许比1更加稳定，不过这也取决于zotero connector是否能顺利批量导入。 算是一个1的备用方案。

3. 实在不行还有一个办法就是利用知网研学先批量下载下来。对于这类，他们的pdf标题好像仅包含文章标题（硕博论文不清楚），对于这类仅含有标题的pdf，希望插件也能帮助其找到meta信息。 不过利用知网研学的批量下载功能，貌似对于硕博论文还是说博士论文，依然仅能下载到caj。 

最后，关于一篇篇点击下载pdf，不知道有没有更高效的方法，希望有更好办法的朋友提供建议。

对于知网不为国内用户提供方便的pdf下载功能表示深深的鄙视；另外zotero connector的不定期失效也不知道与知网方面是否有关系。下载文献是为了做学术研究，希望我们能自由的选择我们用的惯的文献管理软件，让研究者把精力集中在更重要的事情上。本身知网研学的功能也挺强，有他的用户，但有用户选择使用其他软件必然是有一些他们需要的功能而在这些方面知网研学不够方便。希望不要为了为其提高用户量而用这种方式强行为其他软件用户造成困难，这是一种无畏的内耗，与分享知识的初衷相悖。

**Comment by l0o0** [comment]
1. 如果从知网海外版下载的文件，文件名是英文的，不过因为下载的文件名长度是有限制的，文件名里面可能只有几个单词，靠这几个单词去搜索，可能准确性比较低。如果文件名中title 信息比较少，也不能从PDF中读到文章的title  

2. 知网最近改版了，如果海外版有问题，可以反馈下，我修改下cnkijs

3. 对于仅有文章标题的pdf，你可以去jasminum的设置页面，调整下识别的格式，设置成{%t}就行

对于有条件使用知网的，建议还是直接使用CNKI.js来获取比较方便。Jasminum 只是实在没有办法的辅助

**Comment by ghweili** [comment]
1. 目前海外版还可以正常使用zotero connector导入条目。
2. 关于仅用pdf来匹配的方式，的确可以，这个挺方便的。不过有没有可能让设置里设置多种匹配方式，按照优先级，比如先按照title+fullauthor等方式，然后若不成功（比如检测title里不包含下划线等方式）再尝试用第二种匹配方式？
3. 关于第一点，貌似期刊论文下载时中文的题目_作者，且可以用Jasmium顺利找到，而硕博论文貌似前两周也是这样的，但最近变成上述情况了。
   的确纯粹的去利用那些关键字在知网里搜索匹配很不准确，但有没有可能我们首先在知网上通过zotero connector把条目导入进zotero，并手动一篇篇下载pdf到本地，然后让Jasmium有办法读取本地的特定文件夹，并从这里面去挑选pdf与所选定的若干条目去进行匹配，并把匹配到的pdf 添加为对应条目的附件？ 这样的话匹配率应该可以保证，就是不知道是否容易实现。
4. 关于你说的使用CNKI.js 来获取，是指的我再3里边提到的这种方式，把条目利用zotero connector导入吗？这个是没有问题，就是没办法查找全文，必须把手动下载的pdf一篇篇手动匹配起来，这也是我提第三点的原因，如果能利用插件实现匹配并添加到附件的话那会方便不少。 
   如果这个难度较大的话，还有一个方案是让我们手动把pdf也拖动到该colletion，这样collection里既有若干条目，也有若干pdf附件。剩下的问题就是匹配以及把pdf的条目变成对应条目的附件。 这也会很大的减轻一条条匹配的工作量。

**Comment by ghweili** [comment]
另外有一个小建议：关于仅用title来匹配的方式，若某个条目搜索到多个潜在可能的匹配时，会弹出对话框让选择哪个，包括全选。针对这种少量的情况，大部分情况下我们事先并不知道该选哪个，而此时我发现无法切换到zotero窗口去查看应该选哪个，所以我倾向于选全选那个选项，但此时好像依然只会导入一个；另外，如果两个都不选，则好像会停止匹配，包括剩余的条目。 另外建议考虑对这类存疑的可以自动添加一个tag，好方便知道要着重关注哪些条目是否有问题。

**Comment by l0o0** [comment]
那个是我设定了，只能选择一个。一般尽量使用作者加标题的形式提升搜索的准确。如果全选的话，其实也没必要，因为在选择页面，已经出现作者和标题的信息。这些可以在全文中有的

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ghweili** [comment]
一般情况下是没问题，不过有时我们可能一次性导入20来个pdf，那此时我们可能无法提前为每个pdf都查看其作者，也记不住，而当某个条目在弹出上述选择框的时候，我们无法切换回zotero的界面去查看pdf，所以无法查看到底应该下载哪个，此时我只能随便下一个条目，此时就无法保证是正确的。那个弹出框的时候无法选中zotero界面，这个如果可以改进的话那也能解决这个问题。

另外除了上述内容，我还有另外一条回复，不知道您看到了没有，我附在下面：

目前海外版还可以正常使用zotero connector导入条目。
关于仅用pdf来匹配的方式，的确可以，这个挺方便的。不过有没有可能让设置里设置多种匹配方式，按照优先级，比如先按照title+fullauthor等方式，然后若不成功（比如检测title里不包含下划线等方式）再尝试用第二种匹配方式？
关于第一点，貌似期刊论文下载时中文的题目_作者，且可以用Jasmium顺利找到，而硕博论文貌似前两周也是这样的，但最近变成上述情况了。
的确纯粹的去利用那些关键字在知网里搜索匹配很不准确，但有没有可能我们首先在知网上通过zotero connector把条目导入进zotero，并手动一篇篇下载pdf到本地，然后让Jasmium有办法读取本地的特定文件夹，并从这里面去挑选pdf与所选定的若干条目去进行匹配，并把匹配到的pdf 添加为对应条目的附件？ 这样的话匹配率应该可以保证，就是不知道是否容易实现。
关于你说的使用CNKI.js 来获取，是指的我再3里边提到的这种方式，把条目利用zotero connector导入吗？这个是没有问题，就是没办法查找全文，必须把手动下载的pdf一篇篇手动匹配起来，这也是我提第三点的原因，如果能利用插件实现匹配并添加到附件的话那会方便不少。
如果这个难度较大的话，还有一个方案是让我们手动把pdf也拖动到该colletion，这样collection里既有若干条目，也有若干pdf附件。剩下的问题就是匹配以及把pdf的条目变成对应条目的附件。 这也会很大的减轻一条条匹配的工作量。

**Comment by l0o0** [comment]
1. 目前我在想着怎么修改那个文件名匹配的方式，如果文件名没有下划线会直接认为是title。
2. 如果出现多选框，你选中多个的时候，可以让你保留多个条目，不过附件我想着先不移动，需要用户手动移到对应的条目里。

上面是我的想法。然后如果你使用知网海外版，应该也可以在收集条目信息的时候，同时下载PDF附件的。你那边实现不了么？

**Comment by ghweili** [comment]
1. 关于“如果出现多选框，你选中多个的时候，可以让你保留多个条目，不过附件我想着先不移动，需要用户手动移到对应的条目里”，目前好像还不是这样的，我全选时还是只会导入一个，好像是第一个。其实最好以及简单的办法是让这个多选框与zotero的界面可以互相切换，这样就可以回到zotero界面查看一下pdf的信息，到底是对应哪个，然后再回到弹出框这里选择。目前是弹出后就无法再切换回去。这个功能应该比较可以实现吧？
另外如果可能的话， 上述全选功能还是建议完善一下，比如我有次搜索一个标题，出来两个，而另外一个我看题目也挺感兴趣，可能就也想导入就来。至于pdf 附件，这个不太关键，这种少量的自己手动拖一下也不算麻烦。

2. 目前国内知网与海外知网利用zotero connector：前几天时海外知网可以利用，而国内版仅能保存网页，而刚刚我的测试，对于国内知网，当切换到特定类型，比如 硕士、博士或期刊论文后，可以利用zotero connector批量导入条目，而海外版又意外的都不能用了，仅能保存网页。搞不懂知网怎么会这么频繁的变动

3. 刚才测试了利用国内知网导入条目后是否自动下载附件，试了硕博论文和期刊，都没有自动导入。而find available PDF 也不生效。 印象里好像我以前无论是用国内还是海外版的，都没有办法直接自动下载附件。即使我再校园网环境下，知网右上角在chrome里直接显示某某大学登陆。

4. 不知道这个与我的extensions.zotero.findPDFs.resolvers 里的设置有关吗？我曾把这里改为了用scihub来查找全文。不过即使我把这里改回[]依然不行。

5. 另外不知道查找全文有没有办法设置成优先使用校园网查找、没有的话再到scihub上搜索，不知道您知道这个事情吗？

总结而言，我这里核心的问题是不知什么原因一直无法自动下载pdf或caj，不知道是不是个案。

**Comment by l0o0** [comment]
1. 多选框那个代码我是直接调用 Zotero 原有的窗口，估计修改不了。还有就是如果一个PDF出现多个搜索条目，我会在后面将应该会买PDF与这多个条目进行关联，方便查找

2. 这个CNKI.js 正常是能下载PDF附件（也可以设置成CAJ）。同学你是不是没有更新CNKI.js或者哪里没设置好。要不要加群913637964 讨论下

**Comment by l0o0** [comment]
@ghweili 多个结果的下载，已经补上了，到时候记得更新下插件
