### ISSUE TITLE
1.0.0-8版本从网页条目中抓取知网元数据失败

### ISSUE THREAD

**Issue by jhhj7148** [l0o0/jasminum#221]
![Snipaste_2023-11-21_22-44-58](https://github.com/l0o0/jasminum/assets/136339264/a7549985-4c65-40b5-a18f-7bda1e187124)
![Snipaste_2023-11-21_22-41-34](https://github.com/l0o0/jasminum/assets/136339264/f83ba3c2-6ca4-4083-820d-149445f9c08b)
可以看到利用知网助手抓取网页条目知网元数据失败，但奇怪的是对于.pdf文件的元数据抓取在这个版本中是可以正常使用的
![Snipaste_2023-11-21_22-55-26](https://github.com/l0o0/jasminum/assets/136339264/98dceb7c-731a-43dd-a131-a4d55b4d463b)
（值得一提的是上个版本最近抓取知网元数据的功能完全失效了，不知道是不是也和翻译器未更新有关）

**Comment by l0o0** [comment]
这个我会跟进一下，我应该忘了修改这个查询的逻辑了

**Comment by fredericky123** [comment]
1.0.0-9也不能抓取如下链接
https://chn.oversea.cnki.net/kcms/detail/12.1288.F.20231117.1629.002.html

**Comment by TimeCapsule1219** [comment]
> 1.0.0-9也不能抓取如下链接 https://chn.oversea.cnki.net/kcms/detail/12.1288.F.20231117.1629.002.html
![image](https://github.com/l0o0/jasminum/assets/129166233/2d153e12-2a82-4913-af48-408093b7e29d)
wo我也是

**Comment by TimeCapsule1219** [comment]
> 1.0.0-9也不能抓取如下链接 https://chn.oversea.cnki.net/kcms/detail/12.1288.F.20231117.1629.002.html

![image](https://github.com/l0o0/jasminum/assets/129166233/795a5d23-4349-4e2b-b1c6-2feb1a7d7c78)
![image](https://github.com/l0o0/jasminum/assets/129166233/424c51dd-f5ca-4e10-9e83-71f57f43a038)

我也是，抓不下来文献，显示到图二就没有反应了

**Comment by fredericky123** [comment]
> > 1.0.0-9也不能抓取如下链接 https://chn.oversea.cnki.net/kcms/detail/12.1288.F.20231117.1629.002.html
> 
> ![image](https://user-images.githubusercontent.com/129166233/285370786-795a5d23-4349-4e2b-b1c6-2feb1a7d7c78.png) ![image](https://user-images.githubusercontent.com/129166233/285370861-424c51dd-f5ca-4e10-9e83-71f57f43a038.png)
> 
> 我也是，抓不下来文献，显示到图二就没有反应了

我也是抓不下来
