### ISSUE TITLE
新版本茉莉花插件能不能做一个适配zotero6的特别版

### ISSUE THREAD

**Issue by MrGongqi** [l0o0/jasminum#222]
你好，由于我没有安装zotero 7,仍然使用的zotero 6,但是现在知网改版了，原来的0.2.7版本无法抓取知网文献了，我看到新的0.9版本的茉莉花插件已经完全解决了这个问题，而我的zotero 6却无法安装，开发者能不能做一个适配zotero 6的，谢谢

**Comment by l0o0** [comment]
正在修改

MrGongqi ***@***.***> 于2023年11月22日周三 13:45写道：

**Comment by MrGongqi** [comment]
非常感谢
