### ISSUE TITLE
zotero 7 PDFtk serve 路径设置

### ISSUE THREAD

**Issue by PJRRRRR** [l0o0/jasminum#223]
zotero 7 PDFtk serve 路径设置旁边一直有感叹号，但是我已经安装了pdftk serve程序 我重新选择完文件夹后会变绿色，但是之后在首选项打开后又变成感叹号了
![QQ截图20231122170345](https://github.com/l0o0/jasminum/assets/145548149/d132d61f-8b95-4761-8fd1-a3fbac030778)
![QQ截图20231122170318](https://github.com/l0o0/jasminum/assets/145548149/02a7e12e-af52-402d-9da2-669a105867b5)

**Comment by l0o0** [comment]
同学应该是下载错了，
![图片](https://github.com/l0o0/jasminum/assets/2743744/1907fd1b-c529-4027-b592-ad79137859e7)

下载的是PDFtk server ， https://www.pdflabs.com/tools/pdftk-server

**Comment by PJRRRRR** [comment]
> 同学应该是下载错了， ![图片](https://user-images.githubusercontent.com/2743744/285089466-1907fd1b-c529-4027-b592-ad79137859e7.png)
> 
> 下载的是PDFtk server ， https://www.pdflabs.com/tools/pdftk-server

谢谢作者大大，问题已解决
