### ISSUE TITLE
更新至最新版本0.2.8后仍然出现无法提取知网数据，请跟进谢谢

### ISSUE THREAD

**Issue by eccwy98** [l0o0/jasminum#224]
<img width="321" alt="螢幕截圖 2023-11-22 下午9 51 43" src="https://github.com/l0o0/jasminum/assets/89065865/90ff0524-f246-40a4-a663-28a75a448be1">

**Comment by l0o0** [comment]
你好，知网浏览器抓取是依赖转换器的。你检查下知网的转换器有没及时更新，注意浏览器中也需要及时更新。

茉莉花插件只是用来辅助pdf元数据识别，下载转换器的

**Comment by minatozakiqiao** [comment]
> 你好，知网浏览器抓取是依赖转换器的。你检查下知网的转换器有没及时更新，注意浏览器中也需要及时更新
请问知网的转换器是什么呀

**Comment by HN-Jiang** [comment]
![图片](https://github.com/l0o0/jasminum/assets/53942586/beaca2b0-c525-4aa3-9bd9-e00ea3042829)
同样的问题。刚刚更新了转换器
