### ISSUE TITLE
你好，知网浏览器抓取是依赖转换器的。你检查下知网的转换器有没及时更新，注意浏览器中也需要及时更新。

### ISSUE THREAD

**Issue by minatozakiqiao** [l0o0/jasminum#226]
你好，知网浏览器抓取是依赖转换器的。你检查下知网的转换器有没及时更新，注意浏览器中也需要及时更新。

茉莉花插件只是用来辅助pdf元数据识别，下载转换器的

_Originally posted by @l0o0 in https://github.com/l0o0/jasminum/issues/224#issuecomment-1823684797_

**Comment by l0o0** [comment]
同学你好，这个有什么具体问题嘛😁

**Comment by l0o0** [comment]
没什么问题，我先关掉了
