### ISSUE TITLE
有关无论是使用“转换器”抓取新条目，还是使用茉莉花内置“抓取知网元数据”都失败的，可能是系统代理的问题！（clash等代理软件）

### ISSUE THREAD

**Issue by xjn6666** [l0o0/jasminum#229]
我的情况是使用学校的webvpn知网下载pdf，想使用connector抓取条目（更新过转换器还是失败），结果不行。换成使用茉莉花自带的“抓取知网元数据”一直报抓取失败。（zotero版本7，插件版本1.0.0-beta10）结果我关掉clash的系统代理就好了。我的clash使用的是规则模式，不确定为何会对茉莉花的抓取功能产生影响。分享给各位同学

**Comment by xjn6666** [comment]
补充一下，经过关闭clash，“好了”的是茉莉花的“抓取知网元数据”功能。在网页上尝试使用connector抓取新条目是依旧失败的，会报“使用 CNKI 保存时发生错误。改为尝试用 DOI 保存。保存此条目时发生错误。查看 [翻译器故障排除](https://www.zotero.org/support/troubleshooting_translator_issues) 获取更多信息。”

**Comment by l0o0** [comment]
好奇怪规则模式怎么也会让知网走代理。你能确认一下，知网流量确实走VPN么？

还有就是你是如何访问知网的，有没有使用图书馆的vpn工具？

**Comment by xjn6666** [comment]
我访问知网使用的是“webvpn”，一种只需要浏览器来实现访问网页资源的vpn方式。不是使用easyconnect那种需要生成虚拟网卡统一管理所有流量的vpn工具。我在clash截了好多次终于截到了知网走代理的链接，或许会有帮助。规则模式下究竟哪些流量会走代理而不直连或许是跟机场的默认规则有关系的，毕竟都是直接从机场订阅的节点链接
![image](https://github.com/l0o0/jasminum/assets/58368436/1356e860-6334-4160-a581-3a19c2c3d0dc)

**Comment by wenting0ma** [comment]
我也一直怀疑是clash的问题，但我不一样的地方在于，无论是通过学校链接进入知网，还是直接访问知网，我关闭clash还是仅能抓取到条目，而无法抓去pdf，即使是将pdf拖进zotero，也无法抓到条目。但开着clash的规则链接就连条目都抓不到。

**Comment by xjn6666** [comment]
> 我也一直怀疑是clash的问题，但我不一样的地方在于，无论是通过学校链接进入知网，还是直接访问知网，我关闭clash还是仅能抓取到条目，而无法抓去pdf，即使是将pdf拖进zotero，也无法抓到条目。但开着clash的规则链接就连条目都抓不到。

从知网直接抓取pdf失败估计是知网的转换器的问题（好像最近知网网页的规则有变动，转换器还没来得及更新），和茉莉花应该是无关的。至于你说把pdf拖进zotero抓条目失败的问题，可能跟我在本条issue中遇到的情况是一样的。

**Comment by wenting0ma** [comment]
> > 我也一直怀疑是clash的问题，但我不一样的地方在于，无论是通过学校链接进入知网，还是直接访问知网，我关闭clash还是仅能抓取到条目，而无法抓去pdf，即使是将pdf拖进zotero，也无法抓到条目。但开着clash的规则链接就连条目都抓不到。
> 
> 从知网直接抓取pdf失败估计是知网的转换器的问题（好像最近知网网页的规则有变动，转换器还没来得及更新），和茉莉花应该是无关的。至于你说把pdf拖进zotero抓条目失败的问题，可能跟我在本条issue中遇到的情况是一样的。

谢谢你的回复，我大概是10月出现这个情况，最近也跟着作者更新了插件，也在浏览器更新了，但还是一样，关clash能抓条目抓不到pdf，开着连条目都不大行
