### ISSUE TITLE
Catalina选择不了PDFtk Server路径

### ISSUE THREAD

**Issue by xiangsanliu** [l0o0/jasminum#23]
![image](https://user-images.githubusercontent.com/19505695/97956613-1a8b0700-1de4-11eb-9450-62b95719eb64.png)
刚开始进入这个设置有路径选择，再进去就选不了了

**Comment by xiangsanliu** [comment]
重新安装也不得行

**Comment by l0o0** [comment]
Mac系统请参考 #7 里面的设置

**Comment by zfhxi** [comment]
开发者似乎没有设计滚动条，你选择一个选项框，不断按Tab键就可以看到设置pdftk server路径的选项框了

**Comment by l0o0** [comment]
@zfhxi 啊，就窗口大小被限制了，下次窗口设置大些。确实没注意mac窗口差距这么大
