### ISSUE TITLE
知网不能提取，其余网站正常使用[BUG]

### ISSUE THREAD

**Issue by WangSiHan0711** [l0o0/jasminum#230]
**BUG说明**

请填写下面的版本信息
**Zotero 版本**：6.0.30.0
**Jasminum 插件版本**：0.2.8

请详细介绍使用中遇到的BUG，按照BUG类型，请在下面 3 个类别中具体说明。如果可以附上截图，那就更好了。

**知网元数据识别失败**

请提供识别失败的PDF文件名，或 Snapshot 条目标题

![jasminum](https://github.com/l0o0/jasminum/assets/151508182/44aced19-5666-4157-bb07-ea1eecb3c6d0)
每篇文章均这样
其余都更新完成，仍然没有用

**Comment by yszve** [comment]
我也是这个界面，既不能保存条目也不能保存PDF。翻译器都是更新了的。
把校园网的VPN（easyconnect）关了作为知网游客点击connector时可以保存条目，
挂上VPN后变成如楼主的图那样只显示目标文件夹连条目都无法保存，
挂上VPN（easyconnect）且更改Proxies（webvpn型）后，点击插件变成无法获取条目信息作为网页形式保存。

**Comment by l0o0** [comment]
我怀疑你们两位同学是使用学校的图书馆访问知网的。这种情况会出现点击按钮没有任何效果，应该是知网接口没返回数据的缘故。

可以试试下载这个[转换器](https://raw.githubusercontent.com/l0o0/translators_CN/cnki/CNKI.js)，手动更新知网的CNKI.js.

这个是直接抓取网页上的信息，所以不能在搜索页面使用，点击时不会在浏览器出现弹窗提示，可是会保留到Zotero。PDF附件也能正常下载。

你们可以测试一下这个新的转换器

**Comment by l0o0** [comment]
你们这个问题应该放到这个仓库的 https://github.com/l0o0/translators_CN

**Comment by l0o0** [comment]
> 是使用图书馆vpn的，因为之前一直这样操作，无异常。近期出现异常。感谢帮助，我会尝试一下解决方法

出现这样的问题是因为知网的引文导出接口参数更新了，转换器和Zotero Connector 中对于代理之后的接口请求有一些参数不能设置，所以出现问题了

**Comment by WangSiHan0711** [comment]
> > 是使用图书馆vpn的，因为之前一直这样操作，无异常。近期出现异常。感谢帮助，我会尝试一下解决方法
> 
> 出现这样的问题是因为知网的引文导出接口参数更新了，转换器和Zotero Connector 中对于代理之后的接口请求有一些参数不能设置，所以出现问题了

嗯嗯，请问下载这个就可以吗[translators_CN](https://github.com/l0o0/translators_CN/tree/master)
/CNKI.js

**Comment by l0o0** [comment]
一定是这个链接 https://raw.githubusercontent.com/l0o0/translators_CN/cnki/CNKI.js

**Comment by yszve** [comment]
> 一定是这个链接 https://raw.githubusercontent.com/l0o0/translators_CN/cnki/CNKI.js

![Snipaste_2023-11-29_18-33-41](https://github.com/l0o0/jasminum/assets/56151854/3f802bec-b088-4143-be48-588c090bdb3e)
多出两行字，不再只有目标文件夹，插件还做了doi尝试，但还是不行

**Comment by yszve** [comment]
> 一定是这个链接 https://raw.githubusercontent.com/l0o0/translators_CN/cnki/CNKI.js

解决了，我把这个就是更新后，又把Proxies的代理设置删了就行了，改了Proxies反而不行。

**Comment by yszve** [comment]
> 一定是这个链接 https://raw.githubusercontent.com/l0o0/translators_CN/cnki/CNKI.js

解决了，我把这个JS更新后，又把Proxies的代理设置删了就行了，改了Proxies反而不行。

**Comment by yszve** [comment]
多谢您。

**Comment by WangSiHan0711** [comment]
好的，一番操作之后现在变成了这个问题
![image](https://github.com/l0o0/jasminum/assets/151508182/8cb4264e-ca89-4e7e-b149-163fa8b413ac)

**Comment by l0o0** [comment]
> 好的，一番操作之后现在变成了这个问题 ![image](https://private-user-images.githubusercontent.com/151508182/286592074-8cb4264e-ca89-4e7e-b149-163fa8b413ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNjk2ODEsIm5iZiI6MTcwMTI2OTM4MSwicGF0aCI6Ii8xNTE1MDgxODIvMjg2NTkyMDc0LThjYjQyNjRlLWNhODktNGU3ZS1iMTQ5LTE2M2ZhOGI0MTNhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOVQxNDQ5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MjdjM2JlMmE5YTJiOWE5NzdjNDA1MWY2YTExOWUwODkxNDdjOTUwMGVlZWEyZjgwMzliYWVjNjUxY2VjM2ZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5-4nOy6d1HqjwYgW4beq8SroNnyt5GROUozhGnWJyBs)

能否提供异常日志？

**Comment by yszve** [comment]
> > > 一定是这个链接 https://raw.githubusercontent.com/l0o0/translators_CN/cnki/CNKI.js
> > 
> > 
> > 解决了，我把这个JS更新后，又把Proxies的代理设置删了就行了，改了Proxies反而不行。
> 
> 同学，你是使用的网页VPN访问知网的么？ 还有就是你设置的Proxies是在哪里设置的？

我按这个链接改的（https://www.linxingzhong.top/posts/2020-2-26/），但反而出问题，不改Proxies就按默认来反而是好的。

**Comment by l0o0** [comment]
> > > > 一定是这个链接 https://raw.githubusercontent.com/l0o0/translators_CN/cnki/CNKI.js
> > > 
> > > 
> > > 解决了，我把这个JS更新后，又把Proxies的代理设置删了就行了，改了Proxies反而不行。
> > 
> > 
> > 同学，你是使用的网页VPN访问知网的么？ 还有就是你设置的Proxies是在哪里设置的？
> 
> 我按这个链接改的（[https://www.linxingzhong.top/posts/2020-2-26/），但反而出问题，不改Proxies就按默认来反而是好的。](https://www.linxingzhong.top/posts/2020-2-26/%EF%BC%89%EF%BC%8C%E4%BD%86%E5%8F%8D%E8%80%8C%E5%87%BA%E9%97%AE%E9%A2%98%EF%BC%8C%E4%B8%8D%E6%94%B9Proxies%E5%B0%B1%E6%8C%89%E9%BB%98%E8%AE%A4%E6%9D%A5%E5%8F%8D%E8%80%8C%E6%98%AF%E5%A5%BD%E7%9A%84%E3%80%82)

配置这个Proxy 是个技术活，门槛比较高。当时就不想推这个东西，直接在知网的转换器里，把代理后网址也加到识别规则里，这样就直接能识别了。可惜知网前段时间的改版，更新了参数，使用代理后原来的接口就不能用了。

试试更新到更新的代码
https://github.com/l0o0/translators_CN/commit/4d75425e3a75650cdefb755a5fb10b52a876bd73
