### ISSUE TITLE
希望能够支持nature网页future栏目列表批量下载🛠功能建议[Feature]

### ISSUE THREAD

**Issue by tangxunding** [l0o0/jasminum#235]
[请详细说明新功能点，描述地越清楚，开发起来速度越快。

可以详细说说因为没有此功能，在日常使用中会有什么问题，对你使用Zotero或科研有什么影响。

如果有了此功能，你觉得在插件里要怎么设计才会让你的使用更加方便。

大家畅所欲言，如果一两句说不明白，可以多写一些。写着写着你的功能需求就明确了♥]

希望能够支持nature网页future栏目列表批量下载，谢谢各位大佬！
(https://www.nature.com/nature/articles?type=futures)

**Comment by jiaojiaodubai** [comment]
@tangxunding  这属于[官方仓库](https://github.com/zotero/translators)维护的翻译器，不是茉莉花提供的功能，你可以到官方仓库 https://github.com/zotero/translators 提交issue

**Comment by l0o0** [comment]
确实，这个是属于转换器的范围，建议到官方那边提交请求。这里就先关掉啦
