### ISSUE TITLE
无法抓取知网学位论文full-pdf

### ISSUE THREAD

**Issue by PicerGhost** [l0o0/jasminum#238]
**BUG说明**
Zotero最近开始抓取不了知网学位论文full-pdf

请填写下面的版本信息
**Zotero 版本**：6.0.30
**Jasminum 插件版本**：0.2.8

请详细介绍使用中遇到的BUG，按照BUG类型，请在下面 3 个类别中具体说明。如果可以附上截图，那就更好了。

**知网元数据识别失败**

请提供识别失败的PDF文件名，或 Snapshot 条目标题
![Show_Error](https://github.com/l0o0/jasminum/assets/116953815/3cb68c5b-0aa4-431a-88f1-7412775fd358)

**Comment by jiaojiaodubai** [comment]
浏览器抓取与本仓库无关，请发到[这里](https://github.com/l0o0/translators_CN)

**Comment by jiaojiaodubai** [comment]
已经在 b9d2c2e36de0008f24ad226370c122ec7323d8e3 得到修复了

**Comment by PicerGhost** [comment]
> 已经在 [这里](https://github.com/l0o0/translators_CN/commit/b9d2c2e36de0008f24ad226370c122ec7323d8e3) 修复了

大佬辛苦了，太感谢了！！！
