### ISSUE TITLE
插件在文件名为标题是无法使用

### ISSUE THREAD

**Issue by sunshineharry** [l0o0/jasminum#24]
插件配置如下：
![image](https://user-images.githubusercontent.com/52942042/98375710-74f2c480-207d-11eb-8d8b-2a6db39ec27f.png)
对于这种文件，它失效了
![image](https://user-images.githubusercontent.com/52942042/98375778-92279300-207d-11eb-8d47-30da9f5881c7.png)
求问怎么解决
谢谢啦

**Comment by l0o0** [comment]
知网api变了，等我修复

**Comment by TaiwenYou** [comment]
I have the same problem.

**Comment by l0o0** [comment]
请尝试008版本。
