### ISSUE TITLE
能否绕开zotfile实现重命名？

### ISSUE THREAD

**Issue by linsezi** [l0o0/jasminum#241]
Zotero早已支持通过按父级元数据进行文件重命名，然而，ZotFile的更新已经停滞很长时间了。在没有使用ZotFile的情况下，茉莉花拉取的知网PDF默认标题为"Full Text PDF"，但实际上文件名已经由Zotero自动命名。是否可以让茉莉花拉取的PDF标题直接使用Zotero按父级元数据重命名的文件名呢？如图：
![image](https://github.com/l0o0/jasminum/assets/155357467/cc3272dc-7fc7-4838-a056-7ecd44edd1b3)

**Comment by jiaojiaodubai** [comment]
Zotero 7已经内置重命名文件名，而附件的标题重命名在 [Attanger 插件](https://zotero-chinese.com/plugins/#search=attanger)。
