### ISSUE TITLE
茉莉花插件无法获取知网信息，提示“未查询到结果”

### ISSUE THREAD

**Issue by Zhang-Qixian** [l0o0/jasminum#242]
**BUG说明**

请填写下面的版本信息
**Zotero 版本**：6.0.30
**Jasminum 插件版本**：0.2.8

**知网元数据识别失败**
**上传pdf附件，点击“知网助手”--点击“抓取知网元数据”后，提示“未查询到结果”。**
![image](https://github.com/l0o0/jasminum/assets/155280855/40172e21-0069-46ff-931f-a8c35377b576)

识别失败的PDF文件名：金属基复合材料振动辅助磁流变抛光关键技术研究-李震

其他说明：
1、之前成功，最近一直失败。按照网上提醒的更新翻译器后，同样无法成功
2、同时在 非官方维护中文翻译器页面，点击“更新全部”后，zotero会闪退

**Comment by Zhang-Qixian** [comment]
@l0o0 辛苦给看看这个问题呢

**Comment by Zhang-Qixian** [comment]
@l0o0 这个问题可以给看看吗？长时间无法解决

**Comment by jiaojiaodubai** [comment]
某些篇名用知网的搜索本身无法检索到结果，此问题似乎已经修复
