### ISSUE TITLE
Zotero 7 抓取知网数据失败

### ISSUE THREAD

**Issue by Userchangzhou** [l0o0/jasminum#243]
**BUG说明**
Zotero 7 抓取知网数据失败
如何调整

![微信图片_20240106130103](https://github.com/l0o0/jasminum/assets/146600519/a8379fa0-a7c3-468a-a6c5-f5fd30f1241b)

**Comment by l0o0** [comment]
是只有这一个pdf抓取失败，还是所有PDF都没有成功？

**Comment by feifeimao7** [comment]
我的也是失败，是所有的都失败

**Comment by l0o0** [comment]
@feifeimao7 你的是什么版本的插件？

**Comment by JoeYi666** [comment]
我也是，有解决方案吗
