### ISSUE TITLE
1.0.0-15插件显示功能异常[BUG]

### ISSUE THREAD

**Issue by 2021521** [l0o0/jasminum#249]
**BUG说明**

请填写下面的版本信息
**7.0.0-beta.54+6b996d4f9 (64-bit)**：
**[1.0.0-15](https://github.com/l0o0/jasminum/releases/tag/1.0.0-15)**：

请详细介绍使用中遇到的BUG，按照BUG类型，请在下面 3 个类别中具体说明。如果可以附上截图，那就更好了。

**其他功能异常**

安装最新版的茉莉花插件，在Zotero的设置中并不显示茉莉花的功能界面。下面第一幅图是茉莉花插件安装之后并没有任何描述，第二幅图则是在设置中并没有茉莉花的功能界面。经检验，1.0.0-14插件目前能正常使用。
![image](https://github.com/l0o0/jasminum/assets/49866394/b7c9ba14-47c4-4fb3-8562-17f885d63eb4)
![image](https://github.com/l0o0/jasminum/assets/49866394/6511386c-41e5-42f5-9589-432070698fa2)

**Comment by CamWam** [comment]
同

**Comment by jiaojiaodubai** [comment]
同 #300，已于 f14a8c824e20d96db5f9887a65f2d293dfe07a29 修复。
