### ISSUE TITLE
茉莉花插件无法获取知网信息，提示“未查询到结果”[BUG]

### ISSUE THREAD

**Issue by Zhang-Qixian** [l0o0/jasminum#253]
**BUG说明**

请填写下面的版本信息
**Zotero 版本**：**6.0.30**
**Jasminum 插件版本**：**0.2.8**

**知网元数据识别失败**

上传中文论文的PDF附件后，右键点击“知网助手”->"抓取知网数据"，右下角出现弹窗，识别到了作者和文章名，但是提示“未查询到数据”

PDF文件名：
基于飞秒激光诱导重分布近场驱动纳米烧蚀的研究_胥亦实

![image](https://github.com/l0o0/jasminum/assets/155280855/a675667f-0a4e-460f-9855-89c87cad83b1)

以前更成功，但是现在都不能成功了，恳请开发大大们给看看

**Comment by Carrot0617** [comment]
我也有这个问题，有没有人知道是怎么回事，怎么办呀

**Comment by 14-5** [comment]
同样的问题，zotero 6.0.36，茉莉花0.2.8和0.2.9都试了

**Comment by jiaojiaodubai** [comment]
@14-5 见 #316
