### ISSUE TITLE
插件未适配zotero beta.56

### ISSUE THREAD

**Issue by pencilheart** [l0o0/jasminum#254]
设置页面中无此插件页面，望作者大佬更新。

**Comment by northword** [comment]
need more info: 

![image](https://github.com/l0o0/jasminum/assets/44738481/e5e4e7c9-a443-4449-b112-d3ce50f0c67c)

![image](https://github.com/l0o0/jasminum/assets/44738481/49339951-a778-4692-826c-7bc4fc47259b)

**Comment by pencilheart** [comment]
重新安装插件解决了
