### ISSUE TITLE
请概括一下内容，想一个标题[版本BUG]

### ISSUE THREAD

**Issue by OrlandoZh** [l0o0/jasminum#255]
**BUG说明**

请填写下面的版本信息
**Zotero 版本**： 7 beta 57
**Jasminum 插件版本**：
1.0.13
请详细介绍使用中遇到的BUG，按照BUG类型，请在下面 3 个类别中具体说明。如果可以附上截图，那就更好了。

**元数据识别错误**
导致英文文献拖入pdf后会生成两条文献条目

**Comment by jiaojiaodubai** [comment]
能否提供PDF样本？

**Comment by OrlandoZh** [comment]
@jiaojiaodubai  反复测试后发现是针对有doi的文献，这类文献解析器会获取一次，然后茉莉花再获取一次就出现这情况
