### ISSUE TITLE
CNKI翻译器失效，无法抓取PDF[BUG]

### ISSUE THREAD

**Issue by yinongfeng** [l0o0/jasminum#259]
**BUG说明**

请填写下面的版本信息
**Zotero 版本**：6.0.30
**Jasminum 插件版本**：0.2.8

请详细介绍使用中遇到的BUG，按照BUG类型，请在下面 3 个类别中具体说明。如果可以附上截图，那就更好了。

**知网元数据识别失败**

![image](https://github.com/l0o0/jasminum/assets/152311260/177abf87-367d-421e-b4d5-f012a22214a9)

点击connect插件，之后保存出故障，翻译器故障，选择了save page snapshot

**Comment by PicerGhost** [comment]
我也遇到了这个问题，刚才解决了，是因为开学回到学校要重新IP登录cnki。如果你刚回学校的话，可以先手动下载一篇，然后cnki会提醒让你登录然后才能下载，选择IP登录，然后你再用Zotero Connector就可以下载了，如果还不行，就去https://github.com/l0o0/translators_CN更新一下翻译器

**Comment by gorgeousemily** [comment]
我刚刚也遇到这个问题了，但不是ip问题，因为我自己可以下载pdf。
这次应该是因为知网的翻译器在3月4号又更新了一版，如果本地更新了那就会出现无法抓取的问题。
解决方法是手动找到 CNKI.js 的文件，然后[更新一下](https://[raw.githubusercontent.com/l0o0/translators_CN/cnki/CNKI.js](https://raw.githubusercontent.com/l0o0/translators_CN/cnki/CNKI.js))，再抓取的时候记得先刷新，就可以正常使用了。

**Comment by jiaojiaodubai** [comment]
见[此处](https://github.com/l0o0/translators_CN/issues/252)

**Comment by yinongfeng** [comment]
谢谢！我直接升级成了zotero7，就啥事儿都没了。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jiangyu-bjtu** [comment]
![微信图片_20240430112527](https://github.com/l0o0/jasminum/assets/76524681/65b07338-0183-4799-9a2f-0adc62825f92)

**Comment by jiangyu-bjtu** [comment]
请问这是什么原因呢
