### ISSUE TITLE
能否支持多种文件名格式？

### ISSUE THREAD

**Issue by mbhyaaa** [l0o0/jasminum#26]
不同网站下载的文献名格式有区别，不能统一设置。
另外利用zotfile重命名完以后，再拖回来都是不支持的，因为格式变了。

**Comment by l0o0** [comment]
不同网站下载的格式你有提供一些示例让我参考一下么？
zotfile重命名后的文件，确实不能识别，因为我们是靠文件名中的信息来识别的。下次我看看有什么办法可以完善一下

**Comment by mbhyaaa** [comment]
> 不同网站下载的格式你有提供一些示例让我参考一下么？
> zotfile重命名后的文件，确实不能识别，因为我们是靠文件名中的信息来识别的。下次我看看有什么办法可以完善一下

本来想说有的带名字（比如知网），有的不带（比如万方、维普），又看了一下介绍发现是都支持的。
第二条的需求是因为，今天我错删文件，然后试图往回拖拽发现识别不了，只能把名字改回默认格式再拖。
我认为的解决方式，就是支持设置多种文件名格式，这样我可以设置一种对应默认下载下来的，再设置另一种和zotfile命名后一致的，不过也刚刚想到两者可能会有冲突。

**Comment by l0o0** [comment]
是的，如果同时有两个格式，不知道需要使用哪个。两个都尝试一次，抓取过程也比较花时间。所以如果遇到这种情况还是手动处理一下比较好

**Comment by mbhyaaa** [comment]
> 是的，如果同时有两个格式，不知道需要使用哪个。两个都尝试一次，抓取过程也比较花时间。所以如果遇到这种情况还是手动处理一下比较好

好的，谢谢您了
