### ISSUE TITLE
小工具统一日期格式缺失

### ISSUE THREAD

**Issue by ChrisAntash** [l0o0/jasminum#262]
**Zotero 版本**：7.0.0-beta.65+b047f3d90
**Jasminum 插件版本**：1.0.0-14

更新至zotero7后，文献条目的小工具内统一日期格式功能不见了，望作者修复一下，统一的日期真的很赏心悦目。
![缺失统一时间格式](https://github.com/l0o0/jasminum/assets/86591357/3736c0dc-f2f6-4fac-bb5b-e0ac6e0a1c41)

**Comment by northword** [comment]
此功能已迁移至 [Linter for Zotero](https://github.com/northword/zotero-format-metadata)，茉莉花未来会集中于中文生态增强。
