### ISSUE TITLE
转换器界面显示空白，且点击更新显示下载失败，调试显示TypeError: ztoolkit.getGlobal(...) is undefined

### ISSUE THREAD

**Issue by ZhenyuXiao** [l0o0/jasminum#267]
**BUG说明**
转换器界面显示空白，且点击更新显示下载失败，调试显示TypeError: ztoolkit.getGlobal(...) is undefined

请填写下面的版本信息
**7.0.0-beta.71+03d0ea436 (64-bit)**：
**Jasminum 1.0.0-14**：

**非官方转换器下载异常**
1. Chinese Translators 显示不正常，全为空白
2. 点击` update all `弹出一堆错误
3. Debug output 显示 **下载失败 TypeError: ztoolkit.getGlobal(...) is undefined**
4. 关闭其他插件后也显示一样的错误
![image](https://github.com/l0o0/jasminum/assets/46998685/1b463875-483e-490f-89b6-5ada024e0672)
![image](https://github.com/l0o0/jasminum/assets/46998685/cb8b336e-cffc-4663-9463-da22b70022f8)
(3)(+0164294): [Jasminum] download all translators

(3)(+0000000): [Jasminum] C:\Users\Gauss\AppData\Local\Temp\Zotero\translator.json

(3)(+0000001): Getting contents of C:\Users\Gauss\AppData\Local\Temp\Zotero\translator.json

(3)(+0000003): [Jasminum] https://oss.wwang.de/translators_CN/Baidu Baike.js

(5)(+0000002): CookieSandbox: Being paranoid about channel for oss.wwang.de

(5)(+0000000): CookieSandbox: Cleared cookies to be sent to oss.wwang.de

(3)(+0000004): [Jasminum] https://oss.wwang.de/translators_CN/Baidu Scholar.js

(3)(+0000001): C:\Users\Gauss\Zotero\translators\Baidu Baike.js

(3)(+0000000): [Jasminum] Baidu Baike.js 下载失败 TypeError: ztoolkit.getGlobal(...) is undefined

(5)(+0000013): CookieSandbox: Being paranoid about channel for oss.wwang.de

(5)(+0000001): CookieSandbox: Cleared cookies to be sent to oss.wwang.de

(3)(+0000002): [Jasminum] https://oss.wwang.de/translators_CN/BiliBili.js

(3)(+0000005): C:\Users\Gauss\Zotero\translators\Baidu Scholar.js

(3)(+0000000): [Jasminum] Baidu Scholar.js 下载失败 TypeError: ztoolkit.getGlobal(...) is undefined

(5)(+0000009): CookieSandbox: Being paranoid about channel for oss.wwang.de

(5)(+0000000): CookieSandbox: Cleared cookies to be sent to oss.wwang.de

(3)(+0000010): [Jasminum] https://oss.wwang.de/translators_CN/CCPINFO.js

(3)(+0000056): C:\Users\Gauss\Zotero\translators\BiliBili.js

(3)(+0000000): [Jasminum] BiliBili.js 下载失败 TypeError: ztoolkit.getGlobal(...) is undefined

(5)(+0000013): CookieSandbox: Being paranoid about channel for oss.wwang.de

(5)(+0000000): CookieSandbox: Cleared cookies to be sent to oss.wwang.de

(3)(+0000030): [Jasminum] https://oss.wwang.de/translators_CN/CNBKSY.js

(3)(+0000067): C:\Users\Gauss\Zotero\translators\CCPINFO.js

(3)(+0000001): [Jasminum] CCPINFO.js 下载失败 TypeError: ztoolkit.getGlobal(...) is undefined

**Comment by wefuiwheoi** [comment]
我i也是更新了zotero就成这样了，有点小烦

**Comment by Howard-H-Du** [comment]
I have the same problem. Wish it could be fixed. I extremely appreciate your contribution to the scholarship.
