### ISSUE TITLE
自动化发布

### ISSUE THREAD

**Issue by lychichem** [l0o0/jasminum#27]
看到前辈好久忘了把更新内容加进release了……所以搞了个自动化release轮子，用的github actions（就是顶上那个），不过建议前辈不要直接merge我的分支（lychichem/jasminum），因为可能会有文件冲突，最好先点actions再点set up a workflow yourself，然后复制我的.github/workflows/main.yml全文，以后每次更新完想release的时候只要打个v*的tag就能自动发布新版了（当然install.rdf和update.rdf还是应该要改成对应tag的版本号的）

**Comment by l0o0** [comment]
好的，我下个版本我试试，谢谢同学的工作

**Comment by l0o0** [comment]
我忘了修改install.rdf 里的版本号了
