### ISSUE TITLE
translator一直提示loading，无法更新使用

### ISSUE THREAD

**Issue by MOWAGN** [l0o0/jasminum#287]
**BUG说明**

请填写下面的版本信息
**Zotero 版本**：7.0.0-beta.114+d869d7898 (64-bit)
**Jasminum 插件版本**：1.0.0-16

请详细介绍使用中遇到的BUG，按照BUG类型，请在下面 3 个类别中具体说明。如果可以附上截图，那就更好了。

**非官方转换器下载异常**

非官方转换器下载出现异常，一直提示loading，无法更新，更新全部和刷新选项全部没有反应。
![image](https://github.com/user-attachments/assets/9e6c94d5-1c60-4cd3-9316-516bbb2b0334)

**Comment by jiaojiaodubai** [comment]
服务器故障，已修复
