### ISSUE TITLE
jasminum和zotero7为什么不兼容

### ISSUE THREAD

**Issue by syulanyang** [l0o0/jasminum#289]
**BUG说明**

请填写下面的版本信息
**Zotero 7**：
**Jasminum -v0.2.9 (1)**：

请详细介绍使用中遇到的BUG，按照BUG类型，请在下面 3 个类别中具体说明。如果可以附上截图，那就更好了。

**其他功能异常**

6可以正常安装，但是7不兼容，有更新的版本for 7吗？

**Comment by jiaojiaodubai** [comment]
插件请到[插件商店](https://zotero-chinese.com/plugins/)下载

**Comment by IronShannon** [comment]
> 插件请到[插件商店](https://zotero-chinese.com/plugins/)下载

请问从该地址下载的能适配zotero7吗
