### ISSUE TITLE
希望可以取消Tags自动添加功能

### ISSUE THREAD

**Issue by ningyawei** [l0o0/jasminum#29]
通用设置里取消tags自动添加功能，但是拖进去中文pdf后，还是会自动添加tags。
可不可以设置取消自动添加tags？

![020](https://user-images.githubusercontent.com/14836854/103160031-45804e80-47c8-11eb-87b6-82b3b906fa86.png)
![021](https://user-images.githubusercontent.com/14836854/103160041-6d6fb200-47c8-11eb-9868-2ae62df05135.png)

**Comment by l0o0** [comment]
嗯，这个功能之前添加过，可能没成功，会在下个版本里添加。到时候麻烦关注下

**Comment by ningyawei** [comment]
好的~ ![image](https://user-images.githubusercontent.com/14836854/103171870-5c19ba80-4847-11eb-8728-a2348f0f52cb.png)
