### ISSUE TITLE
🛠功能建议[Feature]匹配学位论文地点

### ISSUE THREAD

**Issue by s23ir45** [l0o0/jasminum#292]
您好，感谢您提供这么好的插件。
目前知网学位论文抓取的信息，地点一栏没有，能否按照更新IF的思路，根据教育部的高校地点库，抓取高校之后直接匹配更新一下学位论文的地点一栏信息。
如果可以，您是否可以实现一下，感觉按照国标引文文献这项信息挺需要，谢谢。

这里有高校地点文档信息[http://www.moe.gov.cn/jyb_xxgk/s5743/s5744/A03/202110/t20211025_574874.html]

**Comment by jiaojiaodubai** [comment]
此功能已经在 [Zotero Linter](https://github.com/northword/zotero-format-metadata) 实现，未来预计茉莉花将专注于中文PDF的条目抓取
