### ISSUE TITLE
zotero7 茉莉花中文附件获取

### ISSUE THREAD

**Issue by LBJCG** [l0o0/jasminum#295]
在zotero6中，有知网附件获取功能，在元数据上右击即可抓取知网元数据的附件。为什么在zotero7的茉莉花附件中取消了这个功能？
<img width="708" alt="78ccc3eb_8433257" src="https://github.com/user-attachments/assets/2ef34e69-72a0-449c-b019-9ce28577551e">

**Comment by jiaojiaodubai** [comment]
Z7 的插件架构不同于 Z6，不能直接 Copy 原先写好的代码来用，只是暂时没有实现。再者，任何批量下载行为都有帐号封禁的风险，批量下载 PDF 建议还是走知网官方推荐的知网研学。

**Comment by LBJCG** [comment]
非常感谢您的答复，我已了解。谢谢！
