### ISSUE TITLE
网络正常，点击“抓取知网元数据”无反应

### ISSUE THREAD

**Issue by liujinbao96** [l0o0/jasminum#3]
茉莉花0.0.3，网络正常，从知网下载中文文献PDF导入文献库后右键，大部分时间点击“抓取知网元数据”无反应，但有时可以正常拉取信息。PDF命名方式为 题目_作者

**Comment by l0o0** [comment]
@liujinbao96 好的，谢谢你的反馈，能提供一下不成功的文件名么，我这边测试一下

**Comment by liujinbao96** [comment]
部分文件名如下，感谢！
中国家庭婚姻破裂对中国子女成就的长期影响_张春泥
运动式协调及其制度逻辑_以B市技能人才政策制定为例_王飞
机遇不平等_概念_机制与启示_靳永爱

**Comment by l0o0** [comment]
@liujinbao96 好的，我先测试下

**Comment by l0o0** [comment]
@liujinbao96 我这边可以，你试试这个文件，把后缀改成xpi再安装
[jasminum_0.0.3.zip](https://github.com/l0o0/jasminum/files/5040242/jasminum_0.0.3.zip)

**Comment by liujinbao96** [comment]
用这个文件重新安装后已解决，感谢！
