### ISSUE TITLE
新版本不兼容

### ISSUE THREAD

**Issue by lyndonlyu** [l0o0/jasminum#300]
**BUG说明**

请填写下面的版本信息
**7.0.3 (64-bit) windows**：
**Jasminum 1.0.0-16**：

必现，版本不兼容，安装后重启，不会显示在设置中
![image](https://github.com/user-attachments/assets/27d62f47-4de5-4a1a-ad18-d32df3e6d4a0)

![image](https://github.com/user-attachments/assets/404bb6d7-70dc-4a45-a150-a5144609297a)

**Comment by zzxgo** [comment]
加一，同样有这个问题

**Comment by yellowdoge1996** [comment]
+1

**Comment by Ryan-4327** [comment]
+1 windows macos 都遇到这个问题了

**Comment by H-Tung** [comment]
今天帮人装 Zotero，目前测试的解决方案：卸载新版本 Zotero 选择不保留配置文件，重启后安装 [Windows_x64_7.0.1](https://download.zotero.org/client/release/7.0.1/Zotero-7.0.1_x64_setup.exe) 然后安装 Jasminum 1.0.0-16 即可。

成功后升级应该是不影响的，我现在的 Zotero 7.0.5 是可以正常显示茉莉花菜单的。

**Comment by littleironx** [comment]
同样有这个问题，很严重的bug
