### ISSUE TITLE
硕博论文元数据识别，发表日期字段有问题[BUG]

### ISSUE THREAD

**Issue by cjhonlyone** [l0o0/jasminum#301]
**BUG说明**

请填写下面的版本信息
**Zotero 版本**：7
**Jasminum 插件版本**：1.0.0-16

**知网元数据字段有误**

拉取的元数据日期为2021年
![image](https://github.com/user-attachments/assets/9e74580b-2cf8-4a27-be41-a956f637738e)
源论文提交日期与知网日期均为2020年
![image](https://github.com/user-attachments/assets/47280446-623c-4547-a8e1-470a020e5131)
![image](https://github.com/user-attachments/assets/b677ae89-9c82-4c36-9b25-e2acf1715495)

另外有个小问题，我想自行编译该插件
npm install
npm run build-dev
得到xpi文件，我切换到1.0.0-16版本的代码，结果却编译出版本号1.0.0-15，且安装后插件无法启动，
请问这是什么原因？感谢！

![image](https://github.com/user-attachments/assets/cbd355e5-e5cc-4aa1-b6fb-194f9c67ac53)

(3)(+0017902): Installing plugin jasminum@linxzh.com
(3)(+0000015): Installed plugin jasminum@linxzh.com
(3)(+0000002): Calling bootstrap method 'install' for plugin jasminum@linxzh.com version 1.0.0-15 with reason ADDON_INSTALL
(3)(+0000001): Calling bootstrap method 'startup' for plugin jasminum@linxzh.com version 1.0.0-15 with reason ADDON_INSTALL
(1)(+0000000): Error running bootstrap method 'startup' on jasminum@linxzh.com
(1)(+0000001): Error opening input stream (invalid filename?): jar:file:///C:/Users/caopc/AppData/Roaming/Zotero/Zotero/Profiles/mc8c4cft.default/extensions/jasminum@linxzh.com.xpi!/chrome/content/scripts/index.js

**Comment by jiaojiaodubai** [comment]
已修复，知网更新了接口，新旧接口导出的信息不同。

**Comment by cjhonlyone** [comment]
感谢作者！
