### ISSUE TITLE
无法抓取中文文献

### ISSUE THREAD

**Issue by Guo1ess** [l0o0/jasminum#302]
**BUG说明**
**Zotero 版本**：7.0.3
**Jasminum 插件版本**：1.0.0-16

**非官方转换器下载异常**

打开设置界面，一直显示loading，所有中文网站无法抓取数据
![image](https://github.com/user-attachments/assets/aa39031d-0050-4827-b1e7-9e574bf853e0)

**Comment by alphagui** [comment]
same issue, how to solve?

**Comment by Guo1ess** [comment]
> same issue, how to solve?

It seems like a problem caused by network proxy. I turn that off and it works well.

**Comment by jiaojiaodubai** [comment]
不要开启代理访问

**Comment by Thinkaboutzu9** [comment]
> 不要开启代理访问

在哪里设置

**Comment by jiaojiaodubai** [comment]
同 #287
