### ISSUE TITLE
请概括一下内容，想一个标题[BUG]

### ISSUE THREAD

**Issue by Wynxa** [l0o0/jasminum#304]
**BUG说明**

请填写下面的版本信息
**Zotero 版本**：7
**Jasminum 插件版本**：1.00.16

**知网元数据识别失败**

请提供识别失败的PDF文件名，或 Snapshot 条目标题

**非官方转换器下载异常**

点击刷新和全部更新翻译器没有反应

**其他功能异常**
学位论文的pdf无法抓取到

**Comment by jiaojiaodubai** [comment]
浏览器抓取问题请到[Translators_CN](https://github.com/l0o0/translators_CN)反馈。
