### ISSUE TITLE
小工具的日期格式化功能失效

### ISSUE THREAD

**Issue by ljs-fjmu-edu-cn** [l0o0/jasminum#306]
**BUG说明**

请填写下面的版本信息
**Zotero 版本7：
**Jasminum 插件版本1.00-16：
**其他功能异常**
小工具的日期格式化功能缺失了
![1](https://github.com/user-attachments/assets/3e8ee47a-a44d-4475-8bc7-b530b3c8bb1f)
![2](https://github.com/user-attachments/assets/9cb3f3e2-2242-4ea3-82b0-e59ded3ddbe7)

**Comment by jiaojiaodubai** [comment]
目前条目元数据格式化基本在 [Linter](https://github.com/northword/zotero-format-metadata) 完成。

**Comment by ljs-fjmu-edu-cn** [comment]
已装Linter插件，体验不错，那么问题来了:右键茉莉花冗余的知网助手和小工具怎么去除或个性化选择显示与否？
---- 回复的原邮件 ----
***@***.***>发送日期2024年09月21日 11:47 ***@***.***> ***@***.***>,
***@***.***>主题Re: [l0o0/jasminum] 小工具的日期格式化功能失效 (Issue #306)
目前条目元数据格式化基本在 Linter 完成。

**Comment by ljs-fjmu-edu-cn** [comment]
> 目前条目元数据格式化基本在 [Linter](https://github.com/northword/zotero-format-metadata) 完成。
