### ISSUE TITLE
🛠建议增加修改caj附件保存位置的功能[Feature]

### ISSUE THREAD

**Issue by epoch8260** [l0o0/jasminum#308]
请详细说明新功能点，描述地越清楚，开发起来速度越快。

可以详细说说因为没有此功能，在日常使用中会有什么问题，对你使用Zotero或科研有什么影响。

如果有了此功能，你觉得在插件里要怎么设计才会让你的使用更加方便。

大家畅所欲言，如果一两句说不明白，可以多写一些。写着写着你的功能需求就明确了♥

**Comment by jiaojiaodubai** [comment]
附件默认采用 storage 存储，如果需要用 link 模式，可以用 [Attanger](https://github.com/MuiseDestiny/zotero-attanger)（注意与 webDAV同步方案不兼容）
