### ISSUE TITLE
zotero7中茉莉花插件显示安装了，但是在设置里看不到茉莉花的选项。

### ISSUE THREAD

**Issue by wzheyo** [l0o0/jasminum#309]
zotero7中茉莉花插件显示安装了，但是在设置里看不到茉莉花的选项，如图，
**zotero版本7.0.6，茉莉花版本1.0.0-16**
![CleanShot 2024-09-21 at 11 14 18@2x](https://github.com/user-attachments/assets/0947589a-d2a4-4d95-be4c-539610e98741)
![CleanShot 2024-09-21 at 11 14 34@2x](https://github.com/user-attachments/assets/4627c7ff-3d9a-4ce2-9a16-f696953f8c01)

**Comment by jiaojiaodubai** [comment]
暂时按照[这里](https://zotero-chinese.com/user-guide/faqs/plugins#%E5%AE%89%E8%A3%85%E6%8F%92%E4%BB%B6%E5%90%8E-%E6%97%A0%E4%BB%BB%E4%BD%95%E5%BC%B9%E7%AA%97%E9%94%99%E8%AF%AF-%E4%BD%86%E6%B2%A1%E6%9C%89%E6%8F%92%E4%BB%B6%E8%AE%BE%E7%BD%AE%E9%A1%B9%E6%88%96%E8%8F%9C%E5%8D%95%E9%A1%B9)解决，等待插件更新

**Comment by wzheyo** [comment]
感谢！问题解决了。

**Comment by Airrhead** [comment]
mac上的zotero版本为7.0.6，茉莉花版本为1.0.0-14（因为最新版disable了），更新非官方维护中文转换器时，所有的js转换全部下载失败了，请问可以解决吗
<img width="83" alt="截屏2024-09-23 17 00 02" src="https://github.com/user-attachments/assets/6cd483d5-1a1d-43cf-b662-972fa0b300a1">

**Comment by jiaojiaodubai** [comment]
同 #300
