### ISSUE TITLE
批量文章只能抓取第一个文章的对应信息

### ISSUE THREAD

**Issue by YidingJiangfang** [l0o0/jasminum#311]
**BUG说明**

请填写下面的版本信息
**Zotero 版本**：
**Jasminum 插件版本**：

请详细介绍使用中遇到的BUG，按照BUG类型，请在下面 3 个类别中具体说明。如果可以附上截图，那就更好了。

**知网元数据识别失败**

请提供识别失败的PDF文件名，或 Snapshot 条目标题

**非官方转换器下载异常**

非官方转换器下载出现异常，请在这里说明

**其他功能异常**

请详细说明操作步骤，出现的错误提示信息等

**Comment by jiaojiaodubai** [comment]
请按照模板完整填写相关信息以便定位问题
