### ISSUE TITLE
无法安装插件“D:\Software\Zotero\插件\jasminum-v0.2.9.xpi”。它可能无法与该版本的 Zotero 兼容[BUG]

### ISSUE THREAD

**Issue by torfqy** [l0o0/jasminum#313]
**BUG说明**
无法安装插件“D:\Software\Zotero\插件\jasminum-v0.2.9.xpi”。它可能无法与该版本的 Zotero 兼容
请填写下面的版本信息
**Zotero 版本**：7.0.5 (64-bit)
**Jasminum 插件版本**：jasminum-v0.2.9

请详细介绍使用中遇到的BUG，按照BUG类型，请在下面 3 个类别中具体说明。如果可以附上截图，那就更好了。

**其他功能异常**
无法安装插件“D:\Software\Zotero\插件\jasminum-v0.2.9.xpi”
![image](https://github.com/user-attachments/assets/782928a7-6b20-4b1b-99a0-35814374c688)

**Comment by jiaojiaodubai** [comment]
不是bug。Z7 和 Z6 之间的插件架构不同，注意区分版本，可以来[插件市场](https://zotero-chinese.com/plugins/#search=Jasminum)下载
