### ISSUE TITLE
拖入pdf后右下角气泡弹窗显示“抓取知网元数据失败”

### ISSUE THREAD

**Issue by Petrichor728** [l0o0/jasminum#316]
**BUG说明**

请填写下面的版本信息
**Zotero 版本**：7.0.7
**Jasminum 插件版本**：1.0.0-16

请详细介绍使用中遇到的BUG，按照BUG类型，请在下面 3 个类别中具体说明。如果可以附上截图，那就更好了。

**知网元数据识别失败**

请提供识别失败的PDF文件名，或 Snapshot 条目标题
聚变堆第一壁钨材料辐照损伤与燃料滞留行为研究_张学希.pdf
合金元素对掺杂钨基材料力学、抗辐照性能影响研究进展_罗来马.pdf 
等等
![image](https://github.com/user-attachments/assets/62a1c8a2-53a8-42e4-87f7-a05fb3629c72)

**非官方转换器下载异常**

非官方转换器下载出现异常，请在这里说明

**其他功能异常**

请详细说明操作步骤，出现的错误提示信息等

**Comment by YYan99** [comment]
一样，同问

**Comment by choices7** [comment]
我也遇到了这个问题，前端时间还可以正常抓取呢

**Comment by ChenX0707** [comment]
同问，zotero 6.0.36也发现了这个问题，前段时间还可以用的

**Comment by Choi-Daniel** [comment]
一样的问题，求解答！

**Comment by Choi-Daniel** [comment]
![6X(YK1}`%D75JIW}7Z2%)5Q](https://github.com/user-attachments/assets/325fd4a9-a08c-4d6f-b99f-c322ccd25b9f)
同样的文献之前还能抓取，现在就不行了/(ㄒoㄒ)/~~

**Comment by ficus-bit** [comment]
同样的问题，知网第一页的数据可以抓取到，第二页、第三页往后就抓取不到了。

**Comment by jiaojiaodubai** [comment]
知网更换接口，Z7插件已经更新适配，Z6等待修复。而浏览器抓取问题请到[Translators_CN](https://github.com/l0o0/translators_CN)反馈。

**Comment by luosai47** [comment]
直接下架zotero6的插件吧，不要干扰别人
