### ISSUE TITLE
Feature Request：抓取中国知网的文献 DOI

### ISSUE THREAD

**Issue by TomBener** [l0o0/jasminum#32]
问题：Zotero 中使用的 DOI 添加中国知网的文献，提示无法获取。从网页上抓取 https://www.cnki.net/ 上的文献也无法自动获取 DOI，即使该篇文献有 DOI。

希望添加的功能：获取知网 DOI。

**Comment by l0o0** [comment]
能提供一个知网的链接地址么，还有DOI是指知网上的DOI信息么？我记得有些DOI信息可能搜索不到

**Comment by TomBener** [comment]
比如这个：https://www.cnki.net/kcms/doi/10.13502/j.cnki.issn1000-7636.2014.03.002.html

DOI 是 10.13502/j.cnki.issn1000-7636.2014.03.002

![CleanShot 2021-01-10 at 18 30 28@2x](https://user-images.githubusercontent.com/49151155/104120474-29f17800-5372-11eb-9f41-c630234588d0.png)

确实有一些文献没有 DOI，希望可以把有 DOI 的抓下来。

**Comment by l0o0** [comment]
![图片](https://user-images.githubusercontent.com/2743744/104121870-91142a00-537c-11eb-8685-546ff8ce603e.png)
你的意思，是不是在这个地方添加DOI，就能搜索到知网的文献了？

**Comment by TomBener** [comment]
对的，这个地方 Zotero 提示无法找到。

当然通过 Zotero Connector 抓取知网时把 DOI（如果有的话）一并抓下来就更好了。

**Comment by l0o0** [comment]
好的，估计这个功能比较复杂，我回去研究一下。Zotero Connector 那个如果不是搜索页面，应该会保留页面上的DOI信息，你看看有没有

**Comment by TomBener** [comment]
Zotero Connector 就是没有 DOI，是在文章的详情页面，不是在搜索页面。

**Comment by l0o0** [comment]
@TomBener Zotero Connector 已经更新了DOI抓取的translator了，同学可以更新一下试试看

**Comment by TomBener** [comment]
已更新，可以抓取 DOI 了，非常感谢！
