### ISSUE TITLE
没办法批量更新元数据？还是我的问题 

### ISSUE THREAD

**Issue by liujin-r** [l0o0/jasminum#320]
**BUG说明**

请填写下面的版本信息
**Zotero 版本**：
**Jasminum 插件版本**：

请详细介绍使用中遇到的BUG，按照BUG类型，请在下面 3 个类别中具体说明。如果可以附上截图，那就更好了。

**知网元数据识别失败**

请提供识别失败的PDF文件名，或 Snapshot 条目标题

**非官方转换器下载异常**

非官方转换器下载出现异常，请在这里说明

**其他功能异常**

请详细说明操作步骤，出现的错误提示信息等

**Comment by jiaojiaodubai** [comment]
知网更新查询接口，适用 Z7 的最新版茉莉花已经发布，请下载更新，至于Z6需要等待更新，此外注意修改模板原文提交详细的issue信息。

**Comment by jiaojiaodubai** [comment]
同 #323
