### ISSUE TITLE
🛠功能建议[Feature]为什么会自动添加关键词作为标签，希望此功能可以选择性关闭。我在自用标签功能，这样会冲突

### ISSUE THREAD

**Issue by flyros** [l0o0/jasminum#321]
为什么会自动添加关键词作为标签，希望此功能可以选择性关闭。我在自用标签功能，这样会冲突

**Comment by jiaojiaodubai** [comment]
注意：可以用茉莉花的“抓取知网元数据”来抓取条目，但浏览器抓取条目 **不是** 由茉莉花完成的。

大部分 translator 默认把关键词作为 tags，如果不想看可以过滤掉，甚至把它们删除。

![image](https://github.com/user-attachments/assets/8f2240cd-f8d5-4dd0-95dc-aa65c9487518)

**Comment by l0o0** [comment]
> 为什么会自动添加关键词作为标签，希望此功能可以选择性关闭。我在自用标签功能，这样会冲突

Zotero的设置中有对应的设置。
![图片](https://github.com/user-attachments/assets/55aaf721-8ffe-45c3-bc79-1c6b76ebf8a9)
