### ISSUE TITLE
抓取知网元数据失败

### ISSUE THREAD

**Issue by GuGuGuGun** [l0o0/jasminum#323]
**Zotero 版本**：7.0.9-beta.2+bfa9d5b6d (64-bit)
**Jasminum 插件版本**：1.0.0-17

网页插件抓取正常，但在Zotero7内使用茉莉花抓取知网元数据失败（之前是正常的，最近使用zotero的时候突然发现这个问题，然后更新到了最新版本的茉莉花这个问题依然存在），使用的是校园网且未开启代理，DNS也没有进行修改过。同时进行批量更新知网引用数时会提示出现验证码

**Comment by GuGuGuGun** [comment]
![screenshot20241022215025](https://github.com/user-attachments/assets/8b7ba4f2-9487-4e2a-a149-ffc7f3a90219)

**Comment by GuGuGuGun** [comment]
目前更新到1.0.0-18问题依然存在

**Comment by cp-Aurora** [comment]
同失败。似乎已经好几天了。插个眼

**Comment by jiaojiaodubai** [comment]
> 目前更新到1.0.0-18问题依然存在

经测试，标题存在特殊字符（公式），知网搜索本身搜索不到，不是插件bug，是知网的搜索算法决定的。
![image](https://github.com/user-attachments/assets/1a4fec93-d217-4f9f-8b3a-926571a7cc48)

**Comment by jiaojiaodubai** [comment]
同 #316

**Comment by pical-liew** [comment]
> 同失败。似乎已经好几天了。插个眼

+1  之前是靠手动导入pdf再抓取数据的，现在连抓取数据也不行了🤷只能全手动抓取条目，然后将下载的pdf拖动到对应的条目下

**Comment by GuGuGuGun** [comment]
> > 目前更新到1.0.0-18问题依然存在
> 
> 经测试，标题存在特殊字符（公式），知网搜索本身搜索不到，不是插件bug，是知网的搜索算法决定的。 ![image](https://private-user-images.githubusercontent.com/63148861/379089014-1a4fec93-d217-4f9f-8b3a-926571a7cc48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NjAyNTMsIm5iZiI6MTcyOTY1OTk1MywicGF0aCI6Ii82MzE0ODg2MS8zNzkwODkwMTQtMWE0ZmVjOTMtZDIxNy00ZjlmLThiM2EtOTI2NTcxYTdjYzQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA1MDU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3ODZiYjkzZDcxNzczOTI1YjNiN2JiYTM4NzNkMTczZjBiYTkxNGMyNmE3ZWM0MWJiNWJjMTc0ZjI2MDc3OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oJtWLdJBYuL0BiNkUEpOxN3mp8VSMbik-w9PE8E3USA)

已解决，谢谢
