### ISSUE TITLE
🛠功能建议[Feature]微信推文在浏览器打卡能建立条目无法生成本地快照

### ISSUE THREAD

**Issue by smiao6** [l0o0/jasminum#324]
以前微信公众号的推文在浏览器打开可以生成本地快照保存，今天发现只能生成条目，无法建立本地快照了

**Comment by smiao6** [comment]
其他网页可以正常生成本地快照

**Comment by jiaojiaodubai** [comment]
浏览器抓取问题请到[Translators_CN](https://github.com/l0o0/translators_CN)反馈。
