### ISSUE TITLE
拖入文件茉莉花无法知网元数据

### ISSUE THREAD

**Issue by HISUNDAY** [l0o0/jasminum#327]
**BUG说明**
在知网中下载文献PDF后，拖入文件进zotero提示茉莉花无法知网元数据。之前能够识别的也都不能识别了。
根据这些网站的指导，我都完成了，但是依然没有效果。
①https://blog.csdn.net/JWsunshine/article/details/130520910
②https://zotero-chinese.com/user-guide/faqs/update-translators
我认为是抓取功能整体异常，而不是单独某篇文献的问题。
请填写下面的版本信息
**Zotero 版本**：zotero7
**Jasminum 插件版本**：1.0.0-16
请详细介绍使用中遇到的BUG，按照BUG类型，请在下面 3 个类别中具体说明。如果可以附上截图，那就更好了。
**知网元数据识别失败**
请提供识别失败的PDF文件名，或 Snapshot 条目标题
<img width="221" alt="屏幕截图 2024-10-27 142558" src="https://github.com/user-attachments/assets/6c249d84-cf59-400a-8675-ee20b076864f">
其中之一的文献名称：不同针刺频次治疗中风偏瘫的疗效分析
最近重度使用zotero，感谢大家的帮组

**Comment by jiaojiaodubai** [comment]
同 #316，提 issue 前请先尝试更新到最新版，同时搜索是否有相同议题已对此问题作出解答。

**Comment by HISUNDAY** [comment]
感谢您的帮助
