### ISSUE TITLE
zotero connector读取知网论文的日期异常[BUG]

### ISSUE THREAD

**Issue by Jasonw372** [l0o0/jasminum#328]
**BUG说明**

请填写下面的版本信息
**Zotero 版本**：7.0
**Jasminum 插件版本**：1.0.0-18

存在通过zotero connector加载知网学位论文无法获取到日期的情况，或者是获取错误
<img width="351" alt="image" src="https://github.com/user-attachments/assets/df3ff7c2-8a7d-46eb-8b3c-a3f22a4888c1">
<img width="582" alt="image" src="https://github.com/user-attachments/assets/f4e508dc-8b42-4df9-b672-519143ac2ccc">
正常情况是2022 错误的写成了2024，通过pdf获取元数据的过程没有问题，可以得到2022

**Comment by Jasonw372** [comment]
<img width="631" alt="image" src="https://github.com/user-attachments/assets/5a3249cb-3a54-439f-a937-1333d686e5a5">
部分无法获取到日期的和只能获取到2024的

**Comment by jiaojiaodubai** [comment]
浏览器抓取相关问题请到[Translators_CN](https://github.com/l0o0/translators_CN)反馈。

经检查，未能复现。
