### ISSUE TITLE
更新知网引用失败[BUG]

### ISSUE THREAD

**Issue by 91ma** [l0o0/jasminum#334]
更新知网引用失败，显示“知网出现验证码”
![image](https://github.com/user-attachments/assets/67446446-6170-41c0-95df-baaf94c9d901)

版本信息
**Zotero 7**：
**Jasminum 1.0018**：

**Comment by SgAriFool** [comment]
我也遇到了类似的问题, 安装了最新的插件之后(zotero7, Jasminum1.0.0-18)
首先有明明是最新版本的插件, 但是在点击更新的时候还是会显示有更新的版本
![image](https://github.com/user-attachments/assets/97f46eca-9ea7-4e5d-ad65-1731269e5460)

然后就是在使用插件获取文献数据的时候会有
![image](https://github.com/user-attachments/assets/5559e038-cbf1-437b-a395-5e437e3d53ca)

点击关闭之后会有
![image](https://github.com/user-attachments/assets/dda84294-3f7d-4829-9f58-ce1eb125b822)

**Comment by Shariz0419** [comment]
请问一下这个问题是如何解决的

**Comment by 91ma** [comment]
更新DOI号就可以了
