### ISSUE TITLE
知网下不了pdf，万方却可以[BUG]

### ISSUE THREAD

**Issue by Y2043344383** [l0o0/jasminum#335]
**BUG说明**

**Zotero 版本**：7.0
**Jasminum 插件版本**：1.0.0-18

**知网元数据识别失败**
![屏幕截图 2024-11-10 203242](https://github.com/user-attachments/assets/0ae98965-db08-4a27-8b2b-5fec3df95ea5)

非官方中文转换器全部更新了，插件扩展更新也点了，感觉没什么问题，但现在知网就是下不了，万方倒可以
![屏幕截图 2024-11-10 203633](https://github.com/user-attachments/assets/f9ad6689-470b-4378-a7c1-d0383b94a91e)

**Comment by jiaojiaodubai** [comment]
浏览器抓取相关问题请到[Translators_CN](https://github.com/l0o0/translators_CN)反馈。
