### ISSUE TITLE
知网选择相近元数据的窗口异常[BUG]

### ISSUE THREAD

**Issue by YuanXianghe** [l0o0/jasminum#336]
Zotero：7.0.9（64-bit）
Jasminum：1.0.0-18

其他功能异常：

从知网获取元数据时，若存在多个相近的元数据（例如“中国的低生育水平及其影响因素_郭志刚.pdf”），之前版本的插件会弹出窗口供用户选择；更新后弹出空白窗口，窗口标题为“Problem loading page”。

![screenshot](https://github.com/user-attachments/assets/6d80b498-d500-4ef9-81ec-2a86bdc981cf)

**Comment by l0o0** [comment]
目前我发现有不少同学出现类似的问题，不过我这边复现不了。同学你帮我试试，把其他插件禁用后，还会有这个问题嘛？

**Comment by YuanXianghe** [comment]
> 目前我发现有不少同学出现类似的问题，不过我这边复现不了。同学你帮我试试，把其他插件禁用后，还会有这个问题嘛？

在禁用其他插件后，这个问题依然存在。

我看了下调试日志，抓取知网的元数据是成功的，问题可能在窗口显示的部分。

>  (3)(+0005819): itemTree.render(). Displaying Item Tree
> 
> (4)(+0002829): SELECT synced FROM fulltextItems WHERE itemID=? [2904]
> 
> (4)(+0000001): SELECT indexedPages, totalPages AS total FROM fulltextItems WHERE itemID=? [2904]
> 
> (3)(+0000005): [Jasminum] **Jasminum selected item length: 1
> 
> (3)(+0000000): [Jasminum] show menu: search true name false boomark false
> 
> (3)(+0000675): [Jasminum] **Jasminum selected item length: 1
> 
> (3)(+0000000): [Jasminum] show menu: search true name false boomark false
> 
> (3)(+0000673): [Jasminum] getItems items
> 
> (3)(+0000000): [Jasminum] {"author":"郭志刚","keyword":"中国的低生育水平及其影响因素"}
> 
> (3)(+0000000): [Jasminum] Begain to search CNKI 中国的低生育水平及其影响因素 郭志刚
> 
> (3)(+0000000): [Jasminum] {"boolSearch":true,"QueryJson":{"Platform":"","Resource":"CROSSDB","Classid":"WD0FTY92","Products":"","ExScope":"1","SearchType":1,"Rlang":"CHINESE","KuaKuCode":"YSTT4HG0,LSTPFY1C,JUP3MUPD,MPMFIG1A,WQ0UVIAA,BLZOG7CK,PWFIRAGL,EMRPGLPA,NLBO1Z6R,NN3FJMUV","SearchFrom":1,"QNode":{"QGroup":[{"Key":"Subject","Title":"","Logic":0,"Items":[],"ChildItems":[{"Key":"input[data-tipid=gradetxt-1]","Title":"主题","Logic":0,"Items":[{"Key":"input[data-tipid=gradetxt-1]","Title":"主题","Logic":0,"Field":"SU","Operator":"TOPRANK","Value":"中国的低生育水平及其影响因素","Value2":""}],"ChildItems":[]},{"Key":"input[data-tipid=gradetxt-2]","Title":"作者","Logic":0,"Items":[{"Key":"input[data-tipid=gradetxt-2]","Title":"作者","Logic":0,"Field":"AU","Operator":"FUZZY","Value":"郭志刚","Value2":""}],"ChildItems":[]}]},{"Key":"ControlGroup","Title":"","Logic":0,"Items":[],"ChildItems":[]}]}},"pageNum":1,"pageSize":20,"dstyle":"listmode","boolSortSearch":false,"sentenceSearch":false,"productStr":"YSTT4HG0,LSTPFY1C,RMJLXHZ3,JQIRZIYA,JUP3MUPD,1UR4K4HZ,BPBAFJ5S,R79MZMCB,MPMFIG1A,WQ0UVIAA,NB3BWEHK,XVLO76FD,HR1YT1Z9,BLZOG7CK,EMRPGLPA,J708GVCE,ML4DRIDX,PWFIRAGL,NLBO1Z6R,NN3FJMUV,","searchFrom":"资源范围：总库;++中英文扩展;++时间范围：更新时间：不限;++","CurPage":1,"aside":"（主题：中国的低生育水平及其影响因素）AND（作者：郭志刚(模糊)）"}
> 
> (3)(+0000000): [Jasminum] boolSearch=true&QueryJson=%7B%22Platform%22%3A%22%22%2C%22Resource%22%3A%22CROSSDB%22%2C%22Classid%22%3A%22WD0FTY92%22%2C%22Products%22%3A%22%22%2C%22ExScope%22%3A%221%22%2C%22SearchType%22%3A1%2C%22Rlang%22%3A%22CHINESE%22%2C%22KuaKuCode%22%3A%22YSTT4HG0%2CLSTPFY1C%2CJUP3MUPD%2CMPMFIG1A%2CWQ0UVIAA%2CBLZOG7CK%2CPWFIRAGL%2CEMRPGLPA%2CNLBO1Z6R%2CNN3FJMUV%22%2C%22SearchFrom%22%3A1%2C%22QNode%22%3A%7B%22QGroup%22%3A%5B%7B%22Key%22%3A%22Subject%22%2C%22Title%22%3A%22%22%2C%22Logic%22%3A0%2C%22Items%22%3A%5B%5D%2C%22ChildItems%22%3A%5B%7B%22Key%22%3A%22input%5Bdata-tipid%3Dgradetxt-1%5D%22%2C%22Title%22%3A%22%E4%B8%BB%E9%A2%98%22%2C%22Logic%22%3A0%2C%22Items%22%3A%5B%7B%22Key%22%3A%22input%5Bdata-tipid%3Dgradetxt-1%5D%22%2C%22Title%22%3A%22%E4%B8%BB%E9%A2%98%22%2C%22Logic%22%3A0%2C%22Field%22%3A%22SU%22%2C%22Operator%22%3A%22TOPRANK%22%2C%22Value%22%3A%22%E4%B8%AD%E5%9B%BD%E7%9A%84%E4%BD%8E%E7%94%9F%E8%82%B2%E6%B0%B4%E5%B9%B3%E5%8F%8A%E5%85%B6%E5%BD%B1%E5%93%8D%E5%9B%A0%E7%B4%A0%22%2C%22Value2%22%3A%22%22%7D%5D%2C%22ChildItems%22%3A%5B%5D%7D%2C%7B%22Key%22%3A%22input%5Bdata-tipid%3Dgradetxt-2%5D%22%2C%22Title%22%3A%22%E4%BD%9C%E8%80%85%22%2C%22Logic%22%3A0%2C%22Items%22%3A%5B%7B%22Key%22%3A%22input%5Bdata-tipid%3Dgradetxt-2%5D%22%2C%22Title%22%3A%22%E4%BD%9C%E8%80%85%22%2C%22Logic%22%3A0%2C%22Field%22%3A%22AU%22%2C%22Operator%22%3A%22FUZZY%22%2C%22Value%22%3A%22%E9%83%AD%E5%BF%97%E5%88%9A%22%2C%22Value2%22%3A%22%22%7D%5D%2C%22ChildItems%22%3A%5B%5D%7D%5D%7D%2C%7B%22Key%22%3A%22ControlGroup%22%2C%22Title%22%3A%22%22%2C%22Logic%22%3A0%2C%22Items%22%3A%5B%5D%2C%22ChildItems%22%3A%5B%5D%7D%5D%7D%7D&pageNum=1&pageSize=20&dstyle=listmode&boolSortSearch=false&sentenceSearch=false&productStr=YSTT4HG0%2CLSTPFY1C%2CRMJLXHZ3%2CJQIRZIYA%2CJUP3MUPD%2C1UR4K4HZ%2CBPBAFJ5S%2CR79MZMCB%2CMPMFIG1A%2CWQ0UVIAA%2CNB3BWEHK%2CXVLO76FD%2CHR1YT1Z9%2CBLZOG7CK%2CEMRPGLPA%2CJ708GVCE%2CML4DRIDX%2CPWFIRAGL%2CNLBO1Z6R%2CNN3FJMUV%2C&searchFrom=%E8%B5%84%E6%BA%90%E8%8C%83%E5%9B%B4%EF%BC%9A%E6%80%BB%E5%BA%93%3B%2B%2B%E4%B8%AD%E8%8B%B1%E6%96%87%E6%89%A9%E5%B1%95%3B%2B%2B%E6%97%B6%E9%97%B4%E8%8C%83%E5%9B%B4%EF%BC%9A%E6%9B%B4%E6%96%B0%E6%97%B6%E9%97%B4%EF%BC%9A%E4%B8%8D%E9%99%90%3B%2B%2B&CurPage=1&aside=%EF%BC%88%E4%B8%BB%E9%A2%98%EF%BC%9A%E4%B8%AD%E5%9B%BD%E7%9A%84%E4%BD%8E%E7%94%9F%E8%82%B2%E6%B0%B4%E5%B9%B3%E5%8F%8A%E5%85%B6%E5%BD%B1%E5%93%8D%E5%9B%A0%E7%B4%A0%EF%BC%89AND%EF%BC%88%E4%BD%9C%E8%80%85%EF%BC%9A%E9%83%AD%E5%BF%97%E5%88%9A(%E6%A8%A1%E7%B3%8A)%EF%BC%89
> 
> (3)(+0000001): HTTP POST "boolSearch=true&QueryJson=%7B%22Platform%22%3A%22%22%2C%22Resource%22%3A%22CROSSDB%22%2C%22Classid%22%3A%22WD0FTY92%22%2C%22Products%22%3A%22%22%2C%22ExScope%22%3A%221%22%2C%22SearchType%22%3A1%2C%22Rlang%22%3A%22CHINESE%22%2C%22KuaKuCode%22%3A%22YSTT4HG0%2CLSTPFY1C%2CJUP3MUPD%2CMPMFIG1A%2CWQ0UVIAA%2CBLZOG7CK%2CPWFIRAGL%2CEMRPGLPA%2CNLBO1Z6R%2CNN3FJMUV%22%2C%22SearchFrom%22%3A1%2C%22QNode%22%3A%7B%22QGroup%22%3A%5B%7B%22Key%22%3A%22Subject%22%2C%22Title%22%3A%22%22%2C%22Logic%22%3A0%2C%22Items%22%3A%5B%5D%2C%22ChildItems%22%3A%5B%7B%22Key%22%3A%22input%5Bdata-tipid%3Dgradetxt-1%5D%22%2C%22Title%22%3A%22%E4%B8%BB%E9%A2%98%22%2C%22Logic%22%3A0%2C%22Items%22%3A%5B%7B%22Key%22%3A%22input%5Bdata-tipid%3Dgradetxt-1%5D%22%2C%22Title%22%3A%22%E4%B8%BB%E9%A2%98%22%2C%22Logic%22%3A0%2C%22Field%22%3A%22SU%22%2C%22Operator%22%3A%22TOPRANK%22%2C%22Value%22%3A%22%E4%B8%AD%E5%9B%BD%E7%9A%84%E4%BD%8E%E7%94%9F%E8%82%B2%E6%B0%B4%E5%B9%B3%E5%8F%8A%E5%85%B6%E5%BD%B1%E5%93%8D%E5%9B%A0%E7%B4%A0%22%2C%22Value2%22%3A%22%22%7D%5D%2C%…" (2465 chars) to https://kns.cnki.net/kns8s/brief/grid
> 
> (5)(+0000003): CookieSandbox: Being paranoid about channel for kns.cnki.net
> 
> (5)(+0000000): CookieSandbox: Cleared cookies to be sent to kns.cnki.net
> 
> (5)(+0000638): CookieSandbox: Being paranoid about channel for kns.cnki.net
> 
> (5)(+0000000): CookieSandbox: Not tracking received cookies for kns.cnki.net
> 
> (3)(+0000001): HTTP POST https://kns.cnki.net/kns8s/brief/grid succeeded with 200
> 
> (3)(+0000000): [Jasminum] CNKI search return status code : 200
> 
> (3)(+0000001): [Jasminum] CNKI results: 3
> 
> (3)(+0000000): [Jasminum] ** found results
> 
> (3)(+0000000): [Jasminum] 1 中国的低生育率与被忽略的人口风险 免费 郭志刚 国际经济评论 2010-11-27 期刊 72 2558 下载 HTML阅读 AI辅助阅读
> 
> (3)(+0000001): [Jasminum] 2 中国的低生育水平及相关人口研究问题 免费 郭志刚 学海 2010-01-20 期刊 86 2710 下载 HTML阅读 AI辅助阅读
>
> (3)(+0000000): [Jasminum] 3 中国的低生育水平及其影响因素 免费 郭志刚 人口研究 2008-07-29 期刊 243 8381 下载 HTML阅读 AI辅助阅读
> 
> (3)(+0000000): [Jasminum] select window start
> 
> (3)(+0005266): [Jasminum] select window end
> 
> (3)(+0000001): [Jasminum] []
>

**Comment by l0o0** [comment]
请加我v， em90ZXJvc2hhcmU=，我远程看看
https://tool.chinaz.com/tools/base64.aspx，用此解码
