### ISSUE TITLE
算是一个求助，关于标签和条目信息，我在设置内找好久没找到，冒昧来问一下：

### ISSUE THREAD

**Issue by Petrichor728** [l0o0/jasminum#337]
请填写下面的版本信息
**Zotero 版本**：7.0.9
**Jasminum 插件版本**：1.0.0-20
算是一个求助，我在设置内找好久没找到，冒昧来问一下：
1、如何关闭茉莉花自动添加标签功能
![image](https://github.com/user-attachments/assets/42b5f5d7-7b45-48d0-ba7e-2b82de5904d8)
2、现在还会生成一个笔记，显示内容如图，而这部分信息我不需要，如何关闭此功能
![image](https://github.com/user-attachments/assets/105acc79-77ce-4249-b30e-1963b5caa8fa)
![image](https://github.com/user-attachments/assets/7d49de7a-66dc-4094-bca9-8d64c084aa07)

**Comment by jiaojiaodubai** [comment]
1. 关于标签，自动将关键词抓取为标签是多数转换器的默认行为，你基本无法阻止这件事发生，但有一些后续措施，如隐藏或批量删除：
![image](https://github.com/user-attachments/assets/162d2992-a077-4b1a-8d47-e66765cc05d4)


2. 关于茉莉花自动生成的笔记，敬请期待新版。

**Comment by northword** [comment]
![PixPin_2024-12-17_15-13-08](https://github.com/user-attachments/assets/fb728491-b93a-41e0-825d-a5f771ab8033)
