### ISSUE TITLE
能否根据抓取内容，判断是否为核心期刊

### ISSUE THREAD

**Issue by Allwillcome** [l0o0/jasminum#34]
有时候想要获取期刊是否为核心期刊，手动查找过程缓慢，但是在文献的页面，会有核心的标识，不知道能不能一同抓取到 zotero 当中？
![image](https://user-images.githubusercontent.com/35840764/105343857-246f1a00-5c1d-11eb-8fc4-f09e0fa7578f.png)

**Comment by l0o0** [comment]
这个可以的，我之前是没有发现有这方面的需求。我后面会放到extra 这个字段里。

**Comment by Allwillcome** [comment]
> 这个可以的，我之前是没有发现有这方面的需求。我后面会放到extra 这个字段里。

嗯嗯，有时候想删除掉不是核心期刊的文章，还要到网页上查看，不太方便。先谢谢了，等待更新~
ps：关注你挺早了，最开始是看你的博客上发了一篇，给 zotero 加上代理，在校外访问 cnki 的文章。那个时候你还没做茉莉花，没想到你后来直接做了个茉莉花，解决了  zotero 在中文环境中的常见问题，赞！

**Comment by l0o0** [comment]
非常感谢同学的支持，最近事情比较多，我抽空帮收集的需求再汇总下。下个版本再更新一下

**Comment by Allwillcome** [comment]
> 非常感谢同学的支持，最近事情比较多，我抽空帮收集的需求再汇总下。下个版本再更新一下

理解理解，你加入代办列表即可~
