### ISSUE TITLE
MAC环境下，pdf抓取失败问题[BUG]

### ISSUE THREAD

**Issue by LoongYuan** [l0o0/jasminum#340]
**BUG说明**
**Zotero 版本**：7
**Jasminum 插件版本**：1.0.0-20
电脑版本：MacBook pro m1max 64g

请详细介绍使用中遇到的BUG，按照BUG类型，请在下面 3 个类别中具体说明。如果可以附上截图，那就更好了。

**知网pdf抓取失败**
按照网上提供的办法试过，我安装的也是edge，一开始安装pdftk说不符合版本，随后找到适配版本，安装成功，会在终端里输入pdftk时显示很多字符，表明安装成功；在edge中也狂点更新翻译器，但是就是抓取失败，替换源文件中的翻译器也试过，都不行，但是我在外网数据库抓取英文文献就没问题，但是国内的知网万方之类的都无法抓取，希望有人指路解决办法。

**Comment by jiaojiaodubai** [comment]
浏览器抓取相关问题请到[Translators_CN](https://github.com/l0o0/translators_CN)反馈。
pdftk 与 PDF 抓取没有任何关系，转换器更新教程参考[此处](https://zotero-chinese.com/user-guide/faqs/update-translators)。
