### ISSUE TITLE
维普无法抓取PDF

### ISSUE THREAD

**Issue by MF-142** [l0o0/jasminum#344]
**BUG说明**

**Zotero 版本**：7.0.10 (64-bit)
**Jasminum 插件版本**：1.0.0-20

**其他功能异常**

维普中文期刊论文Detail页面 保存至Zotero的时候 保存的类型是网页，不优先抓取PDF

**Comment by jiaojiaodubai** [comment]
浏览器抓取相关问题请到[Translators_CN](https://github.com/l0o0/translators_CN)反馈。
