### ISSUE TITLE
多种方法尝试后中文转换器仍无法加载出来

### ISSUE THREAD

**Issue by bur1bur1** [l0o0/jasminum#346]
![捕获](https://github.com/user-attachments/assets/45570171-d309-4e75-8025-4783d7c45037)

1.卸载其他插件重新优先安装茉莉花插件 失败
2.已确认最新版本 重新下载安装包并安装 失败
3.从wifi切换到流量网络等待超过十分钟 使用/关闭VPN 失败...T T

**Comment by jiaojiaodubai** [comment]
服务器故障，已修复。
