### ISSUE TITLE
茉莉花编译器无法使用了

### ISSUE THREAD

**Issue by MrGongqi** [l0o0/jasminum#347]
**BUG说明**

请填写下面的版本信息
**Zotero 版本**：7.0.11
**Jasminum 插件版本**：1.0.0-20

zotero最近更新到了7.0.11了，发现茉莉花插件无法使用了，点击Update all已经无法获取信息了（如下图）。了

![1](https://github.com/user-attachments/assets/1dda7590-2b89-4c1a-a7a7-19c7344000c6)

**Comment by jiaojiaodubai** [comment]
服务器故障，已修复。

注意，是“翻译器”，不是“编译器”。

**Comment by jiaojiaodubai** [comment]
同 #346
