### ISSUE TITLE
功能请求—为期刊论文增加目录抓取功能

### ISSUE THREAD

**Issue by katana-hydra** [l0o0/jasminum#38]
既然学位论文可以，期刊论文是否也能如此呢？

**Comment by l0o0** [comment]
学位论文的目录及页码信息是从在线阅读那里获取的，比如[这个](https://kreader.cnki.net/Kreader/CatalogViewPage.aspx?dbCode=cdmd&filename=1021002822.nh&tablename=CDFDTEMP&compose=&first=1&uid=WEEvREcwSlJHSldSdmVqeVpQU2Fqd3JUa2QyZFVETFBSZ0pOQkFtYTZEZz0=$9A4hF_YAuvQ5obgVAqNKPCYcEjKensW4ggI8Fm4gTkoUKaID8j8gFw!!]。期刊论文没有找到对应目录的页面信息，所以添加不了
