### ISSUE TITLE
点击抓取以后没有反应

### ISSUE THREAD

**Issue by sunshineharry** [l0o0/jasminum#4]
# 相关信息
- jasminum版本：0.0.4
- 文件名：`基于视觉的自主装配系统轴孔位姿测量研究.pdf`
- 文件目录：`C:\Users\HUAWEI\OneDrive - bjtu.edu.cn\学习资料\Zotero\storage\J3ATH6NU`

# 演示

![output](https://user-images.githubusercontent.com/52942042/89701608-27c26200-d96b-11ea-8ff9-0e1e97948ef3.gif)

**Comment by l0o0** [comment]
@sunshineharry 你在编辑->首选项中 -> 打开茉莉花的文件名格式，把{%t}_{%g} 改为{%t}。你这个格式是只有title，没有姓名，你把设置中的姓名{%g}去掉后再试试

**Comment by sunshineharry** [comment]
我重新试了，成功了，另外，对标签的处理似乎有点问题，我放在另一个issue里了，谢谢大佬！
