### ISSUE TITLE
使用PDFtk生成书签之后，原pdf文件消失

### ISSUE THREAD

**Issue by Msirte** [l0o0/jasminum#40]

**Comment by Msirte** [comment]
使用PDFtk生成书签之后，原pdf文件消失，双击会转到知网的链接，如下图：
<img width="772" alt="QQ截图20210426110259" src="https://user-images.githubusercontent.com/33335070/116023702-3d092900-a67f-11eb-8c9f-49749a4e8b9e.png">
<img width="773" alt="QQ截图20210426110335" src="https://user-images.githubusercontent.com/33335070/116023705-41354680-a67f-11eb-8f1a-35be514f7050.png">

**Comment by l0o0** [comment]
同学，你这里有没有加PDF书签前的PDF文件，可以发给我看看

**Comment by Msirte** [comment]
> 同学，你这里有没有加PDF书签前的PDF文件，可以发给我看看

[超分辨率图像重建的点扩散函数建模与研究_翟宁宁.pdf](https://github.com/l0o0/jasminum/files/6374084/_.pdf)

PDF文件已附上，谢谢。

P.S. 我这里所有的学位论文都会出现这种问题。

**Comment by l0o0** [comment]
![图片](https://user-images.githubusercontent.com/2743744/116026063-7ee89e00-a684-11eb-94a4-cc19b421275b.png)
同学，我下载了你的文件，识别成功后，添加书签后的样子。你可以看下插件是哪个版本，然后可以提供一下日志信息。
![图片](https://user-images.githubusercontent.com/2743744/116026150-ae97a600-a684-11eb-9ede-1360eb3bbf6b.png)
你打开日志窗口，先点clear，然后你选择一个pdf添加书签，这里会有信息出来，然后点左上角保存，上传上来

**Comment by Msirte** [comment]
@l0o0 你好，我所用的插件为0.1.0版本，日志信息附上：

[Debug Output.txt](https://github.com/l0o0/jasminum/files/6375188/Debug.Output.txt)

似乎是保存到了临时文件夹C:\tmp下，我在C:\tmp文件夹下看到有文件一闪而过，应该是被删除了。
我推测可能需要更改一下PDFtk的设置。

谢谢。

**Comment by l0o0** [comment]
因为目录中含有中文名，程序会报错，所以win系统下会新建一个英文的临时文件夹。我怀疑会不会是C盘的权限问题。我回头测试一下

**Comment by Msirte** [comment]
@l0o0 应该不是C盘权限问题，我在“未分类条目”中找到了所有尝试生成目录的pdf文件，它们都在zotero/storage/xxxxxxxx目录下，但是似乎并没有和所属的条目合并，所以看起来像是pdf文件丢失了，见下图：
![image](https://user-images.githubusercontent.com/33335070/116052965-bf5c1200-a6ac-11eb-9426-54ce3eeb63e8.png)

**Comment by l0o0** [comment]
也就是说这些文件其实都已经处理成功了，只不过没有移动到对应的条目里。同学你试试禁用zotfile和bbt这个插件，然后再试试

**Comment by Msirte** [comment]
禁用插件之后，还是没有变化

**Comment by JhonHuGit** [comment]
同样遇到这个问题，可以产生添加目录后的pdf，但文件没有放到对应citation下，而是放到了“我的文库”中
