### ISSUE TITLE
功能期望：为添加的中文条目统一“语言”属性

### ISSUE THREAD

**Issue by windingwind** [l0o0/jasminum#41]
问题描述：
目前从不同来源添加的中文文献语言属性有包括“zh-CN“（理想情况应当是这个），"zh"，“中文”，”中文;“，……导致引用格式不统一（例如et al和等）。

期望的功能：
新添加的条目，所有语言属性包含”中文”，“zh”的统一调整为“zh-CN”

**Comment by l0o0** [comment]
好的，我采纳了
