### ISSUE TITLE
拉取知网元数据后调用 zotfile 重命名导致无法抓取知网元数据

### ISSUE THREAD

**Issue by bluequilt** [l0o0/jasminum#42]
从浏览器导入文献时，“拉取知网元数据后调用zotfile重命名”功能导致会导致无法抓取知网元数据

开启该功能时，当我在浏览器里点插件时，文件加入文献库，并被zotfile改名，然后触发了茉莉花抓取知网的事件，它发现文件名已经被zotfile更改，不符合从知网下载的默认名称，于是抓取失败
在不开启的情况下，会先出现一个名为"Full Text PDF"的文件，然后一瞬间出现两个PDF，另一个的名字符合知网规范，过一会，会再变成只剩一个，留在条目的附件里，并且留下的这个有目录，名称符合zotfile规范。此时符合使用需求。
导入本地PDF并获得题录的需求和在浏览器中获得新文献及题录的需求冲突。

**Comment by l0o0** [comment]
同学你好，你说的那个BUG我好像重复不了。我看了下我的代码，我应该是在抓取知网元数据的时候才会判断是否重命名附件。并不会对浏览器中添加下载的附件处理

**Comment by jiaojiaodubai** [comment]
我不清楚 Zotfile 在对浏览器下载的附件重命名过程中是否会创建临时的顶层条目；目前 Zotfile 已经不维护，而且 Zotero 7 自带重命名之后，茉莉花插件不需要再有这个功能了，此议题过期关闭。
