### ISSUE TITLE
bug report批量导入无法下载pdf

### ISSUE THREAD

**Issue by fredericky123** [l0o0/jasminum#45]
在知网的检索结果页面（图1），如果一次性导入很多个题录，则只能正常导入题录，却不能把pdf都下载下来，
而只有一一点开具体的论文页面（图2），才能自动把pdf下载下来
![image](https://user-images.githubusercontent.com/13982749/138201065-f0d05c72-418f-484f-b948-5ba789e30511.png)
图1
![image](https://user-images.githubusercontent.com/13982749/138201114-79ff82ff-eed7-4737-80ad-5654f2823fcc.png)
图2

**Comment by l0o0** [comment]
这里的下载链接变化了，增加了一步跳转步骤。新翻译器已经换成了海外版下载地址，可以更新下翻译器试试看。学位论文页面的下载也有问题，建议点开下方的在线阅读，进行抓取

**Comment by l0o0** [comment]
新版翻译器可以用了，你可以试试更新。这是隔壁项目[translators_CN中文翻译器](https://github.com/l0o0/translators_CN)。

**Comment by fredericky123** [comment]
> 新版翻译器可以用了，你可以试试更新。这是隔壁项目[translators_CN中文翻译器](https://github.com/l0o0/translators_CN)。

试了，确实有效，感激！
