### ISSUE TITLE
分享：通过item题录直接检索知网期刊的lookup engine

### ISSUE THREAD

**Issue by fredericky123** [l0o0/jasminum#46]
如果能整合进茉莉花，为已导入的没有附件的题录查找并下载pdf附件就更好了
{
		"_name": "CNKI",
		"_alias": "cn.cnki",
		"_description": "Search CNKI",
		"_icon": "https://oversea.cnki.net/kns/Content/images/gb/logo.png",
		"_hidden": false,
		"_urlTemplate": "https://kns.cnki.net/kns8/defaultresult/index?kw={z:title}",
		"_urlParams": {
			"field0": "DOI",
			"q_text0": "{z:DOI}",
			"type": "advance+search",
			"rt": "all"
		},
		"_method": "POST",
		"_urlNamespaces": {
			"rft": "info:ofi/fmt:kev:mtx:journal",
			"z": "http://www.zotero.org/namespaces/openSearch#",
			"": "http://a9.com/-/spec/opensearch/1.1/"
		},
		"_iconSourceURI": "https://oversea.cnki.net/kns/Content/images/gb/logo.png"
	},

**Comment by l0o0** [comment]
好方法哎，最近也在想怎么可以方便的让大家补全知网的PDF。我觉得可以利用Zotero 查找PDF的功能，按照类似你的思路，把查找的源换成知网的，应该可以的。

**Comment by fredericky123** [comment]
> 其实也不必用检索，因为保留的条目里， 一般都会有URL，可以直接双击打开

有道理
