### ISSUE TITLE
无法自动识别

### ISSUE THREAD

**Issue by sunshineharry** [l0o0/jasminum#49]
在导入中文PDF的时候，无法自动从知网加载数据：

插件配置如下：
![image](https://user-images.githubusercontent.com/52942042/139791783-a60d69c7-3ab8-45c4-9cbb-6ada1259bc7d.png)

文件信息如下：
![image](https://user-images.githubusercontent.com/52942042/139791800-19d8a8ea-7c83-4bad-bedb-78cdcb96c87e.png)

**Comment by syheliel** [comment]
现在的搜索方式是将PDF名称匹配`{论文名}_{作者名}`，你这里少了作者名。要解决这个问题可以手动选中PDF右侧信息栏中的PDF名称，在后面加上`_{第一作者名}`，重命名时选中`重命名相关文件`，之后再次抓取就能成功
