### ISSUE TITLE
请求改进对标签的处理

### ISSUE THREAD

**Issue by sunshineharry** [l0o0/jasminum#5]
# 目前对标签的处理方式
- 原始标签信息如下（标签在PDF文件上）
![image](https://user-images.githubusercontent.com/52942042/89732710-3865fb80-da83-11ea-9bd4-881d6bf6eb69.png)
- `抓取知网元数据` 操作完成后（标签在PDF上）
![image](https://user-images.githubusercontent.com/52942042/89732749-782ce300-da83-11ea-8cea-2c20696af8c8.png)
- `添加PDF书签` 操作完成后（标签信息丢失）
![image](https://user-images.githubusercontent.com/52942042/89732786-add1cc00-da83-11ea-998b-8c396a75a9db.png)

# 建议对标签的处理方式
- `抓取知网元数据` 操作完成后，标签可以转移到条目上
- `添加PDF书签` 操作完成后，丢失了标签信息，有点难受呜呜呜

**不过，这还是个很优秀的插件啦，疯狂打call**

**Comment by l0o0** [comment]
@sunshineharry 我没有想到PDF文件，会有标签信息啊。我插件里的逻辑是新生成的一个带书签的PDF，然后把旧的删掉了。没有注意到还有标签信息。可以关注下我的更新，会在005版本里
