### ISSUE TITLE
知网其他格式如.kdh、.nh好像还不支持抓取？

### ISSUE THREAD

**Issue by WhoAmIreal** [l0o0/jasminum#50]
测试了.caj可以抓取，.kdh不能抓取，希望能够添加这两种格式的支持
<img width="364" alt="Snipaste_2021-11-05_17-45-58" src="https://user-images.githubusercontent.com/14259341/140491462-4b0231b3-82b7-42af-80e8-5b053a791181.png">

**Comment by l0o0** [comment]
这个实在是我不知道知网还出这个kdh格式，哈哈

**Comment by WhoAmIreal** [comment]
哈哈，好吧，确实一般下载是caj格式的。某些单位买的数据库，下载下来就是kdh和nh格式的，看来是比较小众了。我尝试直接把后缀改成caj，也能够打开，但是抓取的时候还是不行。
