### ISSUE TITLE
期望功能：提取非知网学位论文PDF文件的书签到笔记

### ISSUE THREAD

**Issue by impermanD** [l0o0/jasminum#51]
现有功能根据知网数据产生的附件笔记特别好用，日后可以导出Markdown文件进一步细化笔记。但是很多期刊文献pdf文件有书签，却无法产生对应的附件笔记。谢谢大神。

**Comment by l0o0** [comment]
Zotfile插件可以提取PDF中的注释笔记，你需要的是这个功能么？

**Comment by impermanD** [comment]
想要提取期刊文章的PDF书签到笔记，大神回复真快。

**Comment by l0o0** [comment]
@impermanD 这个很难啊，因为现在中文的PDF中很难提取到大纲信息，不像英文的。我猜测可能是不是中文的PDF规范可能和英文的不同。而且知网上也没有提供类似学位论文那种书签信息

**Comment by impermanD** [comment]
实在不好意思，今天用zotfile突然发现有这个功能呢。我前几天一个PDF自己做的书签它也能提取。就在右键菜单的Manage Attachments下面的Get Table of Contens里。既然其它插件有这功能，也能省省大神的心，十分感谢您的回复。

**Comment by l0o0** [comment]
不客气的同学。这个issue我关掉了
