### ISSUE TITLE
文献引用数格式问题

### ISSUE THREAD

**Issue by manyouzhe** [l0o0/jasminum#52]
开发者您好！非常感谢您编写的插件，真的非常有用，给我们提供了很大的帮助。
有个小建议，望基于考虑。
现有的引用数中“其他”选项类似这样：CNKI citations: 16[2021-11-29]
Chinese Core Journals: <北大核心, EI, CSCD>
这使得主窗口可能只能显示“CNKI cita...”，这就导致最关键的引用数字“16”，以及期刊等级“EI”只能逐个点击查看，不太直观。
假如将“其他”选项内容改为：Z16<EI>，这使得在主内容窗口可以直观看到目录下所有文献的引用数字和期刊等级，效率极大提高。
![微信截图_20211129105022](https://user-images.githubusercontent.com/35192593/143801859-095b2832-9a1e-4c2b-bbe8-eae41cf1bde9.png)
![微信截图_20211129110028](https://user-images.githubusercontent.com/35192593/143802018-25c5843c-0fa4-4b6c-b8b4-14cc3d34c8e4.png)
望予以考虑。感谢！

**Comment by l0o0** [comment]
好的好的，已经有同学和我反馈了。不过之前Zotero 开发者建议说其他栏里的格式是key : value 的形式。不过这样的话，确实不好用于排序。我后续看看改进一下

**Comment by manyouzhe** [comment]
感谢回复！


我以前一直是采用：“Z”+“引用数”+“期刊等级”，这可以根据引用数排序，不知是否可以借鉴。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "l0o0/jasminum"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月29日(星期一) 中午11:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [l0o0/jasminum] 文献引用数格式问题 (Issue #52)





 
好的好的，已经有同学和我反馈了。不过之前Zotero 开发者建议说其他栏里的格式是key : value 的形式。不过这样的话，确实不好用于排序。我后续看看改进一下
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by alone-tree** [comment]
建议引用数放到最前面，例如23-CNKI cite-other items

**Comment by jiaojiaodubai** [comment]
需要遵守 CSL 规范，统一于 69b1d4a3c9787251961ebe85648820d55f46d9f2。
