### ISSUE TITLE
抓取知网数据无效

### ISSUE THREAD

**Issue by Tongzhao9417** [l0o0/jasminum#54]
今天上午突然无法抓取知网数据，已更换WiFi网络仍无法抓取。电脑型号为：MacBook Air M1。如果需要我上传日志我可以回复中附上。

感谢作者的贡献！非常好的插件！

**Comment by Sharonnn28** [comment]
今天刚下载也无法抓取不知道是不是同样问题。

**Comment by Sharonnn28** [comment]
![image](https://user-images.githubusercontent.com/95841301/145341025-fa92f64f-0e4c-4037-8e18-e931b2c86b67.png)
文件名错误的会报错找不到，文件名正确的没有反应

**Comment by Sharonnn28** [comment]
(3)(+0009888): Setting mode to 'edit'

(3)(+0000001): Refreshing attachment box

(4)(+0000000): SELECT indexedPages, totalPages AS total FROM fulltextItems WHERE itemID=? [15]

(4)(+0000002): SELECT synced FROM fulltextItems WHERE itemID=? [15]

(3)(+0000001): Reloading tags box

(3)(+0000000): Refreshing note editor

(3)(+0000002): Textbox value hasn't changed

(4)(+0000011): SELECT indexedPages, totalPages AS total FROM fulltextItems WHERE itemID=? [15]

(4)(+0000006): SELECT synced FROM fulltextItems WHERE itemID=? [15]

(4)(+0000002): SELECT indexedPages, totalPages AS total FROM fulltextItems WHERE itemID=? [15]

(4)(+0000068): SELECT synced FROM fulltextItems WHERE itemID=? [15]

(4)(+0000002): SELECT indexedPages, totalPages AS total FROM fulltextItems WHERE itemID=? [15]

(3)(+0000007): MIME type application/pdf cannot be handled internally

(3)(+0000002): **Jasminum selected item length: 1

(3)(+0000001): getFilename() deprecated -- use .attachmentFilename

(3)(+0000000): **Jasminum show menu: search true name false boomark false

(3)(+0000582): **Jasminum selected item length: 1

(3)(+0000001): getFilename() deprecated -- use .attachmentFilename

(3)(+0000000): **Jasminum show menu: search true name false boomark false

(3)(+0000615): **Jasminum Updating Selected items

(3)(+0000001): getFilename() deprecated -- use .attachmentFilename

(3)(+0000000): { "author": "李方" "keyword": "非均匀有理B样条在线拟合高速平滑插补法" }

(3)(+0000001): **Jasminum start search

(3)(+0000000): HTTP POST "IsSearch=true&QueryJson=%7B%22Platform%22%3A%22%22%2C%22DBCode%22%3A%22SCDB%22%2C%22KuaKuCode%22%3A%22CJFQ%2CCDMD%2CCIPD%2CCCND%2CCYFD%2CSCOD%2CCISD%2CSNAD%2CBDZK%2CGXDB_SECTION%2CCJFN%2CCCJD%22%2C%22QNode%22%3A%7B%22QGroup%22%3A%5B%7B%22Key%22%3A%22Subject%22%2C%22Title%22%3A%22%22%2C%22Logic%22%3A4%2C%22Items%22%3A%5B%5D%2C%22ChildItems%22%3A%5B%7B%22Key%22%3A%22input%5Bdata-tipid%3Dgradetxt-1%5D%22%2C%22Title%22%3A%22%E7%AF%87%E5%90%8D%22%2C%22Logic%22%3A2%2C%22Items%22%3A%5B%7B%22Key%22%3A%22%22%2C%22Title%22%3A%22%E9%9D%9E%E5%9D%87%E5%8C%80%E6%9C%89%E7%90%86B%E6%A0%B7%E6%9D%A1%E5%9C%A8%E7%BA%BF%E6%8B%9F%E5%90%88%E9%AB%98%E9%80%9F%E5%B9%B3%E6%BB%91%E6%8F%92%E8%A1%A5%E6%B3%95%22%2C%22Logic%22%3A1%2C%22Name%22%3A%22TI%22%2C%22Operate%22%3A%22%3D%22%2C%22Value%22%3A%22%E9%9D%9E%E5%9D%87%E5%8C%80%E6%9C%89%E7%90%86B%E6%A0%B7%E6%9D%A1%E5%9C%A8%E7%BA%BF%E6%8B%9F%E5%90%88%E9%AB%98%E9%80%9F%E5%B9%B3%E6%BB%91%E6%8F%92%E8%A1%A5%E6%B3%95%22%2C%22ExtendType%22%3A1%2C%22ExtendValue%22%3A%22%E4%B8%AD%E8%8B%B1%E6%96%87%E…" (1979 chars) to https://kns.cnki.net/KNS8/Brief/GetGridTableHtml

(5)(+0000010): CookieSandbox: Managing cookies for kns.cnki.net

(5)(+0000000): CookieSandbox: Added cookies for request to kns.cnki.net

(5)(+0016281): CookieSandbox: Managing cookies for kns.cnki.net

(5)(+0000001): CookieSandbox: Slurped cookies from kns.cnki.net

(3)(+0000000): HTTP POST https://kns.cnki.net/KNS8/Brief/GetGridTableHtml succeeded with 200

(3)(+0000001): **Jasminum get item from search

(3)(+0000000): **Jasminum 搜索结果：1

(3)(+0000001): 1 非均匀有理B样条在线拟合高速平滑插补法 李方; 李迪; 黄昕 华南理工大学学报(自然科学版) 2010-08-15 期刊 36 373 下载

(3)(+0000000): **Jasminum start get ref

(3)(+0000000): [ "0": { "dbname": "CJFD2010" "filename": "HNLG201008012" "dbcode": "CJFD" } ]

(3)(+0000001): filename=CJFD2010!HNLG201008012!1!8&displaymode=Refworks&orderparam=0&ordertype=desc&selectfield=&random=0.9317799522629542

(3)(+0000000): HTTP POST "filename=CJFD2010!HNLG201008012!1!8&displaymode=Refworks&orderparam=0&ordertype=desc&selectfield=&random=0.9317799522629542" to https://kns.cnki.net/KNS8/manage/ShowExport

(5)(+0000006): CookieSandbox: Managing cookies for kns.cnki.net

(5)(+0000001): CookieSandbox: Added cookies for request to kns.cnki.net

(1)(+0002511): HTTP POST https://kns.cnki.net/KNS8/Brief/GetGridTableHtml failed with status code 0

(2)(+0000000): Channel status was 2152398850

(1)(+0027488): HTTP POST https://kns.cnki.net/KNS8/manage/ShowExport failed with status code 0

(2)(+0000001): Channel status was 2152398850

**Comment by Ha1ta0** [comment]
同抓取不到知网数据

**Comment by Sharonnn28** [comment]
![image](https://user-images.githubusercontent.com/95841301/145351481-e5cd9438-35e6-4fe8-9dea-dcdd29dbde35.png)

**Comment by Tongzhao9417** [comment]
也可能不是插件的问题，我刚才尝试抓取英文文献，也失败了。可能是zotero的问题？

**Comment by Tongzhao9417** [comment]
经测试是zotero的问题，zotero官方在其github上作出了说明，是因为Amazon cloud的问题所导致的。现在zotero已经恢复了，插件也可以正常使用了。作者可以close这个issue了。

**Comment by l0o0** [comment]
@Tongzhao9417 能详细说说是哪个 issue 么

**Comment by Tongzhao9417** [comment]
> @Tongzhao9417 能详细说说是哪个 issue 么

您好！该问题的出现是因为前段时间Amazon的服务器出现故障，整个zotero都无法使用抓取功能。现Amazon已恢复功能，所以该问题不再出现了，因此我closed issue了。

感谢您的回复！也为您的辛苦工作表示感谢！
