### ISSUE TITLE
求助帖

### ISSUE THREAD

**Issue by HuangYiMing-26** [l0o0/jasminum#57]
开发者您好！你们的插件非常好用，但我在使用的过程中，发现期刊的期数小于10的时候，他会自动补0，如第5期，插件会识别成第05期，但是在写文献列表的时候不希望有这个0。请问这个0应该怎么去掉呢？

**Comment by l0o0** [comment]
这个应该是当时处理时没注意到这点。能提供一下测试示例么，会在下次更新时补上。

**Comment by HuangYiMing-26** [comment]
不好意思，我好像没有测试实例，就是我平时用的时候，比如下载《经济研究》21年第1期某某文献时，这个插件就会将期刊期数识别成2021年第01期。我们在投期刊的时候，一般要写成第1期这样，所以这个0就多余了。如果你们能改进就尽量改进，因为我自己不是做开发的，所以也没办法帮助你们很多。不过还是非常感谢你们开发了这么方便的插件！

**Comment by l0o0** [comment]
我这里有一个临时的代码可以帮你。你打开 Zotero -> 工具 -> 开发者 -> Run Javascript ，把下方的代码复制到 code 中，然后点 Run。记得提前在Zotero 中选择中需要处理多余0的条目，可以选择多个一直处理
```javascript
var items = ZoteroPane.getSelectedItems();
for (let item of items) {
    item.setField("volume", item.getField("volume").replace(/^0/, ''));
    item.setField("issue", item.getField("issue").replace(/^0/, ''));
    await item.saveTx()
}
```
![image](https://user-images.githubusercontent.com/2743744/148152376-394e9256-54f2-4651-8730-b1791cf3ae3d.png)

**Comment by HuangYiMing-26** [comment]
测试有效，非常感谢！

**Comment by l0o0** [comment]
下次有时间，我会写一个调用简单api的插件，你就可以保留这脚本，在菜单里直接调用了。如果没有问题，这个issue我就关掉了

**Comment by HuangYiMing-26** [comment]
好的，没有问题了
