### ISSUE TITLE
功能期望帖：希望目录生成能够支持英文学位论文

### ISSUE THREAD

**Issue by gklzc0608** [l0o0/jasminum#58]
大佬，我有一个问题想请您看看能不能解决。就是我之前用油猴的插件能够把知网的学位论文的PDF下载下来，然后拖到zotero里面后，茉莉花的pdftk插件会自动解析生成目录，我觉得这个功能很方便好用。但是我现在发现我下载的国外的论文的PDF是没有目录的，看起来很不方便，然后就想要是茉莉花的自动生成目录的功能也能支持英文学位论文就好了。所以想问一下您能不能把这个插件改善一下，让他那个自动生成目录的功能也能支持英文学位论文，这样就更好了

**Comment by l0o0** [comment]
@gklzc0608 同学，你说的国外学位论文 PDF 是从知网下载的么？如果是的话，你可以给我一个论文网址，我下载看看

**Comment by gklzc0608** [comment]
@l0o0   不是的，就是在google上直接搜的，因为有些学校的部分论文是开源的，然后还有一些是proquest上下的。因为我之前在知网下的PDF拖到zotero里面就可以自动生成目录，所以想问问看这种也能不能实现

**Comment by l0o0** [comment]
原来如此，因为现在从知网上增加书签的功能，主要是知网上可以找到论文书签的信息，像标题和对应的页码。我是抓取了这些信息，然后用pdftk 添加到pdf里的。像同学你说的那种情况，估计是不好处理

**Comment by gklzc0608** [comment]
哦，原来是这样的原理，也就是说pdf添加目录的前提还是要有书目信息是吧，那看来我还是只能自己编目录，用pdgcnt导进去这种本办法了，哈哈哈。什么时候能有自动识别的目录添加的方式就好了。谢谢大佬了

**Comment by l0o0** [comment]
不客气的。如果没其他问题，这个issue我关掉了

**Comment by gklzc0608** [comment]
好的
