### ISSUE TITLE
功能期望：增加对英文文献设置语言为en

### ISSUE THREAD

**Issue by ayue2019** [l0o0/jasminum#59]
您好，感谢提供如此好用的插件。
请问有没有希望增加：对英文文献设置语言为en，这个功能呢？

**Comment by l0o0** [comment]
同学可以试试在这个地方 
![image](https://user-images.githubusercontent.com/2743744/148682243-73f16e82-72da-48dc-bed9-31ee13acdf6b.png)
把语言设置为en，你看看菜单里的功能可以实现你的需求么？
