### ISSUE TITLE
增加提取pdf书签目录的功能

### ISSUE THREAD

**Issue by krisfans** [l0o0/jasminum#60]
您好，感谢您的插件。您的插件能通过PDFtk给通过知网下载的文件添加书签的功能很好用，但是能否反过来？

因为知网PDF本身是没有书签的，下载的PDF文档通过您的插件增加了书签后只能定位到某一页而不是某个具体的位置，所以我倾向于到万方下载有书签的PDF。但是您的插件无法为万方PDF提取书签生成目录，不方便预览。可否利用`pdftk in.pdf dump_data_utf8 output report.txt`提供该功能？

具体描述
万方PDF
![Snipaste_2022-01-14_16-54-05](https://user-images.githubusercontent.com/57793534/149487260-7f266ef1-b95a-42af-b972-14a0f5139112.png)
知网PDF
![Snipaste_2022-01-14_16-54-43](https://user-images.githubusercontent.com/57793534/149487333-f28bbdef-eaba-4c04-80d8-748ce3667c10.png)

**Comment by l0o0** [comment]
@krisfans 之前我担心书签添加的成功率，在菜单弹出设置时，限制了许多条件，其中有个馆藏目录信息为CNKI(大写)。这个限制我前几天在0.1.4 版本中取消了，同学你可试试这个版本，看看能否为万方PDF添加书签。不过这书签的信息也还是会从知网上搜索，如果搜索不到就不能添加了

**Comment by zyx335588** [comment]
@krisfans 
万方下载的PDF都进行了加密，限制了部分操作，要提取书签需要先解除加密。
pdftk没有提供不知道密码的情况下的解密功能，需要用其它软件完成。
解密后的pdf文件可以直接用zotfile插件提取目录。
zotero note中的链接好像只能定位到页，无法精确到页面坐标；所以即便有页面坐标，zotfile提取到note中的链接也只能定位到页。
