### ISSUE TITLE
5.0.97beta65版zotero导入插件时提示版本不兼容

### ISSUE THREAD

**Issue by Darkluna999** [l0o0/jasminum#62]
版本：5.0.97-beta.65+15ae72d14
弹窗提示：无法安装插件“%S”。它可能无法与该版本的 Zotero 兼容。

**Comment by Darkluna999** [comment]
补充：
已安装0.0.4
覆盖安装0.1.3没有问题
但升级0.1.4报错

**Comment by l0o0** [comment]
@Darkluna999 0.1.5 版本安装会有问题么？

**Comment by Darkluna999** [comment]
我已经回退到稳定发行版了。。。

**Comment by l0o0** [comment]
@Darkluna999 Zotero 6 和新版插件，会有兼容问题么？

**Comment by Darkluna999** [comment]
> @Darkluna999 Zotero 6 和新版插件，会有兼容问题么？

没有了。。我居然忘记关闭issue了哈哈哈哈哈哈哈抱歉抱歉
