### ISSUE TITLE
Jasminum is incompatible with Zotero 6.0- beta.1

### ISSUE THREAD

**Issue by pureal** [l0o0/jasminum#63]
![image](https://user-images.githubusercontent.com/3120327/153327363-4957a8e7-d4c3-42ab-9f4c-6f2c8abde703.png)

**Comment by yx1100** [comment]
问题相同

**Comment by synnac** [comment]
同一个问题，希望能早点解决

**Comment by zr47175** [comment]
6.0beta不适配了，大佬快修复一下下

**Comment by l0o0** [comment]
同学们反馈已经收到了

**Comment by gengxiangc** [comment]
感谢大佬
