### ISSUE TITLE
0.1.6显示不全

### ISSUE THREAD

**Issue by fredericky123** [l0o0/jasminum#65]
![image](https://user-images.githubusercontent.com/13982749/156878789-4c0bcfee-ad08-4c2e-91a7-7b8b9b607b74.png)
如图

**Comment by l0o0** [comment]
能截一个大图么？你这应该是mac系统。这是Ubuntu 的截图
![image](https://user-images.githubusercontent.com/2743744/156885922-79d8867c-9916-4543-b39b-c1fd538b65ea.png)

**Comment by fredericky123** [comment]
![image](https://user-images.githubusercontent.com/13982749/156886643-8ad228d6-7836-480f-8db3-fc406e5a64bc.png)
mac系统

**Comment by l0o0** [comment]
嗯，应该是因为英文太长了，导致空间不够，我优化下菜单上的英文说明

**Comment by jiaojiaodubai** [comment]
完成于 8d4e525671bda397e5e9dff0c2ebd0b24d91525e
