### ISSUE TITLE
PDFtk添加书签时失败

### ISSUE THREAD

**Issue by ACE220284Luffy** [l0o0/jasminum#66]
![image](https://user-images.githubusercontent.com/87253240/157392586-1f868d78-6d10-4ce5-bab2-9f03b31d4510.png)
![image](https://user-images.githubusercontent.com/87253240/157392629-988ae9a3-14f8-4ff5-bdee-59bc9620d0b8.png)
之前添加标签功能好好的，最近出现上述问题，无法添加标签，望指导。ps.前段时间重新安装了一下Java，不知道是不是这个原因，如果是该怎么解决呢？（win10系统）

**Comment by ACE220284Luffy** [comment]
是在添加学位论文标签时出现的问题

**Comment by l0o0** [comment]
有没有试过重装pdftk呢？

**Comment by ACE220284Luffy** [comment]
> 试过了，还是不行

**Comment by ACE220284Luffy** [comment]
> 试过了，还是不行

**Comment by l0o0** [comment]
@ACE220284Luffy 有同学反馈，不安装Java可以运行，你试试卸载java看看

**Comment by ACE220284Luffy** [comment]
> @ACE220284Luffy 有同学反馈，不安装Java可以运行，你试试卸载java看看

抱歉，问题解决了没有更新到这里，应该大概或许很可能那个同学就是我，还是很感谢

**Comment by weihecrazy** [comment]
我也有这个问题，不过我的返回值是1
![image](https://user-images.githubusercontent.com/31305871/236722771-c6c23511-186b-4646-ba3b-29e9feeab622.png)

**Comment by 10ThreeStones29** [comment]
<img width="347" alt="image" src="https://user-images.githubusercontent.com/121242370/236759745-f731fa1c-67ec-4108-8a6a-37f43e683322.png">
同样在添加学位论文时出现问题，但是我没有安装过java，请问有别的方法解决吗

**Comment by 10ThreeStones29** [comment]
> 我也有这个问题，不过我的返回值是1 ![image](https://user-images.githubusercontent.com/31305871/236722771-c6c23511-186b-4646-ba3b-29e9feeab622.png)

我也是，有点巧

**Comment by ACE220284Luffy** [comment]
我之前的返回值是3，我不清楚我的解决方法解决你的返回值为1的问题能不能有效，你可以看一下我这里（https://gitee.com/zotero-chinese/zotero-chinese/issues/I4XG1I#note_9169495_link）的操作


***@***.***
 
发件人： 10ThreeStones29
发送时间： 2023-05-08 15:17
收件人： l0o0/jasminum
抄送： ACE220284Luffy; State change
主题： Re: [l0o0/jasminum] PDFtk添加书签时失败 (Issue #66)
同样在添加学位论文时出现问题，但是我没有安装过java，请问有别的方法解决吗 
―

**Comment by ACE220284Luffy** [comment]
我之前的返回值是3，我不清楚我的解决方法解决你的返回值为1的问题能不能有效，你可以看一下我这里（https://gitee.com/zotero-chinese/zotero-chinese/issues/I4XG1I#note_9169495_link）的操作


***@***.***
 
发件人： 10ThreeStones29
发送时间： 2023-05-08 15:17
收件人： l0o0/jasminum
抄送： ACE220284Luffy; State change
主题： Re: [l0o0/jasminum] PDFtk添加书签时失败 (Issue #66)
我也有这个问题，不过我的返回值是1 
我也是，有点巧

**Comment by ACE220284Luffy** [comment]
我之前的返回值是3，我不清楚我的解决方法解决你的返回值为1的问题能不能有效，你可以看一下我这里（https://gitee.com/zotero-chinese/zotero-chinese/issues/I4XG1I#note_9169495_link）的操作。


***@***.***
 
发件人： WEIHE
发送时间： 2023-05-08 10:47
收件人： l0o0/jasminum
抄送： ACE220284Luffy; State change
主题： Re: [l0o0/jasminum] PDFtk添加书签时失败 (Issue #66)
我也有这个问题，不过我的返回值是1

**Comment by weihecrazy** [comment]
看过了，可我是win11的系统 
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年5月8日 17:32
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [l0o0/jasminum] PDFtk添加书签时失败 (Issue #66)
        
      
    
  

我之前的返回值是3，我不清楚我的解决方法解决你的返回值为1的问题能不能有效，你可以看一下我这里（https://gitee.com/zotero-chinese/zotero-chinese/issues/I4XG1I#note_9169495_link）的操作。





***@***.***

 

发件人： WEIHE

发送时间： 2023-05-08 10:47

收件人： l0o0/jasminum

抄送： ACE220284Luffy; State change

主题： Re: [l0o0/jasminum] PDFtk添加书签时失败 (Issue #66)

我也有这个问题，不过我的返回值是1
