### ISSUE TITLE
更新了zotero6.0之后，获取cnki文章失败？

### ISSUE THREAD

**Issue by uplanning** [l0o0/jasminum#68]
macos，下载安装了新的zotero6，茉莉花配置中更新了翻译器，浏览器中手动点击了update，cnki文章页面可以识别，但点击按钮获取后取不到信息，文章标题显示【0】，可以下载pdf会自动命名为【0】，麻烦看看是什么问题，谢谢！

**Comment by l0o0** [comment]
是否所有的文献都是这种情况？能提供下URL，我这边测试一下

**Comment by uplanning** [comment]
我上午试了，目前我这里是所有文章都这样。。昨天5.0下载还正常，今早升级完6.0就不通了。是否可以告知邮箱，我可以截图发你

**Comment by l0o0** [comment]
可以，这里Ctrl + V 也可以贴图

**Comment by uplanning** [comment]
给插件说明上提供的gmail邮箱发了录屏文件，谢谢

**Comment by l0o0** [comment]
@uplanning 开心，至少你PDF能正常下载。你先禁用zotfile插件试试看

**Comment by uplanning** [comment]
禁用zotfile再重启结果彻底进不去zotero了




起始为Zotero中存在错误。

您可以在Zotero论坛中报告此问题。

Error: cleanDOI: argument must be a string
    cleanDOI@chrome://zotero/content/xpcom/utilities/utilities.js:407:15
    _cacheKeyMappings@chrome://zotero/content/xpcom/retractions.js:773:21
From previous event:
    ZoteroService@file:///Applications/Zotero.app/Contents/Resources/components/zotero-service.js:346:7
    @chrome://zotero/content/include.js:4:14

**Comment by l0o0** [comment]
我zotero 6 禁用之后，很正常呐。你是不是有其他插件，你试试把其他都禁用了。或者你连zotero 都打不开

**Comment by uplanning** [comment]
是的，打不开了。。我再想想办法吧

**Comment by l0o0** [comment]
@uplanning 你不能打开解决了么？有没有试过把配置目录里extensions 中的文件先清空。

**Comment by uplanning** [comment]
删掉重装之后OK了，正在痛苦的恢复文献目录
