### ISSUE TITLE
您好，请问PDF书签怎么使用？我下载了PDFtk，但是不知道在何处设置路径。

### ISSUE THREAD

**Issue by Lighting-Zhu** [l0o0/jasminum#7]

**Comment by l0o0** [comment]
你好，如果是win10系统，安装了[PDFtk server](https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/pdftk_server-2.02-win-setup.exe)，一定注意是这个server版本。然后你去找那个安装目录，记住是安装目录下的那个bin目录才行
![图片](https://user-images.githubusercontent.com/2743744/89970977-a2052600-dc8c-11ea-868d-19b72248ebbc.png)
可以点击选择那个选项，选择对应的目录

**Comment by Lighting-Zhu** [comment]
路径问题以及解决，但是还没有使用过。
谢谢你。

**Comment by GuokaiLiu** [comment]
感谢分享！顺便说下macos(10.15)用户：
下载：https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/pdftk_server-2.02-mac_osx-10.11-setup.pkg
路径：/opt/pdflabs/pdftk/.

**Comment by l0o0** [comment]
@GuokaiLiu 感觉同学的提示。Mac系统我确实没有测试过

**Comment by Lighting-Zhu** [comment]
好想知道有没有万方的插件。我伸手党自己觉得自己要求太多了，匿了。

**Comment by l0o0** [comment]
@GuokaiLiu 知网的数据库应该包括了万方的吧

**Comment by GuokaiLiu** [comment]
> @GuokaiLiu 感觉同学的提示。Mac系统我确实没有测试过

 今天发现`translators_CN`与`jasminum`竟然都是出自Git主只手，厉害了！

不过在Chrome使用百度学术的时候，点击插件可以显示勾选的界面，却没法下载同步到Zotero文件夹，

不知道是否有遇到过类似的问题？

谢谢！

**Comment by Python-Zhou** [comment]
能不能简单做个说明怎么用PDFtk制作学位论文书签。

**Comment by luqinghui** [comment]
> 能不能简单做个说明怎么用PDFtk制作学位论文书签。

这个不应该去看pdftk的文档吗？或者翻一下作者添加书签的代码，我猜是这个函数，你可以看看：
![image](https://user-images.githubusercontent.com/5338140/99869300-c619c100-2c04-11eb-98f5-b9870d9b5848.png)

**Comment by l0o0** [comment]
@Python-Zhou 同学好，在这个插件里，我是借助pdftk这个软件来添加书签的，因为我觉得用JS来完成这个工作感觉比较困难。上面那个同学说得对，具体的细节可以参考代码里[addBookmark](https://github.com/l0o0/jasminum/blob/master/chrome/content/scripts/jasminum.js#L848)，具体细节可以参考PDFtk [链接1](https://www.pdflabs.com/docs/pdftk-cli-examples/) [链接2](https://www.pdflabs.com/docs/pdftk-man-page/)。PDFtk具体是用什么样的文件来当作添加书签的输入文件，你可以用 pdftk 把已经添加好书签的 PDF 用`dump_data_utf8` 试试看输出的信息

**Comment by liangx15** [comment]
请问已经安装好PDFtk server，且设置好目录，但是在zotero里点击添加书签一直没有反应，该怎么解决呢？谢谢

**Comment by l0o0** [comment]
@liangx15 同学，你截图下你安装的插件列有，看看有没有冲突的。最近发现Scite 这个插件有冲突，装了之后书签添加没有效果

**Comment by liangx15** [comment]
> @liangx15 同学，你截图下你安装的插件列有，看看有没有冲突的。最近发现Scite 这个插件有冲突，装了之后书签添加没有效果

![image](https://user-images.githubusercontent.com/58251222/103144464-9e1e0000-4764-11eb-84a7-ec883b01c1b5.png)

没有安装Scite，之前添加pdf书签是好用的，最近这几天发现没有反应了。

**Comment by l0o0** [comment]
@liangx15 再提供下Jasminum的版本号，以及有没有什么错误的提示信息？

**Comment by liangx15** [comment]
> @liangx15 再提供下Jasminum的版本号，以及有没有什么错误的提示信息？

是0.0.8版本，错误信息有一条：[JavaScript Error: "TypeError: readerHTML.querySelector(...) is null" {file: "chrome://jasminum/content/scripts/jasminum.js" line: 772}]，不知是否有参考价值。

**Comment by l0o0** [comment]
@liangx15 是部分论文不能添加，还是都出现问题了。你可以给一个文章的URL给我，我自己测试一下

**Comment by liangx15** [comment]
> @liangx15 是部分论文不能添加，还是都出现问题了。你可以给一个文章的URL给我，我自己测试一下

目前我这里的学位论文都不能添加。

https://nxgp.cnki.net/kcms/detail?v=3uoqIhG8C447WN1SO36whLpCgh0R0Z-iVBgRpfJBcb4JAybTo8M4luIPFfQ9zWdBSPuj3MqXfmaQbvAwD68oyXibsILvL9sL&uniplatform=NZKPT

您可以测试一下，谢谢

**Comment by l0o0** [comment]
@liangx15 正常url是以https://kns.cnki.net 开始，你的为什么是nxgp.cnki开头的，你是从哪里进入知网的。然后你试试把你条目里面的网址，换成kns.cnki.net 开头的，再试试看

**Comment by liangx15** [comment]
> @liangx15 正常url是以https://kns.cnki.net 开始，你的为什么是nxgp.cnki开头的，你是从哪里进入知网的。然后你试试把你条目里面的网址，换成kns.cnki.net 开头的，再试试看

您好，我就是从学校知网数据库入口进入的，我发现在知网的搜索页是kns.cnki.net 开头，但是点击进入某篇论文的详情页之后url就变成了nxgp.cnki开头的网址。

![image](https://user-images.githubusercontent.com/58251222/103182888-d13dcc00-48e9-11eb-97d5-a890f559ee7a.png)

**Comment by liangx15** [comment]
> @liangx15 正常url是以https://kns.cnki.net 开始，你的为什么是nxgp.cnki开头的，你是从哪里进入知网的。然后你试试把你条目里面的网址，换成kns.cnki.net 开头的，再试试看

您好，我发现问题，是我们学校cnki提供了两个访问入口，我换另外一个访问入口就正常了！您开发的功能没问题，非常好用，感谢作者！！！

**Comment by l0o0** [comment]
@liangx15 我今天从旧版进去，在搜索结果页面点开的链接进行后的地址就是nxgp开头，估计是旧版的地址。开头网址变了，可能导致插件里设置的cookie出现问题，导致不能正常获取信息

**Comment by liangx15** [comment]
> @liangx15 我今天从旧版进去，在搜索结果页面点开的链接进行后的地址就是nxgp开头，估计是旧版的地址。开头网址变了，可能导致插件里设置的cookie出现问题，导致不能正常获取信息

确实是，旧版本进去就有问题，新版入口就正常了

**Comment by fredericky123** [comment]
https://www.cnki.net/
我从这里进去，打开https://kns.cnki.net/kns8/defaultresult/index
还是不能正常生成pdf书签，路径已配置

**Comment by l0o0** [comment]
> 
> 
> https://www.cnki.net/
> 我从这里进去，打开https://kns.cnki.net/kns8/defaultresult/index
> 还是不能正常生成pdf书签，路径已配置

是指抓取条目后，学位论文没有自动添加书签？

**Comment by fredericky123** [comment]
> > https://www.cnki.net/
> > 我从这里进去，打开https://kns.cnki.net/kns8/defaultresult/index
> > 还是不能正常生成pdf书签，路径已配置
> 
> 是指抓取条目后，学位论文没有自动添加书签？

是的

**Comment by l0o0** [comment]
> 
> 
> > > https://www.cnki.net/
> > > 我从这里进去，打开https://kns.cnki.net/kns8/defaultresult/index
> > > 还是不能正常生成pdf书签，路径已配置
> > 
> > 
> > 是指抓取条目后，学位论文没有自动添加书签？
> 
> 是的

右键手动添加，正常么？有时自动添加会有BUG，不一定会成功。估计是没有触发

**Comment by fredericky123** [comment]
右键怎么添加？
![image](https://user-images.githubusercontent.com/13982749/103773443-04a8f500-5066-11eb-9406-510107e48c37.png)

**Comment by fredericky123** [comment]
我测试了下，macos 11也应该用提到的那个链接：
下载：https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/pdftk_server-2.02-mac_osx-10.11-setup.pkg 

建议把提示里的“After installation, open a Terminal, type pdftk and press Return”标红显示

**Comment by l0o0** [comment]
@fredericky123 请问同学，这个提示是在哪里的？

**Comment by fredericky123** [comment]
https://github.com/l0o0/jasminum
![image](https://user-images.githubusercontent.com/13982749/106376253-7a3a8380-63ce-11eb-8589-307f18b090b6.png)

我感觉是macos 都得通过上述链接下载，因为官方macos下载默认给的链接是个旧程序

**Comment by l0o0** [comment]
明白了 @fredericky123

**Comment by yip01med** [comment]
访达试一下，shift+command+G: 输入：/opt/pdflabs/pdftk/，选择bin确认，
