### ISSUE TITLE
Not compatible with zotero 6.0.3

### ISSUE THREAD

**Issue by Tsingwaa** [l0o0/jasminum#70]
cannot install the add-on.

**Comment by pengwork** [comment]
![image](https://user-images.githubusercontent.com/31396670/160264030-564b2e46-a0c4-4683-b931-3e010cb051ff.png)

@Tsingwaa  hi，我开始也提示与Zotero版本不匹配，但是你多尝试几次（我是三次），每次把提示框关掉就好，然后你会看到插件的自动更新提示，提示你更新jasminum，把它更新就可以使用了。

**Comment by Tsingwaa** [comment]
@pengwork 好的，谢谢！
