### ISSUE TITLE
添加中文PDF时，爬取知网元数据后，附件丢失

### ISSUE THREAD

**Issue by shxzzxz** [l0o0/jasminum#74]
拖拽文件到zotero中添加中文PDF时（例如：[光纤光栅传感器监测混凝土简支梁裂缝的实验研究](https://kns.cnki.net/KCMS/detail/detail.aspx?dbcode=CJFD&dbname=CJFD2013&filename=JJZZ201301038&v=)，爬取知网元数据后，附件丢失，后查找发现，PDF在又创建的一英文条目下归到未分类库中，
![image](https://user-images.githubusercontent.com/49810787/161383215-c3d90764-735b-44cc-acf0-b1fd88cea4c9.png)
且条目URL变为（http://www.opticsjournal.net/Abstract.htm?id=OJ121122000047gNjPmS），为其对应期刊网链接，
撤销检索元数据对PDF手动抓取元数据不会产生此情况

**Comment by shxzzxz** [comment]
抱歉，条目URL变为https://www.opticsjournal.net/Articles/OJ121122000047gNjPmS/Abstract

**Comment by l0o0** [comment]
这个真奇怪，我研究一下

**Comment by shxzzxz** [comment]
确实是冲突了，感谢感谢
