### ISSUE TITLE
用zotero插件无法抓取pdf元素

### ISSUE THREAD

**Issue by sometimesstudy** [l0o0/jasminum#75]
6.0.5-beta.1版本，浏览器用zotero插件抓取知网文章，只显示full text pdf，但是无法抓取pdf
![image](https://user-images.githubusercontent.com/51228607/161412942-13dd6ed1-fc5e-4533-ad19-0aa77903b539.png)

**Comment by l0o0** [comment]
啊，最近有个新的翻译器要出来。目前在测试中
