### ISSUE TITLE
国家标准中的作者抓取有问题，应该抓取起草人，而不是起草单位

### ISSUE THREAD

**Issue by redleafnew** [l0o0/jasminum#76]
如：https://chn.oversea.cnki.net/KCMS/detail/detail.aspx??sfield=fn&QueryID=10&CurRec=2&recid=&FileName=SCSF00073857&DbName=SCSF&DbCode=SCSF&yx=&pr=&URLID=

应该抓取起草人，而不是起草单位：

起草人：张奎彪; 高胜普; 郭峰; 潘满; 孟翠翠; 周伟生; 柴云坤; 尤华; 韩世国; 程振超
起草单位：吉林省艾斯克机电股份有限公司; 中国动物疫病预防控制中心(农业农村部屠宰技术中心); 中国农业机械化科学研究院; 福瑞珂食品设备(济宁)有限公司; 河北滦平华都食品有限公司; 北票市宏发食品有限公司

谢谢老大。

**Comment by l0o0** [comment]
这个页面，在翻译器里不能识别。老师是用什么翻译器的？

**Comment by redleafnew** [comment]
没有注意，你的CNKI不可以吗？

**Comment by l0o0** [comment]
@redleafnew 不可以的。我看里面的类型只有这些
```
var dbType = {
		CJFQ: "journalArticle",
		CJFD: "journalArticle",
		CAPJ: "journalArticle",
		SJES: "journalArticle",
		SJPD: "journalArticle",
		SSJD: "journalArticle",
		CCJD: "journalArticle",
		CDMD: "journalArticle",
		CYFD: "journalArticle",
		CDFD: "thesis",
		CMFD: "thesis",
		CLKM: "thesis",
		CCND: "newspaperArticle",
		CPFD: "conferencePaper",
		IPFD: "conferencePaper",
		SCPD: "patent"
	};
```
并没有SCSF 这个

**Comment by redleafnew** [comment]
好的，但这个文献确实是个国家标准，文献类型倒是不要紧，如果能把作者引用对也可以，Zotero中现在也没有标准这个选项。

**Comment by zepinglee** [comment]
> 应该抓取起草人，而不是起草单位：

从示例来看，GB/T 7714—2015 更倾向于著录起草单位而不是起草人。
<img width="718" alt="Screen Shot 2022-04-26 at 17 33 25" src="https://user-images.githubusercontent.com/12290822/165270019-17e58f75-48fa-4e85-a414-c901e7394dfa.png">

**Comment by zepinglee** [comment]
> Zotero中现在也没有标准这个选项。

我最近发现，可以使用 Report 类型，但是在 `Extra` 中填写 `Type: standard` 一行，可以在穿给 citeproc 处理时转为“标准”类型。
<img width="326" alt="Screen Shot 2022-04-26 at 17 39 57" src="https://user-images.githubusercontent.com/12290822/165271297-6a008b4b-e62b-4b86-8ad3-9819ffcdb040.png">
<img width="727" alt="Screen Shot 2022-04-26 at 17 40 08" src="https://user-images.githubusercontent.com/12290822/165271320-3c65e15d-878f-4ec4-81cb-28d7a3ab2348.png">

**Comment by redleafnew** [comment]
> > 应该抓取起草人，而不是起草单位：
> 
> 从示例来看，GB/T 7714—2015 更倾向于著录起草单位而不是起草人。 <img alt="Screen Shot 2022-04-26 at 17 33 25" width="718" src="https://user-images.githubusercontent.com/12290822/165270019-17e58f75-48fa-4e85-a414-c901e7394dfa.png">

也是哦

**Comment by zepinglee** [comment]
最近在写“全国标准信息公共服务平台”（<https://std.samr.gov.cn/>）的 translator 时（<https://github.com/l0o0/translators_CN/pull/133>）发现，国标中著录的其实不是“起草单位”而是“归口单位”。比如上面国标中的文献 GB/T 3792.4—2009 《[文献著录 第4部分：非书资料](https://std.samr.gov.cn/gb/search/gbDetailed?id=71F772D7D040D3A7E05397BE0A0AB82A)》和 GY/T 202.2—2007《[广播电视音像资料编目规范 第2部分：广播资料](https://std.samr.gov.cn/hb/search/stdHBDetailed?id=8B1827F147EDBB19E05397BE0A0AB44A)》。对应知网的链接分别是 《[文献著录　第4部分：非书资料](https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=SCSF&dbname=SCSF&filename=SCSF00070218&uniplatform=NZKPT&v=9klx80ksI65mmkcXJyoPUtsxQXJ9tJ2hIpOt04tU_dEDJ_TdoXMU2LCmc3W15cPL)》和《[广播电视音像资料编目规范 第2部分:广播资料](https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=SCSD&dbname=SCSD&filename=SCSD000005140697&uniplatform=NZKPT&v=Oph4xQC-wrUL83BwXsCRvSoM53G35j0AAkdPEHA-IjnpiqArIHcHCB8wWydQedq_tGiHo7GUiYs%3d)》，但是保存在了“发布单位”一栏，而且其中还多了“国家质量监督检验检疫总局”。所以总体感觉知网的标准文献数据不够规范，而且更新也不及时。建议从全国标准信息公共服务平台这样的 .gov.cn 网站进行抓取。

**Comment by jiaojiaodubai** [comment]
> 如：https://chn.oversea.cnki.net/KCMS/detail/detail.aspx??sfield=fn&QueryID=10&CurRec=2&recid=&FileName=SCSF00073857&DbName=SCSF&DbCode=SCSF&yx=&pr=&URLID=

现在知网翻译器已经支持抓取以上示例链接，主要责任人已修正为归口单位。
