### ISSUE TITLE
[Bug Report] 拆分名字时，遇到少数民族或者复姓时出现问题

### ISSUE THREAD

**Issue by zombie110year** [l0o0/jasminum#78]
如图
![image](https://user-images.githubusercontent.com/36528430/161427239-7f24c2a1-08aa-4178-a5a0-e53c4e8d2f57.png)

另外，我看到源代码里拆分中文名字是这样的：

```js
} else if (creator.firstName === "") { // For Chinese Name,名为空
    var chineseName = creator.lastName || creator.firstName;
    creator.lastName = chineseName.charAt(0);
    creator.firstName = chineseName.substr(1);
}
```

只取第一个字做名字的话，在遇到少数民族的名字和复姓名字时就会划分错误。
但是这些名字比较少见，就算出错了也可以手动改过来，不知道作者愿不愿意修复这个 BUG？

**Comment by l0o0** [comment]
少数民族的作者姓名，如果有分隔符是可以区分的。我就怕复姓，因为比如欧阳龙，你不知道是姓欧还是欧阳。这个不是本人告诉你，不好判断。不过有一些可能会比较好判断，没有这些复性和单姓重叠的情况。这个可以收集一些
