### ISSUE TITLE
0.0.4版本无法抓取元数据（自动和手动抓取都失效）

### ISSUE THREAD

**Issue by Miaoyifei-mz** [l0o0/jasminum#8]
您好，今天我更新到 0.0.4版本后发现无法抓取元数据（自动和手动抓取都失效），想请大佬看看出了什么问题。（运行环境：MacOS Catalina 10.15.4）

**Comment by l0o0** [comment]
@Miaoyifei-mz 麻烦你提供一下你要抓取的那个文件的文件名

**Comment by Miaoyifei-mz** [comment]
新型纤维状能源器件的发展和思考.pdf

**Comment by Miaoyifei-mz** [comment]
您好，像是这篇 `固态锂电池复合型聚合物电解质研究.pdf`学位论文，我刚试了下 0.0.2 版本是能够抓取的，但 0.0.4版本就不行了

**Comment by Miaoyifei-mz** [comment]
您好，Zotero的版本号是**5.0.90-beta.2+8614e73aa**

**Comment by l0o0** [comment]
嗯，我知道原因了，因为我现在把文件名的格式当成配置选项了，你去茉莉花配置选项页面，设置一下。默认是文件名是title_auth 这样的形式。你这个是只有title，你把配置改成 {%t}，就可以了

**Comment by l0o0** [comment]
![图片](https://user-images.githubusercontent.com/2743744/89983971-32eafa00-dcab-11ea-80c6-d337bb4435a6.png)
配置信息在这里

**Comment by Miaoyifei-mz** [comment]
嗯嗯，解决了，谢谢大佬！
