### ISSUE TITLE
无法抓取万方和维普网页上的题录

### ISSUE THREAD

**Issue by yuzixieshouhuajiaqi** [l0o0/jasminum#81]
报告 ID: 1447782360
![image](https://user-images.githubusercontent.com/76084234/162568236-a0b0169e-e188-4d1a-bc5b-1d1726b6c58f.png)

**Comment by jiaojiaodubai** [comment]
中文网站的抓取问题请到[这里](https://github.com/l0o0/translators_CN/issues/)反馈
