### ISSUE TITLE
换了新电脑后，用插件抓每天的第一篇知网文献总是失败

### ISSUE THREAD

**Issue by RinkoooZ** [l0o0/jasminum#83]
月初更换了电脑，但是每天用zotero抓第一篇知网文献总是只能抓题录，抓不到pdf，但是第二篇又莫名其妙地好了，题录和pdf都可以download，好奇怪啊~
求问如何解决~

**Comment by l0o0** [comment]
我问一上，你是先打开浏览器还是Zotero？

**Comment by RinkoooZ** [comment]
> 

先开浏览器，不过这两天居然奇迹般好了

**Comment by l0o0** [comment]
先打开浏览器，应该会先使用默认的翻译器。不过这个我没有仔细研究过
