### ISSUE TITLE
期刊期号抓取能否改下格式去掉字符串前面的“0”

### ISSUE THREAD

**Issue by mrsunhuang** [l0o0/jasminum#85]
您好，期刊期号抓取能否改下格式去掉字符串前面的“0”
比如，哈丽代姆·居麦, 宁松瑞, 王全九, 等. 施加PAM与CMC对土壤水分入渗与蒸发特征的影响[J]. 水土保持学报, 2020, 34(01): 121-127+134.
这篇文献中，34(01) 为34卷第1期，按照国标
应该34(1)，10一下应该去掉0
能否改一下期号的字符串格式？
谢谢

**Comment by l0o0** [comment]
中文翻译器已经提交了[更新](https://github.com/l0o0/translators_CN/commit/1f79014d42f0f7ad787a4322816149e85f014d5a)，可以试试更新知网翻译器

https://github.com/l0o0/translators_CN

**Comment by mrsunhuang** [comment]
哇！太棒了，
这下文献引用完美了，非常感谢您
