### ISSUE TITLE
希望支持更多标题检索格式

### ISSUE THREAD

**Issue by fangzhegeo** [l0o0/jasminum#90]
已经下载的论文很多都已经按自己的习惯改过文件名，如
- \{年份}_\{作者}\_{期刊}\_{题目}
- \{年份}\_{期刊}\_{题目}

这些论文无法用jasminum检索，希望增加更多检索格式，或者让用户自定义文件名的结构

**Comment by l0o0** [comment]
同学，能否提供两个文件名，按照你上面的格式。我这里测试一下

**Comment by fangzhegeo** [comment]
作者你好，下面是一些示例：

- 2015_李德仁_测绘学报_论夜光遥感数据挖掘
- 2016_测绘学报_地球剖分格网研究进展综述
- 2004_李德仁_武大学报_空间信息语义网格

其中，第三个论文的期刊名应该是《武汉大学学报·信息科学版》，但我按照习惯叫法命名为了《武大学报》

**Comment by l0o0** [comment]
` {%y}_{%g}_{%j}_{%t}`，同学可以试试这处模板，设置那里是可以编辑的
