### ISSUE TITLE
无法抓取知网元数据

### ISSUE THREAD

**Issue by JohnStuartLee** [l0o0/jasminum#91]
这两天导入论文的时候会出现这样的错误：
抓取一篇中文论文（例：高压流动体系CO2水合物生长动力学特性）的知网元数据时，会出现“选择条目”对话框（如下），内容全部无关且包含乱码。
![图片](https://user-images.githubusercontent.com/24764661/166112752-ecb6a8f0-1dd8-4c86-9d44-2b52ca8af777.png)
关闭此窗口后右下角会出现如下提示：
![图片](https://user-images.githubusercontent.com/24764661/166112845-895b9ede-8b2e-4e46-b350-af3b3a49799e.png)

zotero版本：6.0.6
jasminum版本：0.1.6
中文翻译器已更新至最新

**Comment by l0o0** [comment]
感谢同学的使用。
我这边测试，这篇可以正常识别。
不过我建议你把这篇PDF重命名一下，高压流动体系CO2水合物生长动力学特性.pdf -> 高压流动体系 水合物生长动力学特性.pdf。 中间的CO2用空格替换。然后设置里的模板设置为{%t} 然后再试试
![图片](https://user-images.githubusercontent.com/2743744/166142136-849f308e-9c95-4e49-bcca-deab834203ca.png)

**Comment by JohnStuartLee** [comment]
感谢您的回复
已经可以正常使用，应该是模板设置的问题
