### ISSUE TITLE
首选项界面显示不全

### ISSUE THREAD

**Issue by YunLiu96** [l0o0/jasminum#92]
更新到0.1.7版本以后，打开首选项，首选项窗口显示不全，且无法缩小、移动，移除jasminum插件之后，首选项窗口显示完整。

**Comment by l0o0** [comment]
@YunLiu96 不知道现在这个问题解决了没有

**Comment by YunLiu96** [comment]
已解决






发件人：Linxzh ***@***.***>
发送日期：2022-10-22 20:27:49
收件人：l0o0/jasminum ***@***.***>
抄送人：YunLiu96 ***@***.***>,Mention ***@***.***>
主题：Re: [l0o0/jasminum] 首选项界面显示不全 (Issue #92)

Reopened #92.
