### ISSUE TITLE
右键菜单没有抓取知网元数据，如图~

### ISSUE THREAD

**Issue by colaaaaaa** [l0o0/jasminum#96]
![image](https://user-images.githubusercontent.com/39424684/170899502-cdb0ec90-07ba-4bd3-aeeb-409ac0a5ea31.png)
![image](https://user-images.githubusercontent.com/39424684/170899519-538482fb-abe7-445b-ade8-6a1b316ece49.png)

**Comment by l0o0** [comment]
同学，你截图的这个条目，已经是一个完整的条目了，应该是已经有元数据了。所以我在菜单展示时做了判断，直接就不显示了。

如果你右键一个刚拖入的PDF，这个PDF不在某个条目下，那应该会显示出菜单的。

**Comment by colaaaaaa** [comment]
就是为了抓取目录呀~没有目录....还是说有些论文抓取不到目录呀？

**Comment by colaaaaaa** [comment]
嗯嗯~那有些完整的条目无法获得目录嘛~

**Comment by l0o0** [comment]
@colaaaaaa 你说的目录，是指PDF那种书签目录么？我看你这个条目是期刊类型。期刊类型目前知网上没有找到具体的目录页码信息。学校论文一般是有的。而且期刊论文一般都很短

**Comment by colaaaaaa** [comment]
soga~了解啦！谢谢您的耐心解答~！




------------------&nbsp;Original message&nbsp;------------------
From: "Linxzh"; 
Sendtime: Monday, May 30, 2022 10:00 AM
To: "l0o0/jasminum"; 
Cc: ***@***.***>; "Mention"; 
Subject: Re: [l0o0/jasminum] 右键菜单没有抓取知网元数据，如图~ (Issue #96)





 
@colaaaaaa 你说的目录，是指PDF那种书签目录么？我看你这个条目是期刊类型。期刊类型目前知网上没有找到具体的目录页码信息。学校论文一般是有的。而且期刊论文一般都很短
