### ISSUE TITLE
抓取知网元数据后没用任何反应

### ISSUE THREAD

**Issue by bbozhu** [l0o0/jasminum#98]
如题所示，抓取知网元数据后没有任何反应。一周之前应该是还能用的，已经尝试更新茉莉花翻译器，没有效果。
![屏幕截图 2022-06-01 161724](https://user-images.githubusercontent.com/54619498/171363705-351122c3-994c-4a90-b409-e20690f06e9a.jpg)

**Comment by l0o0** [comment]
是所有的PDF都失败么，还是说只有个别文件有问题？可以把失败的文件名放上来，我测试一下

**Comment by wowowo12438** [comment]
> 是所有的PDF都失败么，还是说只有个别文件有问题？可以把失败的文件名放上来，我测试一下

感谢您的回复，我已经询问过其他人，他们的pdf可以正常获取，但我所有的文件均不能正常获取，失败文件名为《旋翼无人机航磁总场补偿技术研究_赵肖.pdf》，现在已经通过网页抓取元数据将就一下。

**Comment by l0o0** [comment]
识别异常的时候有什么提示么？如果没有提示就不太好解决了。如果出现其他情况，麻烦再联系

**Comment by jisidehuli** [comment]
报告，我的也出现这个问题了，今天刚刚安装的茉莉花，同样也无法抓取元数据。
[不过现在有几个点值得怀疑，却不能确定：]
1. 我的论文时先下了caj格式，然后通过全球学术快报导出为pdf的
2. 论文直接拖进zotero中，在storage的文件夹中全部自动创建了文件夹（文件夹命名并非pdf命名）
在以上这两种情况下是无法获取到知网元数据。
直接打开知网用zotero的插件抓取后，茉莉花可用。

**Comment by l0o0** [comment]
> 报告，我的也出现这个问题了，今天刚刚安装的茉莉花，同样也无法抓取元数据。
> [不过现在有几个点值得怀疑，却不能确定：]

是否有什么提示信息，比如弹窗之类的？

**Comment by jisidehuli** [comment]
没有弹窗，直接显示未查询到结果。


<img width="1150" alt="获取数据失败" src="https://user-images.githubusercontent.com/39455147/189844031-509d6815-fcb8-4532-9954-203a46f900cc.png">

昨天的图补一下：
<img width="920" alt="zotero的storage文件夹" src="https://user-images.githubusercontent.com/39455147/189844436-1e0ababd-93d4-4d9a-a4fc-926fcf220ac7.png">

**Comment by l0o0** [comment]
@jisidehuli 可能是这个文件名有点问题。你看这个文件名作者后面有2个点，你重复名，删掉一个点再试试

**Comment by jisidehuli** [comment]
可以正常抓取了，感谢感谢🙏

**Comment by jisidehuli** [comment]
直接更改好像是可以了。
如果不行的话可以把源文件批量改名，然后拖入，也会自动获取到信息了👍。
感谢感谢

**Comment by Yolo9958** [comment]
我也遇到了这个问题，之前是一次拖进去多个PDF的话无法拉取元数据，需要慢慢放入，今天怎么都不行，不论是使用“重新抓取PDF元数据”还是知网助手下的“抓取知网元数据”，特别是“抓取知网元数据”点击后没有反应
<img width="551" alt="截屏2023-07-07 下午5 36 50" src="https://github.com/l0o0/jasminum/assets/57700443/969425e8-2a16-4df3-a129-9271d97c348e">

**Comment by Bigconfidence666** [comment]
> 我也遇到了这个问题，之前是一次拖进去多个PDF的话无法拉取元数据，需要慢慢放入，今天怎么都不行，不论是使用“重新抓取PDF元数据”还是知网助手下的“抓取知网元数据”，特别是“抓取知网元数据”点击后没有反应 <img alt="截屏2023-07-07 下午5 36 50" width="551" src="https://user-images.githubusercontent.com/57700443/251701543-969425e8-2a16-4df3-a129-9271d97c348e.png">

我也遇到了这个问题，抓取知网元数据没有反应

**Comment by Yolo9958** [comment]
> 

我在闲鱼找人解决了，他远程给我替换了translators文件夹，如果你需要，可以加我邮箱，给你vx，这里不方便哈哈，1253999509@qq.com

**Comment by Bigconfidence666** [comment]
> > 
> 
> 我在闲鱼找人解决了，他远程给我替换了translators文件夹，如果你需要，可以加我邮箱，给你vx，这里不方便哈哈，[1253999509@qq.com](mailto:1253999509@qq.com)

你是说的这个文件夹是从作者网页下的翻译器文件夹么？但如果下次知网的翻译器更新的话，这个文件夹又得远程更换？

**Comment by l0o0** [comment]
@Bigconfidence666 @Yolo9958 你们两位的文件名模板设置，是不是 {%t}_{%g} ？

还有就是替换translators文件夹，应该是转换器的问题。转换器可以在茉莉花插件里下载。（转换器就是翻译器，现在叫翻译器有些不适合）

**Comment by Bigconfidence666** [comment]
> @Bigconfidence666 @Yolo9958 你们两位的文件名模板设置，是不是 {%t}_{%g} ？
> 
> 还有就是替换translators文件夹，应该是转换器的问题。转换器可以在茉莉花插件里下载。（转换器就是翻译器，现在叫翻译器有些不适合）

是用的 {%t}_{%g}，也在茉莉花首选项刷新并更新了转换器，在网页更新了connector，还是没反应；重装茉莉花，还是没反应555

**Comment by zizerplus** [comment]
我也出现了这个问题然后自己解决了，过程如下：
问题表现为不论是导入pdf还是菜单选择抓取知网元数据后没反应也没任何弹窗。更新转换器更新connector确定不是转换器的原因，因为浏览器插件完全正常抓取知网。而且感觉不是软件版本或者网络的问题，因为几天前刚安装zotero和茉莉花的时候完全能正常工作，当时挂着vpn也能正常抓取。
后来发现每次重启zotero第一次尝试抓取知网元数据能正常工作，或者抓取失败也会有弹窗（这时候再进行第二次抓取就可以工作），第二次及之后就不行了，总之就是只能成功抓取一次，考虑是不是插件冲突。
结论是一个叫[zotero-updateifs]的可以更新期刊信息和影响因子的插件(https://github.com/redleafnew/zotero-updateifs)可能和茉莉花冲突，只要关闭这个插件甚至不用卸载，重启一下zotero，如果茉莉花转换器设置正常就可以正常给pdf抓取知网元数据了。
感觉这个问题的顺序可能是启动zotero后第一次抓取元数据→茉莉花抓取成功新建父条目→updateifs自动更新条目里的期刊信息→一些冲突→茉莉花后续不能抓取。

**Comment by Fan-123haha** [comment]
> 我也出现了这个问题然后自己解决了，过程如下： 问题表现为不论是导入pdf还是菜单选择抓取知网元数据后没反应也没任何弹窗。更新转换器更新connector确定不是转换器的原因，因为浏览器插件完全正常抓取知网。而且感觉不是软件版本或者网络的问题，因为几天前刚安装zotero和茉莉花的时候完全能正常工作，当时挂着vpn也能正常抓取。 后来发现每次重启zotero第一次尝试抓取知网元数据能正常工作，或者抓取失败也会有弹窗（这时候再进行第二次抓取就可以工作），第二次及之后就不行了，总之就是只能成功抓取一次，考虑是不是插件冲突。 结论是一个叫[zotero-updateifs]的可以更新期刊信息和影响因子的插件(https://github.com/redleafnew/zotero-updateifs) 可能和茉莉花冲突，只要关闭这个插件甚至不用卸载，重启一下zotero，如果茉莉花转换器设置正常就可以正常给pdf抓取知网元数据了。 感觉这个问题的顺序可能是启动zotero后第一次抓取元数据→茉莉花抓取成功新建父条目→updateifs自动更新条目里的期刊信息→一些冲突→茉莉花后续不能抓取。

6，解决了！！！我装了仨获取影响因子的，也不知道哪个导致的问题，反正都disable就可以用了
